<div id="main-content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    
                     <div class="btn-group">
                        <a href="<?php print($this->baseUrl()); ?>/admin/staff/add/" id="table-edit_new" class="btn btn-danger">
                            <?php echo $this->translate("Add-New");?> <i class="fa fa-plus"></i>
                        </a>
                    </div>
                    
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 table-responsive m-t-20 table_padding">
                            <table class="table table-bordered table_obtor_data table-hover">
                                <thead>
                                    <tr>
                                        <th class="table_id table_head"><?php echo $this->translate("ID");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Name-with-initials-head");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Table-Contact-Numbers");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("E-mail-Address");?></th>
                           
                                        <th class="table_head table_data_xx"><?php echo $this->translate("Table-Contract-Status");?></th>
                                        <th class="table_head table_data_xxxx"><?php echo $this->translate("Table-Employee-Type");?></th>
                                        <th class="table_head table_data_xx"><?php echo $this->translate("Status");?></th>
                                        <th class="text-center table_head data_table_action"><?php echo $this->translate("Actions");?></th>
                                    </tr>
                                </thead>
                                <tbody class="no-bd-y">

                                    <?php if ($this->employeeInfo) { ?>
                                        <?php foreach ($this->employeeInfo As $eIndex => $employee) { ?>
                                            <tr>
                                                <td>
                                                    <a title="<?php echo $this->translate("View");?>" href="<?php print($this->baseUrl()); ?>/admin/staff/view/id/<?php print($employee->getId()); ?>">
                                                    <?php print($employee->getEmployeeNumber()); ?>
                                                    </a>
                                                </td>
                                                <td><?php print($employee->getNameWithInitials()); ?></td>
                                                <td>
                                                    <div class="col-md-12 col-sm-12 col-xs-12" id="tooltips">
                                                        <a rel="tooltip" data-toggle="tooltip" data-placement="top" title="<?php print($employee->getTelephoneNumberMobile()); ?>/<?php print($employee->getTelephoneNumberResidence()); ?>">
                                                          <?php print($employee->getTelephoneNumberMobile()); ?>
                                                        </a>
                                                    </div> 
                                                    
                                                </td>
                                                <td><?php print($employee->getEMailAddressOffice()); ?></td>
                                          
                                                <td>
                                                    <?php if($employee->getContractStatus() == "Probation"){?>
                                                    <?php echo $this->translate("Probation"); ?>
                                                    <?php } else {?>
                                                    <?php echo $this->translate("Confirmed"); ?>
                                                    <?php } ?>
                                                </td>
                                                <td>
                                                    <?php print($this->getType($employee->getEmployeeType())->getName()); ?>
                                                </td>
                                                <td>
                                                    <?php if($employee->getEmployeeStatus() == "In-Service") {?>
                                                    <span class="label bg-green"><?php echo $this->translate("In-Service"); ?></span>
                                                    <?php } else {?>
                                                    <span class="label bg-red"><?php echo $this->translate("Not-In-Service"); ?></span>
                                                    <?php } ?>
                                                </td>
                                                
                                                <td class="text-center">
                                                    <a title="<?php echo $this->translate("Edit");?>" href="<?php print($this->baseUrl()); ?>/admin/staff/edit/id/<?php print($employee->getId()); ?>"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_edit.png" /></a>
                                                    <a title="<?php echo $this->translate("Delete");?>" href="<?php print($this->baseUrl()); ?>/admin/staff/delete/id/<?php print($employee->getId()); ?>" class="form-data-delete"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_drop.png" /></a>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                    <?php } else {?>
                                            <tr>
                                                <td colspan="8" class="table_data_not_found"><?php echo $this->translate("Records-Not-Available");?></td>
                                            </tr>
                                    <?php } ?>

                                </tbody>
                            </table>

                        </div>
                    </div>
                    
                    
                    <?php if(count($this->employeeInfo)>0){?>
			<?php echo $this->partial('common/_pagination.phtml', array('paginationData' => $this->paggination)); ?>
                    <?php } ?>
                    
                </div>
            </div>
        </div>
    </div>
</div>
