<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <title><?php echo $this->translate("Login"); ?> - <?php echo $this->translate("Staff-Portal"); ?> - <?php echo $this->translate("System-Name-Version"); ?></title>

        <link href="<?php print($this->baseUrl());?>/assets/staff-login/css/style.default.css" rel="stylesheet">

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="<?php print($this->baseUrl());?>/assets/staff-login/js/html5shiv.js"></script>
        <script src="<?php print($this->baseUrl());?>/assets/staff-login/js/respond.min.js"></script>
        <![endif]-->
    </head>

    <body class="signin">
        
        
        <section>
            
            <?php echo $this->layout()->content ?>
            
        </section>


        <script src="<?php print($this->baseUrl());?>/assets/staff-login/js/jquery-1.11.1.min.js"></script>
        <script src="<?php print($this->baseUrl());?>/assets/staff-login/js/jquery-migrate-1.2.1.min.js"></script>
        <script src="<?php print($this->baseUrl());?>/assets/staff-login/js/bootstrap.min.js"></script>
        <script src="<?php print($this->baseUrl());?>/assets/staff-login/js/modernizr.min.js"></script>
        <script src="<?php print($this->baseUrl());?>/assets/staff-login/js/pace.min.js"></script>
        <script src="<?php print($this->baseUrl());?>/assets/staff-login/js/retina.min.js"></script>
        <script src="<?php print($this->baseUrl());?>/assets/staff-login/js/jquery.cookies.js"></script>

        <script src="<?php print($this->baseUrl());?>/assets/staff-login/js/custom.js"></script>

    </body>
</html>