 <div id="main-content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="btn-group">
                        <a href="<?php print($this->baseUrl()); ?>/admin/user/add" id="table-edit_new" class="btn btn-danger">
                            <?php echo $this->translate("Add-New");?> <i class="fa fa-plus"></i>
                        </a>
                    </div>
                    
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 table-responsive">
                           <table class="table table-bordered table_obtor_data table-hover">
                                <thead class="no-bd">
                                    <tr>
                                        <th class="table_id table_head"><?php echo $this->translate("ID");?></th>
                                        <th class="table_head"><?php echo $this->translate("Full-Name");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Email-Address");?></th>
                                        <th class="table_head"><?php echo $this->translate("Role-Name");?></th>
                                         <th class="table_data table_head"><?php echo $this->translate("Status");?></th>
                                        <th class="text-center table_head data_table_action"><?php echo $this->translate("Actions");?></th>
                                    </tr>
                                </thead>
                                <tbody class="no-bd-y">

                                    <?php if ($this->users) { ?>
                                        <?php foreach ($this->users As $uIndex => $userInfo) { ?>
                                            <tr>
                                                <td><?php print($uIndex+1); ?></td>
                                                <td><?php print($userInfo->getFullName()); ?></td>
                                                <td><?php print($userInfo->getEmailAddress()); ?></td>
                                                <td><?php print($userInfo->getUserRole()->getName()); ?></td>
                                                <td>
                                                    <?php if($userInfo->getStatusIs() == 1) {?>
                                                    <?php echo $this->translate("Enabled"); ?>
                                                    <?php } elseif($userInfo->getStatusIs() == 2){?>
                                                    <?php echo $this->translate("Disabled"); ?>
                                                    <?php } elseif($userInfo->getStatusIs() == 3){?>
                                                    <?php echo $this->translate("Suspended"); ?>
                                                    <?php } ?>
                                                </td>
                                                <td class="text-center">
                                                    <a title="<?php echo $this->translate("Edit");?>" href="<?php print($this->baseUrl()); ?>/admin/user/edit/id/<?php print($userInfo->getId()); ?>"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_edit.png" /></a>
                                                    <a title="<?php echo $this->translate("View-User-Logs");?>" href="<?php print($this->baseUrl()); ?>/admin/user/view-log/id/<?php print($userInfo->getId()); ?>"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_views.png" /></a>
                                                    <a title="<?php echo $this->translate("Delete");?>" href="<?php print($this->baseUrl()); ?>/admin/user/delete/id/<?php print($userInfo->getId()); ?>" class="form-data-delete"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_drop.png" /></a>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                   <?php } else {?>
                                            <tr>
                                                <td colspan="6" class="table_data_not_found"><?php echo $this->translate("Records-Not-Available");?></td>
                                            </tr>
                                    <?php } ?>

                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
