<div id="main-content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    
                     <div class="btn-group">
                        <a href="<?php print($this->baseUrl()); ?>/admin/vacancy/add/" id="table-edit_new" class="btn btn-danger">
                            <?php echo $this->translate("Add-New");?> <i class="fa fa-plus"></i>
                        </a>
                    </div>
                    
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 table-responsive m-t-20">
                           <table class="table table-bordered table_obtor_data table-hover">
                                <thead class="no-bd">
                                    <tr>
                                        <th class="table_id table_head"><?php echo $this->translate("ID");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Title");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Category");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Publish-Start-Date");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Publish-End-Date");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Status");?></th>
                                        <th class="text-center table_head data_table_action"><?php echo $this->translate("Actions");?></th>
                                    </tr>
                                </thead>
                                <tbody class="no-bd-y">

                                    <?php if ($this->vacancyInfo) { ?>
                                        <?php foreach ($this->vacancyInfo As $vIndex => $vacancy) { ?>
                                            <tr>
                                                <td>
                                                    <a title="<?php echo $this->translate("View");?>" href="<?php print($this->baseUrl()); ?>/admin/vacancy/view/id/<?php print($vacancy->getId()); ?>">
                                                    <?php print($vacancy->getId()); ?>
                                                    </a>
                                                </td>
                                                <td><?php print($vacancy->getVacancyTitle()); ?> (<?php print($vacancy->getQty());?>)</td>
                                                 <td><?php print($vacancy->getCategory()); ?></td>
                                            
                                                <td><?php print($vacancy->getPublishStartDate()); ?></td>
                                              <td><?php print($vacancy->getPublishEnddate()); ?></td>
                                                
                                                <td>
                                                    <span class="label bg-green"><?php echo $this->translate("Published"); ?></span>
                                                </td>
                                                
                                                <td class="text-center">
                                                    <a title="<?php echo $this->translate("Edit");?>" href="<?php print($this->baseUrl()); ?>/admin/vacancy/edit/id/<?php print($vacancy->getId()); ?>"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_edit.png" /></a>
                                                    <a title="<?php echo $this->translate("Delete");?>" href="<?php print($this->baseUrl()); ?>/admin/vacancy/delete/id/<?php print($vacancy->getId()); ?>" class="form-data-delete"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_drop.png" /></a>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                   <?php } else {?>
                                            <tr>
                                                <td colspan="7" class="table_data_not_found"><?php echo $this->translate("Records-Not-Available");?></td>
                                            </tr>
                                    <?php } ?>

                                </tbody>
                            </table>

                        </div>
                    </div>
                    
                    
                    <?php if(count($this->vacancyInfo)>0){?>
			<?php echo $this->partial('common/_pagination.phtml', array('paginationData' => $this->paggination)); ?>
                    <?php } ?>
                    
                </div>
            </div>
        </div>
    </div>
</div>