   <div id="main-content">
            
            <div class="row">
                <div class="col-md-12">
            
                    
                    
                    <div class="panel panel-default">
                   
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <form id="form_inquire" name="form_inquire" role="form" method="post" class="form-horizontal">
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Full-Name");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <input parsley-minlength="3" class="form-control normal_input" type="text" name="txtFullName" id="txtFullName"/>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Telephone-Number");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <input parsley-minlength="3" class="form-control normal_input" type="text" name="txtTelephoneNumber" id="txtTelephoneNumber"/>
                                            </div>
                                        </div>
                                        
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Contact-Number");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <input parsley-minlength="3" class="form-control normal_input" type="text" name="txtContactNumber" id="txtContactNumber"/>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Email-Address");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <input parsley-minlength="3" class="form-control normal_input" type="text" name="txtEmailAddress" id="txtEmailAddress"/>
                                            </div>
                                        </div>
                                        
                                      
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Gender");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                 <select  class="form-control normal_input" name="txtGender" id="txtGender">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                     <option value="male"><?php echo $this->translate("male"); ?></option>
                                                     <option value="female"><?php echo $this->translate("female"); ?></option>
                                                </select>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Inquire-Media");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <select  class="form-control normal_input" name="txtInquireMedia" id="txtInquireMedia">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <?php foreach($this->inquireMediaList As $iMedia=>$inquireMedia){?>
                                                     <option value="<?php print($inquireMedia);?>"><?php echo $this->translate($inquireMedia); ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                    <span class="panel-inner-title"><strong><?php echo $this->translate("Postal-Address"); ?></strong></span>
                                </div>


                                <div class="form-group">
                                    <label class="form-label"><strong><?php echo $this->translate("Address"); ?></strong></label>
                                    <div class="controls">
                                        <input class="form-control normal_input" type="text" id="txtPostalAddressAddress" name="txtPostalAddressAddress">
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="form-label"><strong><?php echo $this->translate("Street"); ?></strong>
                                    </label>
                                    <div class="controls">
                                        <input class="form-control normal_input" type="text" id="txtPostalAddressStreet" name="txtPostalAddressStreet">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="form-label"><strong><?php echo $this->translate("City"); ?></strong>
                                    </label>
                                    <div class="controls">
                                        <input class="form-control normal_input" type="text" id="txtPostalAddressCity" name="txtPostalAddressCity">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="form-label"><strong><?php echo $this->translate("State"); ?></strong>
                                    </label>
                                    <div class="controls">
                                        <input class="form-control normal_input" type="text" id="txtPostalAddressState" name="txtPostalAddressState">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="form-label"><strong><?php echo $this->translate("Zip-Postal-Code"); ?></strong>
                                    </label>
                                    <div class="controls">
                                        <input class="form-control normal_input" type="text" id="txtPostalAddressZip" name="txtPostalAddressZip">
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label class="form-label"><strong><?php echo $this->translate("Country"); ?></strong>
                                    </label>
                                    <div class="controls">
                                        <select  class="form-control normal_input" name="txtPostalAddressCountry" id="txtPostalAddressCountry">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <?php foreach($this->countryNameList As $cList=>$countryName){?>
                                                     <option value="<?php print($countryName->getCountryCode());?>"><?php echo $this->translate($countryName->getName()); ?></option>
                                                    <?php } ?>
                                        </select>
                                    </div>
                                </div>
                                        
                                        
                                        
                                        <div class="form-group">
                                    <span class="panel-inner-title"><strong><?php echo $this->translate("Inquire-Location"); ?></strong></span>
                                </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Country-Name");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <select parsley-minlength="3" class="form-control normal_input" name="txtCountry" id="txtCountry">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <?php foreach($this->countries As $cIndex=>$country){?>
                                                     <option value="<?php print($country->getId());?>"><?php print($country->getName());?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Region-Name");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <span id="region">
                                                <select parsley-minlength="3" class="form-control normal_input" name="txtRegion" id="txtRegion">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                </select>
                                                </span>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Branch-Name");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <span id="branch">
                                                <select parsley-minlength="3" class="form-control normal_input" name="txtBranchName" id="txtBranchName">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                </select>
                                                </span>
                                            </div>
                                        </div>
                                        
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Department-Name");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <span id="department">
                                                <select parsley-minlength="3" class="form-control normal_input" name="txtDepartmentName" id="txtDepartmentName">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                </select>
                                                </span>
                                            </div>
                                        </div>   
                                        
                                        
                                        <div class="form-group">
                                    <label class="form-label"><strong><?php echo $this->translate("Status"); ?></strong>
                                    </label>
                                    <div class="controls">
                                       
                                        <select  class="form-control normal_input" name="txtStatus" id="txtStatus">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <?php foreach($this->inquireStatusList As $iList=>$inquireStatus){?>
                                                     <option value="<?php print($inquireStatus);?>"><?php echo $this->translate($inquireStatus); ?></option>
                                                    <?php } ?>
                                        </select>
                                    </div>
                                </div>
                                        
                                          <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Description");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <textarea parsley-minlength="3" class="form-control" type="text" name="txtDescription" id="txtDescription"></textarea>
                                            </div>
                                        </div>
                                        
                                        
                                        
                                   
                                        <div class="form-group text-left">
                                            <button class="btn btn-blue" type="submit" name="Submit" id="Submit"><?php echo $this->translate("Submit");?></button>
                                            <button type="reset" class="btn btn-default"><?php echo $this->translate("Cancel");?></button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    
                    
                </div>
            </div>
            
                        
            
                        
        </div>
<script src="<?php print($this->baseUrl());?>/assets/validator/admin/inquire.js"></script>