<div id="main-content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    
                     <div class="btn-group">
                        <a href="<?php print($this->baseUrl()); ?>/admin/inquire/add/" id="table-edit_new" class="btn btn-danger">
                            <?php echo $this->translate("Add-New");?> <i class="fa fa-plus"></i>
                        </a>
                    </div>
                    
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 table-responsive m-t-20">
                            <table class="table table-bordered table_obtor_data table-hover">
                                <thead class="no-bd">
                                    <tr>
                                        <th class="table_id table_head"><strong><?php echo $this->translate("ID");?></strong></th>
                                        <th class="table_data table_head"><strong><?php echo $this->translate("Fullname");?></strong></th>
                                        <th class="table_data table_head"><strong><?php echo $this->translate("Telephone_Number");?></strong></th>
                                        <th class="table_data table_head"><strong><?php echo $this->translate("Gender");?></strong></th>
                                        <th class="table_data table_head"><strong><?php echo $this->translate("State");?></strong></th>
                                        <th class="table_data table_head"><strong><?php echo $this->translate("Country");?></strong></th>
                                        <th class="table_data table_head"><strong><?php echo $this->translate("Current_Status");?></strong></th>
                                        <th class="text-center table_head data_table_action"><strong><?php echo $this->translate("Actions");?></strong></th>
                                    </tr>
                                </thead>
                                <tbody class="no-bd-y">

                                    <?php if ($this->inquireInformation) { ?>
                                        <?php foreach ($this->inquireInformation As $vIndex => $inquire) { ?>
                                            <tr>
                                                <td>
                                                    <a title="<?php echo $this->translate("View");?>" href="<?php print($this->baseUrl()); ?>/admin/inquire/view/id/<?php print($inquire->getId()); ?>">
                                                    <?php print($inquire->getId()); ?>
                                                    </a>
                                                </td>
                                                <td><?php print($inquire->getFullName()); ?></td>
                                                
                                                <td>
                                                    <div class="col-md-12 col-sm-12 col-xs-12" id="tooltips">
                                                        <a rel="tooltip" data-toggle="tooltip" data-placement="top" title="<?php print($inquire->getContactNumber()); ?>/<?php print($inquire->getTelephoneNumber()); ?>">
                                                          <?php print($inquire->getContactNumber()); ?>
                                                        </a>
                                                    </div> 
                                                    
                                                </td>
                                              <td><?php print($inquire->getGender()); ?></td>
                                              <td>
                                                  <?php 
                                                  if($inquire->getRegion() != ''){
                                                      if($this->getRegion($inquire->getRegion())){
                                                        print($this->getRegion($inquire->getRegion())->getName());
                                                      }
                                                  } 
                                                  ?>
                                              </td>
                                              <td>
                                                  <?php 
                                                  if($inquire->getCountry()){
                                                      if($this->getCountry($inquire->getCountry())){
                                                            print($this->getCountry($inquire->getCountry())->getName());
                                                      }
                                                  }
                                                  ?>
                                              </td>
                                              <td><?php print($inquire->getStatus()); ?></td>
                                                
                                                <td class="text-center">
                                                    <a title="<?php echo $this->translate("Edit");?>" href="<?php print($this->baseUrl()); ?>/admin/inquire/edit/id/<?php print($inquire->getId()); ?>"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_edit.png" /></a>
                                                    <a title="<?php echo $this->translate("Delete");?>" href="<?php print($this->baseUrl()); ?>/admin/inquire/delete/id/<?php print($inquire->getId()); ?>" class="form-data-delete"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_drop.png" /></a>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                    <?php } else {?>
                                            <tr>
                                                <td colspan="8" class="table_data_not_found"><?php echo $this->translate("Records-Not-Available");?></td>
                                            </tr>
                                    <?php } ?>

                                </tbody>
                            </table>

                        </div>
                    </div>
                    
                    
                    <?php if(count($this->inquireInformation)>0){?>
			<?php echo $this->partial('common/_pagination.phtml', array('paginationData' => $this->paggination)); ?>
                    <?php } ?>
                    
                </div>
            </div>
        </div>
    </div>
</div>