   <div id="main-content">
            
            <div class="row">
                <div class="col-md-12">
            
                    
                    
                    <div class="panel panel-default">
                   
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <form id="form_inquire" name="form_inquire" role="form" method="get" class="form-horizontal" action="<?php print($this->baseUrl());?>/admin/inquire/index/">
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Full-Name");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <input parsley-minlength="3" class="form-control normal_input" type="text" name="full-name" id="full-name"/>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Telephone-Number");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <input parsley-minlength="3" class="form-control normal_input" type="text" name="telephone-number" id="telephone-number"/>
                                            </div>
                                        </div>
                                        
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Contact-Number");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <input parsley-minlength="3" class="form-control normal_input" type="text" name="contact-number" id="contact-number"/>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Email-Address");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <input parsley-minlength="3" class="form-control normal_input" type="text" name="email-address" id="email-address"/>
                                            </div>
                                        </div>
                                        
                                      
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Inquire-Media");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <select  class="form-control normal_input" name="inquire-media" id="inquire-media">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <?php foreach($this->inquireMediaList As $iMedia=>$inquireMedia){?>
                                                     <option value="<?php print($inquireMedia);?>"><?php echo $this->translate($inquireMedia); ?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                        
                              
                                        
                                        
                                        
                                        <div class="form-group">
                                    <span class="panel-inner-title"><strong><?php echo $this->translate("Inquire-Location"); ?></strong></span>
                                </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Country-Name");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <select parsley-minlength="3" class="form-control normal_input" name="country" id="country">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <?php foreach($this->countries As $cIndex=>$country){?>
                                                     <option value="<?php print($country->getId());?>"><?php print($country->getName());?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Region-Name");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <span id="region">
                                                <select parsley-minlength="3" class="form-control normal_input" name="region" id="region">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                </select>
                                                </span>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Branch-Name");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <span id="branch">
                                                <select parsley-minlength="3" class="form-control normal_input" name="branch" id="branch">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                </select>
                                                </span>
                                            </div>
                                        </div>
                                        
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Department-Name");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <span id="department">
                                                <select parsley-minlength="3" class="form-control normal_input" name="department" id="department">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                </select>
                                                </span>
                                            </div>
                                        </div>   
                                        
                                        
                                        <div class="form-group">
                                    <label class="form-label"><strong><?php echo $this->translate("Status"); ?></strong>
                                    </label>
                                    <div class="controls">
                                       
                                        <select  class="form-control normal_input" name="status" id="status">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <?php foreach($this->inquireStatusList As $iList=>$inquireStatus){?>
                                                     <option value="<?php print($inquireStatus);?>"><?php echo $this->translate($inquireStatus); ?></option>
                                                    <?php } ?>
                                        </select>
                                    </div>
                                </div>
                                        
                                          
                                   
                                        <div class="form-group text-left">
                                            <button class="btn btn-blue" type="submit" name="Submit" id="Submit"><?php echo $this->translate("Search");?></button>
                                            <button type="reset" class="btn btn-default"><?php echo $this->translate("Cancel");?></button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    
                    
                </div>
            </div>
            
                        
            
                        
        </div>
<script src="<?php print($this->baseUrl());?>/assets/validator/admin/inquire.js"></script>