<div id="main-content">
            
            <div class="row">
                <div class="col-md-12">
            
                    
                    
                    <div class="panel panel-default">
                   
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-5">
                                    <form id="form_branch" name="form_branch" role="form" method="post" class="form-horizontal">
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Country-Name");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <select parsley-minlength="3" class="form-control" name="country" id="country">
                                                    <option value="">-- select country --</option>
                                                    <?php foreach($this->countries As $cIndex=>$country){?>
                                                    <option value="<?php print($country->getId());?>" <?php if($this->branchInformation->getRegion()){if($this->branchInformation->getRegion()->getCountry()->getId() == $country->getId()){?> selected="selected" <?php }} ?> ><?php print($country->getName());?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Region-Name");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <span id="region_box">
                                                <select parsley-minlength="3" class="form-control" name="region" id="region">
                                                    <option value="">-- select region --</option>
                                                    <?php foreach($this->regions As $cIndex=>$region){?>
                                                     <option value="<?php print($region->getId());?>" <?php if($this->branchInformation->getRegion()){if($this->branchInformation->getRegion()->getId() == $region->getId()){?> selected="selected" <?php }} ?>><?php print($region->getName());?></option>
                                                    <?php } ?>
                                                </select>
                                                </span>
                                            </div>
                                        </div>
                                        
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Branch-Name");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <input parsley-minlength="3" class="form-control" type="text" name="branch_name" id="branch_name" value="<?php print($this->branchInformation->getName());?>"/>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Branch-Code");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <input parsley-minlength="3" class="form-control" type="text" name="txtBranchCode" id="txtBranchCode" value="<?php print($this->branchInformation->getPrefix());?>"/>
                                            </div>
                                        </div>
                                        
                                   
                                        <div class="form-group text-left">
                                            <button class="btn btn-blue" type="submit" name="Submit" id="Submit"><?php echo $this->translate("Submit");?></button>
                                            <button type="reset" class="btn btn-default"><?php echo $this->translate("Cancel");?></button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    
                    
                </div>
            </div> 
        </div>
<script src="<?php print($this->baseUrl());?>/assets/validator/admin/branch.js"></script>