<script src="<?php print($this->baseUrl());?>/assets/skin/plugins/Highcharts-4_0_4/js/highcharts.js"></script>
<script src="<?php print($this->baseUrl());?>/assets/skin/plugins/Highcharts-4_0_4/js/exporting.js"></script>
<div id="main-content" class="dashboard">
          <div class="row m-t-20">
            <div class="col-md-3 col-sm-12">
              <div class="panel no-bd bd-3 panel-stat">
                <div class="panel-body bg-blue p-15">
                  <div class="row m-b-10">
                    <div class="col-xs-3">
                      <i class="glyph-icon flaticon-visitors"></i>
                    </div>
                     <div class="col-xs-9">
                      <div class="live-tile" data-mode="carousel" data-direction="vertical" data-delay="3500" data-height="56">
                      <div>
                        <small class="stat-title">Visits today</small>
                        <h1 class="m-0 w-300">25 610</h1>
                     </div>
                     <div>
                        <small class="stat-title">Visits yesterday</small>
                        <h1 class="m-0 w-300">22 420</h1>
                        </div>
                      </div>
                    </div> 
                  </div>
                  <div class="row">
                    <div class="col-xs-6">
                      <small class="stat-title">New Visitors</small>
                      <div class="live-tile" data-mode="carousel" data-direction="vertical" data-delay="3500" data-height="30">
                        <div>
                        <h3 class="m-0 w-300">37.5%</h3>
                        </div>
                        <div>
                        <h3 class="m-0 w-300">34.2%</h3>
                        </div>
                      </div>
                    </div>
                    <div class="col-xs-6">
                      <small class="stat-title">Bounce Rate</small>
                      <div class="live-tile" data-mode="carousel" data-direction="vertical" data-delay="3500" data-height="30">
                        <div>
                        <h3 class="m-0 w-500">5.6%</h3>
                        </div>
                        <div>
                        <h3 class="m-0 w-500">7.4%</h3>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-3 col-sm-12">
              <div class="panel no-bd bd-3 panel-stat">
                <div class="panel-body bg-red p-15">
                  <div class="row m-b-6">
                    <div class="col-xs-3">
                      <i class="glyph-icon flaticon-educational"></i>
                    </div>
                     <div class="col-xs-9">
                      <small class="stat-title">PAGES VIEW</small>
                      <h1 class="m-0 w-500">201k</h1>
                    </div>  
                  </div>
                  <div class="row">
                    <div class="col-xs-6">
                      <small class="stat-title">Duration</small>
                      <h3 class="m-0 w-500">18:25</h3>
                    </div>
                    <div class="col-xs-6">
                      <small class="stat-title">Pages / visits</small>
                      <h3 class="m-0 w-500">21</h3>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-3 col-sm-12">
              <div class="panel no-bd bd-3 panel-stat">
                <div class="panel-body bg-green p-15">
                  <div class="row m-b-0">
                    <div class="col-xs-3">
                      <i class="glyph-icon flaticon-orders"></i>
                    </div>
                     <div class="col-xs-9">
                      <small class="stat-title">ORDERS THIS MONTH</small>
                      <div class="live-tile" data-delay="4000" data-animation-easing="fade" data-height="47">
                        <div>
                          <h1 class="m-0 w-500 bg-green">148</h1>
                        </div>
                        <div>
                          <h1 class="m-0 w-500 bg-green">+28%</h1>
                        </div>
                      </div>
                    </div>  
                  </div>
                  <div class="row">
                    <div class="col-xs-6">
                      <small class="stat-title">Last month</small>
                      <div class="live-tile" data-delay="4000" data-animation-easing="fade" data-height="30">
                        <div class="bg-green">
                        <h3 class="m-0 w-500">126</h3>
                        </div>
                        <div class="bg-green">
                        <h3 class="m-0 w-500">$12,545</h3>
                        </div>
                      </div>
                    </div>
                    <div class="col-xs-6">
                      <small class="stat-title">Last week</small>
                      <div class="live-tile" data-delay="4000" data-animation-easing="fade" data-height="30">
                        <div class="bg-green">
                        <h3 class="m-0 w-500">41</h3>
                        </div>
                        <div class="bg-green">
                        <h3 class="m-0 w-500">$4,237</h3>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-3 col-sm-12">
              <div class="panel no-bd bd-3 panel-stat">
                <div class="panel-body bg-dark p-15">
                  <div class="row m-b-6">
                    <div class="col-xs-3">
                      <i class="glyph-icon flaticon-incomes"></i>
                    </div>
                     <div class="col-xs-9">
                      <small class="stat-title">INCOMES THIS MONTH</small>
                      <h1 class="m-0 w-500">$<span class="animate-number" data-value="42567" data-animation-duration="1400">0</span></h1>
                    </div>  
                  </div>
                  <div class="row">
                    <div class="col-xs-6">
                      <small class="stat-title">Last month</small>
                      <h3 class="m-0 w-500">$<span class="animate-number" data-value="38547" data-animation-duration="1400">0</span></h3>
                    </div>
                    <div class="col-xs-6">
                      <small class="stat-title">Last week</small>
                      <h3 class="m-0 w-500">$<span class="animate-number" data-value="8754" data-animation-duration="1400">0</span></h3>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          
    
    <div class="row">
            <div class="col-md-12">
              <div class="panel">
                <div class="panel-body">
                  <div class="row">
                    
                      <script type="text/javascript">
$(function () {
    $('#attendance-summary-container').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: 'Attendance Summary Report'
        },
        subtitle: {
            text: 'From Jan 12 to Jan 16'
        },
        xAxis: {
            categories: [
                '12-Jan',
                '13-Jan',
                '14-Jan',
                '15-Jan',
                '16-Jan'
            ]
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Total Number Of Staff'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y}</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: [{
            name: 'On Duty',
            data: [150,145,125,85,161]

        }, {
            name: 'On time arrival',
            data: [120,115,106,65,120]

        }, {
            name: 'Late arrival',
            data: [30,30,20,20,41]

        }, {
            name: 'Early Off',
            data: [12,5,0,2,1]

        }, {
            name: 'On Leave',
            data: [2,15,0,7,15]

        }]
    });
});
		</script>
                
                    <div id="attendance-summary-container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
                 
                  </div>
                </div>
              </div>
            </div>
          </div>
    
    
    <div class="row">
            <div class="col-md-12">
              <div class="panel">
                <div class="panel-body">
                  <div class="row">
                    
                      <script type="text/javascript">
$(function () {
    $('#order-summary-container').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: 'Order Summary'
        },
        subtitle: {
            text: 'From Jan 01 to Jan 10'
        },
        xAxis: {
            type: 'category',
            labels: {
                rotation: -45,
                style: {
                    fontSize: '13px',
                    fontFamily: 'Verdana, sans-serif'
                }
            }
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Number of orders'
            }
        },
        legend: {
            enabled: false
        },
        tooltip: {
            pointFormat: 'Total Orders: <b>{point.y}</b>'
        },
        series: [{
            name: 'Orders',
            data: [
                ['01 Jan', 25],
                ['02 Jan', 85],
                ['03 Jan', 65],
                ['04 Jan', 20],
                ['05 Jan', 45],
                ['06 Jan', 15],
                ['07 Jan', 5],
                ['08 Jan', 0],
                ['09 Jan', 32],
                ['10 Jan', 25]
            ],
            dataLabels: {
                enabled: true,
                rotation: -90,
                color: '#FFFFFF',
                align: 'right',
                x: 4,
                y: 10,
                style: {
                    fontSize: '13px',
                    fontFamily: 'Verdana, sans-serif',
                    textShadow: '0 0 3px black'
                }
            }
        }]
    });
});
		</script>
                <div id="order-summary-container" style="min-width: 500px; height: 400px; margin: 0 auto"></div>
                 
                  </div>
                </div>
              </div>
            </div>
          </div>
    
    
    <div class="row">
            <div class="col-md-12">
              <div class="panel">
                <div class="panel-body">
                    
                    <div class="col-md-6"> 
                  <div class="row">
                    
                      <script type="text/javascript">
$(function () {

    // Radialize the colors
    Highcharts.getOptions().colors = Highcharts.map(Highcharts.getOptions().colors, function (color) {
        return {
            radialGradient: { cx: 0.5, cy: 0.3, r: 0.7 },
            stops: [
                [0, color],
                [1, Highcharts.Color(color).brighten(-0.3).get('rgb')] // darken
            ]
        };
    });

    // Build the chart
    $('#order-summary-monthly-container').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false
        },
        title: {
            text: 'Monthly Order Summary , 2014'
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    },
                    connectorColor: 'silver'
                }
            }
        },
        series: [{
            type: 'pie',
            name: 'Order',
            data: [
                ['January', 10.0],
                ['February',2.0],
                {
                    name: 'March',
                    y: 20.5,
                    sliced: true,
                    selected: true
                },
                ['April',    8.5],
                ['May',     6.2],
                ['June',   10.7],
['July',   9.5],
['August',   8.5],
['September',   2.5],
['October',   8.5],
['November',   9.5],
['December',   6.5]
            ]
        }]
    });
});


		</script>
                 <div id="order-summary-monthly-container" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>
                 
                  </div>
                        </div>
                    
                     <div class="col-md-6"> 
                  <div class="row">
                      
                      <script type="text/javascript">
$(function () {



    // Build the chart
    $('#in-come-summary-monthly-container').highcharts({
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false
        },
        title: {
            text: 'Monthly Income Summary , 2014'
        },
        tooltip: {
            pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: true,
                    format: '<b>{point.name}</b>: {point.percentage:.1f} %',
                    style: {
                        color: (Highcharts.theme && Highcharts.theme.contrastTextColor) || 'black'
                    },
                    connectorColor: 'silver'
                }
            }
        },
        series: [{
            type: 'pie',
            name: 'Order',
            data: [
                ['January', 10.0],
                ['February',2.0],
                ['March',    8.5],
                ['April',     6.2],
                {
                    name: 'May',
                    y: 20.5,
                    sliced: true,
                    selected: true
                },
                
                ['June',   10.7],
['July',   9.5],
['August',   8.5],
['September',   2.5],
['October',   8.5],
['November',   9.5],
['December',   6.5]
            ]
        }]
    });
});


		</script>
                    
                   <div id="in-come-summary-monthly-container" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>
                 
                  </div>
                        </div>
                    
                    
                    
                </div>
              </div>
            </div>
          </div>
    
    
    
    
    
        </div>

<!-- BEGIN PAGE LEVEL SCRIPTS -->
   
    <script src='<?php print($this->baseUrl());?>/assets/skin/plugins/fullcalendar/moment.min.js'></script>
    <script src='<?php print($this->baseUrl());?>/assets/skin/plugins/fullcalendar/fullcalendar.min.js'></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/simple-weather/jquery.simpleWeather.min.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/google-maps/markerclusterer.js"></script>
    <script src="http://maps.google.com/maps/api/js?sensor=true"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/google-maps/gmaps.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/charts-flot/jquery.flot.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/charts-flot/jquery.flot.animator.min.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/charts-flot/jquery.flot.resize.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/charts-flot/jquery.flot.time.min.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/charts-morris/raphael.min.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/charts-morris/morris.min.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/js/calendar.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/js/dashboard.js"></script>
    <!-- END  PAGE LEVEL SCRIPTS -->