<div id="main-content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    
                      <h3 class="panel-title"><strong><?php echo $this->translate("Attendance-Summary");?> <?php print($this->reportMonth);?>/<?php print($this->reportYear);?></strong></h3>
                    
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
                </div>
                
          
                <div class="panel-body">
                    <div class="row">
                        
                        
                        
                        <div class="col-md-12 col-sm-12 col-xs-12 table-responsive">
                            
                            
                            <table class="table table-bordered table_obtor_data table-hover">
                  
                                <thead class="no-bd">
                                    <tr>
                                        <th class="table_id table_head"><?php echo $this->translate("Data-Row-Date-On");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Data-Row-Day");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Data-Row-In-Time");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Data-Row-Out-Time");?></th>
                                        <th class="table_head table_data_xx"><?php echo $this->translate("Data-Row-Other-In-Out");?></th>
                                        <th class="table_head table_data_xxxx"><?php echo $this->translate("Data-Row-Is-Late");?></th>
                                        <th class="table_head table_data_xxxx"><?php echo $this->translate("Data-Row-Early-Off");?></th>
                                        <th class="table_head table_data_xx"><?php echo $this->translate("Data-Row-On-Leave");?></th>
                                        <th class="table_head table_data_xx"><?php echo $this->translate("Data-Row-Office-Holiday");?></th>
                                        <th class="table_head table_data_xx"><?php echo $this->translate("Data-Row-Expected-Work-Hours");?></th>
                                        <th class="table_head table_data_xx"><?php echo $this->translate("Data-Row-Actual-Work-Hours");?></th>
                                        <th class="table_head table_data_xx"><?php echo $this->translate("Data-Row-Attendance-Status");?></th>
                                        <th class="table_head table_data_xx"><?php echo $this->translate("Data-Row-Attendance-Counted-Working-Day");?></th>
                                        <th class="table_head table_data_xx"><?php echo $this->translate("Data-Row-Attendance-Counted-Extra-Working-Hrs");?></th>
                                        <th class="table_head table_data_xx"><?php echo $this->translate("Data-Row-Attendance-Approved-Extra-Working-Hrs");?></th>
                                    </tr>
                                </thead>
                                <tbody class="no-bd-y">

                               
                                   <?php foreach($this->reportData As $rIndex=>$reportDataRow){?>
                                            <tr>
                                                <td>
                                                    <a title="#" href="#">
                                                    <?php print($reportDataRow->getDateOn());?>
                                                    </a>
                                                </td>
                                                <td>
                                                 <?php print($this->translate($reportDataRow->getWeekDay()));?>
                                                </td>
                                                <td><?php print($reportDataRow->getInTime());?></td>
                                                <td><?php print($reportDataRow->getOutTime());?></td>
                                                 <td><?php print($reportDataRow->getOtherInOut());?></td>
                                                <td><?php print($reportDataRow->getIsLate());?></td>
                                                <td><?php print($reportDataRow->getEarlyOff());?></td>
                                                <td><?php print($reportDataRow->getOnLeave());?></td>
                                               <td><?php print($reportDataRow->getOfficeHoliday());?></td>
                                                <td><?php print($reportDataRow->getExpectedWorkDay());?></td>
                                                <td><?php print($reportDataRow->getCountedWorkingDay());?></td>
                                                <td><?php 
                                                    $attendanceRowStatus = $reportDataRow->getAttendanceStatus();
                                                    $In_Time_Exempted = $attendanceRowStatus['In-Time-Exempted'];
                                                    $Out_Time_Exempted = $attendanceRowStatus['Out-Time-Exempted'];
                                                    $In_Time_Excused = $attendanceRowStatus['In-Time-Excused'];
                                                    $Out_Time_Excused = $attendanceRowStatus['Out-Time-Excused'];
                                                    ?>
                                                    <?php if($In_Time_Exempted == 'Yes'){?>
                                                    <span class="badge badge-success badge-header attendance_status_icons">IE</span>
                                                    <?php } ?>
                                                     <?php if($Out_Time_Exempted == 'Yes'){?>
                                                    <span class="badge badge-success badge-header attendance_status_icons">OE</span>
                                                     <?php } ?>
                                                    <?php if($In_Time_Excused == 'Yes'){?>
                                                    <span class="badge badge-success badge-header attendance_status_icons">IEX</span>
                                                    <?php } ?>
                                                    <?php if($Out_Time_Excused == 'Yes'){?>
                                                    <span class="badge badge-success badge-header attendance_status_icons">OEX</span>     
                                                    <?php } ?>
                                                </td>
                                                <td><?php print($reportDataRow->getCountedWorkingDay());?></td>
                                                <td><?php print($reportDataRow->getCountedExtraWorkingHrs());?></td>
                                                 <td><?php print($reportDataRow->getApprovedExtraWorkingHrs());?></td>
                                               
                                            </tr>
                                            
                                            <?php if($reportDataRow->getWeekDay() == 'Saturday'){?>
                                            <tr>
						<td colspan="15">&nbsp;</td>
					    </tr>
                                            <?php } ?>
                                            
                                   <?php } ?>
                                    

                                </tbody>
                            </table>

                        </div>
                    </div>
                    
                    
                 
                    
                </div>
            </div>
        </div>
        
        
        
        
    </div>
</div>
