<div id="main-content">

    <div class="row">
        <div class="col-md-12">


            <form id="form_asset" name="form_asset" role="form" method="post" class="form-horizontal" enctype="multipart/form-data">
                <div class="panel panel-default">
                    
                    <div class="panel-heading">
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
           
                </div>

                    <div class="panel-body">


                        <div class="row">
                            <div class="col-md-6">
                                
                                <div class="col-md-12 col-sm-12 col-xs-12 m-t-20 m-b-20">
                                    
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Asset-Type");?></strong></label>
                                        <div class="controls">
                                            
                                            <select class="form-control" id="txtAssetType" name="txtAssetType">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <option value="simple" <?php if($this->assetInformation->getAssetType() == 'simple'){?> selected="selected" <?php } ?>><?php echo $this->translate("simple"); ?></option>
                                                     <option value="bundle" <?php if($this->assetInformation->getAssetType() == 'bundle'){?> selected="selected" <?php } ?>><?php echo $this->translate("bundle"); ?></option>
                                                </select>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Serial-Number");?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtSerialNumber" name="txtSerialNumber" value="<?php print($this->assetInformation->getSerialNumber());?>">
                                        </div>
                                    </div>
                                    
                                     <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Category");?></strong></label>
                                        <div class="controls">
                                            
                                            <select class="form-control" id="txtCategory" name="txtCategory">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <?php foreach($this->categoryList As $cIndex=>$category){?>
                                                    <option value="<?php print($category->getId());?>" <?php if($this->assetInformation->getCategory() == $category->getId()){?> selected="selected" <?php }?>><?php print($category->getName());?></option>
                                                    <?php } ?>
                                                </select>
                                        </div>
                                    </div>
                                    
                                     <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Model");?></strong></label>
                                        <div class="controls">
                                            <span id="model">
                                            <select class="form-control" id="txtModel" name="txtModel">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                      <?php foreach($this->models As $mIndex=>$model){?>
                                                     <option value="<?php print($model->getId());?>" <?php if($this->assetInformation->getModel() == $model->getId()){?> selected="selected" <?php }?>><?php print($model->getName());?></option>
                                                    <?php } ?>
                                                </select>
                                                </span>
                                        </div>
                                    </div>
                                    
                                    
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Country");?></strong></label>
                                        <div class="controls">
                                                <select class="form-control" name="txtCountry" id="txtCountry">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <?php foreach($this->countries As $cIndex=>$country){?>
                                                     <?php foreach($this->countries As $cIndex=>$country){?>
                                                    <option value="<?php print($country->getId());?>" <?php if($this->assetInformation->getCountry() == $country->getId()){?> selected="selected" <?php } ?> ><?php print($country->getName());?></option>
                                                    <?php } ?>
                                                    <?php } ?>
                                                </select>
                                        </div>
                                    </div>
                                   
                                   <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Branch");?></strong>
                                        </label>
                                        <div class="controls">
                                            <span id="branch">
                                                <select class="form-control" name="txtBranchName" id="txtBranchName">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                      <?php foreach($this->branches As $cIndex=>$branch){?>
                                                     <option value="<?php print($branch->getId());?>" <?php if($this->assetInformation->getBranch() == $branch->getId()){?> selected="selected" <?php } ?>><?php print($branch->getName());?></option>
                                                    <?php } ?>
                                                </select>
                                                </span>
                                        </div>
                                    </div>
                                    
                                    
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Purchased-Date");?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtPurchasedDate" name="txtPurchasedDate" value="<?php print($this->assetInformation->getPurchasedDate());?>">
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Cost");?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtCost" name="txtCost" value="<?php print($this->assetInformation->getCost());?>">
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Warranty-Valid-Until");?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtWarrantyValidUntil" name="txtWarrantyValidUntil" value="<?php print($this->assetInformation->getWarrantyValiedUntil());?>">
                                        </div>
                                    </div>
                                    
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Previous-User");?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtPreviousUser" name="txtPreviousUser" value="<?php print($this->assetInformation->getPriviousUser());?>">
                                        </div>
                                    </div>
                                    
                                     
                                    
                                </div>
                                
                                
                                
                            </div>
                            <div class="col-md-6">
                                
                                
                               <div class="col-md-12 col-sm-12 col-xs-12 m-t-20 m-b-20">
                                    
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Tag-Number");?></strong></label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtTagNumber" name="txtTagNumber" value="<?php print($this->assetInformation->getTagNumber());?>">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Barcode");?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtBarcode" name="txtBarcode" value="<?php print($this->assetInformation->getBarcode());?>">
                                        </div>
                                    </div>
                                   
                                   
                                   <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Vendor");?></strong></label>
                                        <div class="controls">
                                            
                                            <select class="form-control" id="txtVendor" name="txtVendor">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <?php foreach($this->vendorList As $vIndex=>$vendor){?>
                                                    <option value="<?php print($vendor->getId());?>" <?php if($this->assetInformation->getVendor() == $vendor->getId()){?>  selected="selected" <?php } ?>><?php print($vendor->getName());?></option>
                                                    <?php } ?>
                                                </select>
                                        </div>
                                    </div>
                                   
                                   
                                   
                                   <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Date-Acquired");?></strong></label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtDateAcquired" name="txtDateAcquired" value="<?php print($this->assetInformation->getDateAcquired());?>">
                                        </div>
                                    </div>
                                   
                                   <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Date Disposed");?></strong></label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtDateDisposed" name="txtDateDisposed" value="<?php print($this->assetInformation->getDateDisposed());?>">
                                        </div>
                                    </div>
                                   
                                   
                                   <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Region");?></strong>
                                        </label>
                                        <div class="controls">
                                            <span id="region">
                                                <select class="form-control" name="txtRegion" id="txtRegion">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <?php foreach($this->regions As $cIndex=>$region){?>
                                                     <option value="<?php print($region->getId());?>" <?php if($this->assetInformation->getRegion() == $region->getId()){?> selected="selected" <?php } ?>><?php print($region->getName());?></option>
                                                    <?php } ?>
                                                </select>
                                                </span>
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Department");?></strong></label>
                                        <div class="controls">
                                           <span id="department">
                                                <select class="form-control" name="txtDepartmentName" id="txtDepartmentName">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <?php foreach($this->departments As $dIndex=>$department){?>
                                                     <option value="<?php print($department->getId());?>" <?php if($this->assetInformation->getDepartment() == $department->getId()){?> selected="selected" <?php } ?>><?php print($department->getName());?></option>
                                                    <?php } ?>
                                                </select>
                                                </span>
                                        </div>
                                    </div>
                                   
                                   <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Purchased-From");?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtPurchasedFrom" name="txtPurchasedFrom" value="<?php print($this->assetInformation->getPurchasedFrom());?>">
                                        </div>
                                    </div>
                                   
                                   
                                   <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Next-Maintenance-Date");?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtNextMaintenanceDate" name="txtNextMaintenanceDate" value="<?php print($this->assetInformation->getNextMaintenanceDate());?>">
                                        </div>
                                    </div>
                                   
                                   
                                   <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Status");?></strong></label>
                                        <div class="controls">
                                            <input type="hidden" name="txtOldStatus" value="<?php print($this->assetInformation->getStatus());?>" />
                                            <select class="form-control" id="txtStatus" name="txtStatus">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <option value="assets-in-use" <?php if($this->assetInformation->getStatus() == 'assets-in-use'){?> selected="selected" <?php } ?>><?php echo $this->translate("assets-in-use"); ?></option>
                                                    <option value="assets-ready-to-use" <?php if($this->assetInformation->getStatus() == 'assets-ready-to-use'){?> selected="selected" <?php } ?>><?php echo $this->translate("assets-ready-to-use"); ?></option>
                                                    <option value="assets-waiting-for-service" <?php if($this->assetInformation->getStatus() == 'assets-waiting-for-service'){?> selected="selected" <?php } ?>><?php echo $this->translate("assets-waiting-for-service"); ?></option>
                                                    <option value="assets-sent-out-for-service" <?php if($this->assetInformation->getStatus() == 'assets-sent-out-for-service'){?> selected="selected" <?php } ?>><?php echo $this->translate("assets-sent-out-for-service"); ?></option>
                                                    <option value="assets-out-of-use" <?php if($this->assetInformation->getStatus() == 'assets-out-of-use'){?> selected="selected" <?php } ?>><?php echo $this->translate("assets-out-of-use"); ?></option>
                                                    <option value="assets-sold" <?php if($this->assetInformation->getStatus() == 'assets-sold'){?> selected="selected" <?php } ?>><?php echo $this->translate("assets-sold"); ?></option>
                                                </select>
                                        </div>
                                    </div>
                                   
                                   
                                   
                                    
                                    
                                </div>
                            
                            
                            
                            </div>
                            
                            
                            
                            <div class="col-md-12">
                                
                                
                               <div class="col-md-12 col-sm-12 col-xs-12 m-t-20 m-b-20">
                                   
                                   
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Description");?></strong>
                                        </label>
                                        <div class="controls">
                                            <textarea class="form-control" id="txtDescription" name="txtDescription"><?php print($this->assetInformation->getDescription());?></textarea>
                                        </div>
                                    </div>
                                  
                                   
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Current-User");?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtCurrentUser" name="txtCurrentUser" value="<?php print($this->assetInformation->getCurrentUser());?>">
                                            <input class="form-control" type="hidden" id="txtOldCurrentUser" name="txtOldCurrentUser" value="<?php print($this->assetInformation->getCurrentUser());?>">
                                        </div>
                                    </div>
                                   
                                   <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Item-Picture");?></strong></label>
                                        <?php if($this->assetInformation->getItemPicture() != ""){?>
                                        <span class="tips">
                                            <a href="<?php print($this->baseUrl());?>/images/assets/item-pictures/<?php print($this->assetInformation->getItemPicture());?>" target="_blank">
                                            <?php echo $this->translate("Existing-Item-Picture");?>
                                            </a>
                                        </span>
                                        <?php } ?>
                                        <div class="controls">
                                            <input class="form-control normal_input" type="file" id="txtItemPicture" name="txtItemPicture">
                                            <input type="hidden" name="txtItemOldPicture" id="txtItemOldPicture" value="<?php print($this->assetInformation->getItemPicture());?>" />
                                        </div>
                                    </div>
                                   
                                   <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Attach-Invoice");?></strong></label>
                                        <?php if($this->assetInformation->getAttachedInvoice() != ""){?>
                                        <span class="tips">
                                            <a href="<?php print($this->baseUrl());?>/images/assets/invoices/<?php print($this->assetInformation->getAttachedInvoice());?>" target="_blank">
                                            <?php echo $this->translate("Existing-Attach-Invoice");?>
                                            </a>
                                        </span>
                                        <?php } ?>
                                        <div class="controls">
                                            <input class="form-control normal_input" type="file" id="txtAttachInvoice" name="txtAttachInvoice">
                                            <input type="hidden" name="txtOldAttachedInvoice" id="txtOldAttachedInvoice" value="<?php print($this->assetInformation->getAttachedInvoice());?>" />
                                        </div>
                                    </div>
                                   
                                   
                                   <div class="form-group text-left m-t-40">
                                                            <button class="btn btn-blue" type="submit" name="Submit" id="Submit"><?php echo $this->translate("Submit");?></button>
                                                            <button type="reset" class="btn btn-default"><?php echo $this->translate("Cancel");?></button>
                                                </div>
                                   
                               </div>
                                
                            </div>
                            
                            
                       
                        </div>
                        
                 
                    </div>
                </div>
            </form>


        </div>
    </div>




</div>
<script src="<?php print($this->baseUrl()); ?>/assets/validator/admin/asset.js"></script>