<div id="main-content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    
                     <div class="btn-group">
                        <a href="<?php print($this->baseUrl()); ?>/admin/asset/add/" id="table-edit_new" class="btn btn-danger">
                            <?php echo $this->translate("Add-New");?> <i class="fa fa-plus"></i>
                        </a>
                    </div>
                    
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 table-responsive m-t-20">
                            <table class="table table-bordered table_obtor_data table-hover">
                                <thead class="no-bd">
                                    <tr>
                                        <th class="table_id table_head"><?php echo $this->translate("ID");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Serial-Number");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Tag-Number");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Barcode");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Current-User");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Date-Acquired");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Status");?></th>
                                        <th class="text-center table_head data_table_action"><?php echo $this->translate("Actions");?></th>
                                    </tr>
                                </thead>
                                <tbody class="no-bd-y">

                                    <?php if ($this->assetInfo) { ?>
                                        <?php foreach ($this->assetInfo As $aIndex => $asset) { ?>
                                            <tr>
                                                <td>
                                                    <a title="<?php echo $this->translate("View");?>" href="<?php print($this->baseUrl()); ?>/admin/asset/view/id/<?php print($asset->getId()); ?>">
                                                    <?php print($aIndex+1); ?>
                                                    </a>
                                                </td>
                                                <td><?php print($asset->getSerialNumber()); ?></td>
                                                <td>
                                                    <?php print($asset->getTagNumber()); ?>
                                                </td>
                                                <td><?php print($asset->getBarcode()); ?></td>
                                                <td><?php print($asset->getCurrentUser()); ?></td>
                                                
                                                <td>
                                                  <?php print($this->dateString($asset->getDateAcquired())); ?>
                                                </td>
                                                <td>
                                                    <?php echo $this->translate($asset->getStatus()); ?>
                                                  
                                                </td>
                                                
                                                <td class="text-center">
                                                    <a title="<?php echo $this->translate("Edit");?>" href="<?php print($this->baseUrl()); ?>/admin/asset/edit/id/<?php print($asset->getId()); ?>"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_edit.png" /></a>
                                                    <a title="<?php echo $this->translate("Delete");?>" href="<?php print($this->baseUrl()); ?>/admin/asset/delete/id/<?php print($asset->getId()); ?>" class="form-data-delete"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_drop.png" /></a>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                     <?php } else {?>
                                            <tr>
                                                <td colspan="8" class="table_data_not_found"><?php echo $this->translate("Records-Not-Available");?></td>
                                            </tr>
                                    <?php } ?>

                                </tbody>
                            </table>

                        </div>
                    </div>
                    
                    
                    <?php if(count($this->assetInfo)>0){?>
			<?php echo $this->partial('common/_pagination.phtml', array('paginationData' => $this->paggination)); ?>
                    <?php } ?>
                    
                </div>
            </div>
        </div>
    </div>
</div>
