<div id="main-content">

    <div class="row">
        <div class="col-md-12">


            <form id="form_asset" name="form_asset" role="form" method="post" class="form-horizontal" enctype="multipart/form-data">
                <div class="panel panel-default">
                    
                    <div class="panel-heading">
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
           
                </div>

                    <div class="panel-body">


                        <div class="row">
                            <div class="col-md-6">
                                
                                <div class="col-md-12 col-sm-12 col-xs-12 m-t-20">
                                    
                                    <div class="view_information">
                                            <ul>
                                                <li>
                                                    <span><?php echo $this->translate("Asset-Type");?></span>
                                                   : <?php if($this->assetInformation->getAssetType() == 'simple'){?> <?php echo $this->translate("simple"); ?> <?php } else {?> <?php echo $this->translate("bundle"); ?> <?php } ?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Serial-Number");?></span>
                                                   : <?php print($this->assetInformation->getSerialNumber());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Category");?></span>
                                                   : <?php print($this->categoryInfo->getName());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Model");?></span>
                                                   : <?php print($this->modelInfo->getName());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Country");?></span>
                                                   : <?php print($this->countryInfo->getName());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Branch");?></span>
                                                   : <?php print($this->branchInfo->getName());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Purchased-Date");?></span>
                                                   : <?php print($this->dateString($this->assetInformation->getPurchasedDate()));?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Cost");?></span>
                                                   : <?php print($this->assetInformation->getCost());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Warranty-Valid-Until");?></span>
                                                   : <?php print($this->dateString($this->assetInformation->getWarrantyValiedUntil()));?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Previous-User");?></span>
                                                   : <?php if($this->assetInformation->getPriviousUser()){ print($this->assetInformation->getPriviousUser()); } else {?> N/A <?php } ?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                 <li>
                                                    <span><?php echo $this->translate("Current-User");?></span>
                                                   : <?php print($this->assetInformation->getCurrentUser());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Item-Picture");?></span>
                                                   : <?php if($this->assetInformation->getItemPicture() != ""){?>
                                        
                                            <a href="<?php print($this->baseUrl());?>/uploads/images/assets/item-pictures/<?php print($this->assetInformation->getItemPicture());?>" target="_blank">
                                            <?php echo $this->translate("View-Existing-Item-Picture");?>
                                            </a>
                            
                                        <?php } else {?>
                                        N/A
                                        <?php } ?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                
                                            </ul>
                                    </div>
                                    
                                    
                                    
                                    
                                  
                                    
                                </div>
                                
                                
                                
                            </div>
                            <div class="col-md-6">
                                
                                
                               <div class="col-md-12 col-sm-12 col-xs-12 m-t-20">
                                    
                                   <div class="view_information">
                                            <ul>
                                                <li>
                                                    <span><?php echo $this->translate("Tag-Number");?></span>
                                                   : <?php print($this->assetInformation->getTagNumber());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Barcode");?></span>
                                                   : <?php print($this->assetInformation->getBarcode());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Vendor");?></span>
                                                   : <?php print($this->venderInfo->getName());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Date-Acquired");?></span>
                                                   : <?php print($this->dateString($this->assetInformation->getDateAcquired()));?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Date Disposed");?></span>
                                                   : <?php if($this->assetInformation->getDateDisposed()){ print($this->dateString($this->assetInformation->getDateDisposed())); } else {?> N/A <?php } ?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Region");?></span>
                                                   : <?php print($this->regionInfo->getName());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Department");?></span>
                                                   : <?php print($this->departmentInfo->getName());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Purchased-From");?></span>
                                                   : <?php print($this->assetInformation->getPurchasedFrom());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                 <li>
                                                    <span><?php echo $this->translate("Next-Maintenance-Date");?></span>
                                                   : <?php print($this->dateString($this->assetInformation->getNextMaintenanceDate()));?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Status");?></span>
                                                   : <?php if($this->assetInformation->getStatus() == 1){?> <?php echo $this->translate("In-Use"); ?> <?php } elseif($this->assetInformation->getStatus() == 2){?> <?php echo $this->translate("Ready-Use"); ?> <?php } elseif($this->assetInformation->getStatus() == 3){?> <?php echo $this->translate("Waiting-For-Service"); ?> <?php } elseif($this->assetInformation->getStatus() == 4){?> <?php echo $this->translate("Sent-Out-For-Service"); ?> <?php } elseif($this->assetInformation->getStatus() == 5){?> <?php echo $this->translate("Out-Of-Use"); ?> <?php } elseif($this->assetInformation->getStatus() == 6){?> <?php echo $this->translate("Sold"); ?> <?php } ?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Attach-Invoice");?></span>
                                                   : <?php if($this->assetInformation->getAttachedInvoice() != ""){?>
                                        
                                            <a href="<?php print($this->baseUrl());?>/uploads/images/assets/invoices/<?php print($this->assetInformation->getAttachedInvoice());?>" target="_blank">
                                            <?php echo $this->translate("View-Existing-Attach-Invoice");?>
                                            </a>
                                    
                                        <?php } else {?>
                                        N/A
                                        <?php } ?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                
                                            </ul>
                                    </div>
                                    
                                    
                                    
                                    
                                </div>
                            
                            
                            
                            </div>
                            
                            
                            
                            <div class="col-md-12">
                                
                                
                               <div class="col-md-12 col-sm-12 col-xs-12 m-b-10">
                                   
                                   
                                   
                                   <div class="view_information">
                                            <ul>
                                                <li>
                                                    <span><?php echo $this->translate("Description");?></span>
                                                   : <?php print($this->assetInformation->getDescription());?>
                                                    <div class="clear"></div>
                                                </li>
                                    
                                              
                                                
                                            </ul>
                                    </div>
                                  
                                   
                               </div>
                                
                            </div>
                            
                            
                       
                        </div>
                        
                        
                        
                      <?php echo $this->partial('common/_system_log.phtml', array('logInformation' => $this->logInformation)); ?> 
                 
                    </div>
                    
                    
                    
                    
                    
                </div>
            </form>


        </div>
    </div>




</div>
<script src="<?php print($this->baseUrl()); ?>/assets/validator/admin/asset.js"></script>