<div id="main-content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    
                     <div class="btn-group">
                        <a href="<?php print($this->baseUrl()); ?>/admin/candidate/add/" id="table-edit_new" class="btn btn-danger">
                            <?php echo $this->translate("Add-New");?> <i class="fa fa-plus"></i>
                        </a>
                    </div>
                    
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 table-responsive m-t-20">
                            <table class="table table-bordered table_obtor_data table-hover">
                                <thead class="no-bd">
                                    <tr>
                                        <th class="table_id table_head"><?php echo $this->translate("ID");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Name_With_Ini");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Email_Address");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Telephone_Number");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Date_Of_Birth");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Gender");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Country");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("State");?></th>
                                        <th class="text-center table_head data_table_action"><?php echo $this->translate("Actions");?></th>
                                    </tr>
                                </thead>
                                <tbody class="no-bd-y">

                                    <?php if ($this->candidateInformation) { ?>
                                        <?php foreach ($this->candidateInformation As $vIndex => $candidate) { ?>
                                            <tr>
                                                <td>
                                                    <a title="<?php echo $this->translate("View");?>" href="<?php print($this->baseUrl()); ?>/admin/candidate/view/id/<?php print($candidate->getId()); ?>">
                                                    <?php print($candidate->getId()); ?>
                                                    </a>
                                                </td>
                                                <td><?php print($candidate->getNameWithIni()); ?></td>
                                                 <td><?php print($candidate->getEmailAddress()); ?></td>
                                            
                                                <td>
                                                    <div class="col-md-12 col-sm-12 col-xs-12" id="tooltips">
                                                        <a rel="tooltip" data-toggle="tooltip" data-placement="top" title="<?php print($candidate->getTelephoneNumber()); ?>/<?php print($candidate->getContactNumber()); ?>">
                                                          <?php print($candidate->getContactNumber()); ?>
                                                        </a>
                                                    </div> 
                                                </td>
                                              <td><?php print($candidate->getDateOfBirth()); ?></td>
                                              <td><?php print($candidate->getGender()); ?></td>
                                              <td><?php print($candidate->getResidentialAddressCountry()); ?></td>
                                              <td><?php print($candidate->getResidentialAddressState()); ?></td>
                                                
                                                
                                                <td class="text-center">
                                                    <a title="<?php echo $this->translate("Edit");?>" href="<?php print($this->baseUrl()); ?>/admin/candidate/edit/id/<?php print($candidate->getId()); ?>"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_edit.png" /></a>
                                                    <a title="<?php echo $this->translate("Delete");?>" href="<?php print($this->baseUrl()); ?>/admin/candidate/delete/id/<?php print($candidate->getId()); ?>" class="form-data-delete"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_drop.png" /></a>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                    <?php } else {?>
                                            <tr>
                                                <td colspan="9" class="table_data_not_found"><?php echo $this->translate("Records-Not-Available");?></td>
                                            </tr>
                                    <?php } ?>

                                </tbody>
                            </table>

                        </div>
                    </div>
                    
                    
                    <?php if(count($this->candidateInformation)>0){?>
			<?php echo $this->partial('common/_pagination.phtml', array('paginationData' => $this->paggination)); ?>
                    <?php } ?>
                    
                </div>
            </div>
        </div>
    </div>
</div>