   <div id="main-content">
            
            <div class="row">
                
                <form class="form-horizontal" id="form_working_time" name="form_working_time" role="form" method="post">
                    
                    
                    
                    
                    <?php foreach($this->weekDays As $lIndex=>$weekDay){?>
                <div class="col-md-6">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            
                            <h5 class="panel-title"><strong><?php echo $this->translate($weekDay); ?><input parsley-minlength="3" class="form-control" type="hidden" name="txtWeekDays[]" value="<?php print($weekDay);?>"/></strong></h5>
                            <div class="row border-top">
                                 <div class="col-md-12 col-sm-12 col-xs-12 m-t-20 m-b-20">
                                        
                                       <div class="form-group">
                                        <label class="col-sm-3 control-label"><strong><?php echo $this->translate("On-Time");?></strong></label>
                                        <div class="col-sm-9">
                                            <input parsley-minlength="3" class="form-control" type="text" name="txtOnTime[]"/>
                                        </div>
                                        </div>
                                     
                                     <div class="form-group">
                                        <label class="col-sm-3 control-label"><strong><?php echo $this->translate("Off-Time");?></strong></label>
                                        <div class="col-sm-9">
                                            <input parsley-minlength="3" class="form-control" type="text" name="txtOffTime[]"/>
                                        </div>
                                        </div>
                                     
                                      <div class="form-group">
                                        <label class="col-sm-3 control-label"><strong><?php echo $this->translate("Is-Working");?></strong></label>
                                        <div class="col-sm-9">
                                           <select parsley-minlength="3" class="form-control normal_input" name="cmbIsWorking[]">
                                                   <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                     <option value="Yes"><?php echo $this->translate("Yes"); ?></option>
                                                     <option value="No"><?php echo $this->translate("No"); ?></option>
                                                </select>
                                        </div>
                                        </div>
                                     
                                     <div class="form-group">
                                        <label class="col-sm-3 control-label"><strong><?php echo $this->translate("Expected-Working-Hours");?></strong></label>
                                        <div class="col-sm-9">
                                           <select parsley-minlength="3" class="form-control normal_input" name="cmbWorkingHours[]">
                                                   <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                     <option value="0">0</option>
                                                     <option value="0.25">0.25</option>
                                                     <option value="0.50">0.50</option>
                                                     <option value="0.75">0.75</option>
                                                     <option value="1.00">1.00</option>
                                                </select>
                                        </div>
                                        </div>
                                     
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                    <?php } ?>
                    
                    <div class="col-md-12">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            
                            <h5 class="panel-title"><strong><?php echo $this->translate('Other-Settings'); ?></strong></h5>
                            <div class="row border-top">
                                 <div class="col-md-12 col-sm-12 col-xs-12 m-t-20 m-b-20">
                                        
                                       <div class="form-group">
                                        <label class="col-sm-3 control-label"><strong><?php echo $this->translate("Effective-From");?></strong></label>
                                        <div class="col-sm-9">
                                            <input parsley-minlength="3" class="form-control normal_input pickadate" type="text" name="txtEffectiveFrom" id="txtEffectiveFrom"/>
                                        </div>
                                        </div>
                                     
                                     <div class="form-group">
                                        <label class="col-sm-3 control-label"><strong><?php echo $this->translate("Is-Active-Currently");?></strong></label>
                                        <div class="col-sm-9">
                                           <select parsley-minlength="3" class="form-control normal_input" name="cmbIsActiveCurrently" id="cmbIsActiveCurrently">
                                                   <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                     <option value="Yes"><?php echo $this->translate("Yes"); ?></option>
                                                     <option value="No"><?php echo $this->translate("No"); ?></option>
                                                </select>
                                        </div>
                                        </div>
                                     
                                 <div class="form-group">
                                  
                                                            <button class="btn btn-blue" type="submit" name="Submit" id="Submit"><?php echo $this->translate("Submit");?></button>
                                                            <button type="reset" class="btn btn-default"><?php echo $this->translate("Cancel");?></button>
                                      
                                     </div>
                                     
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                    
                    
                    </form>
                
                
            </div>
            
                        
            
                        
        </div>

<script src="<?php print($this->baseUrl());?>/assets/validator/admin/form_working_time.js"></script>