   <div id="main-content">
            
            <div class="row">
                <div class="col-md-12">
            
                    
                    
                    <div class="panel panel-default">
                        
                         <div class="panel-heading">
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
           
                </div>
                   
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <form id="form_skills" name="form_skills" role="form" method="post" class="form-horizontal">
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Title");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <p><?php print($this->skillsInfo->getTitle());?></p>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Years-Of-Experience");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <p><?php print($this->skillsInfo->getYearsOfExperience());?></p>
                                            </div>
                                        </div>
                                        
                                         
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Comments");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <p><?php print($this->skillsInfo->getComments());?></p>
                                            </div>
                                        </div>
                                        
                                   
                                 
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    
                    
                </div>
            </div>
            
                        
            
                        
        </div>