<div id="main-content">

    <div class="row">
        <div class="col-md-12">


            <form id="form_asset" name="form_asset" role="form" method="post" class="form-horizontal" enctype="multipart/form-data">
                <div class="panel panel-default">
                    
                    <div class="panel-heading">
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
           
                </div>

                    <div class="panel-body">


                        <div class="row">
                            <div class="col-md-6">
                                
                                <div class="col-md-12 col-sm-12 col-xs-12 m-t-20">
                                    
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Asset-Type");?></strong></label>
                                        <span class="tips data_value"><?php if($this->assetInformation->getAssetType() == 'simple'){?> <?php echo $this->translate("simple"); ?> <?php } else {?> <?php echo $this->translate("bundle"); ?> <?php } ?></span>
                                    </div>
                                    
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Serial-Number");?></strong></label>
                                        <span class="tips data_value"><?php print($this->assetInformation->getSerialNumber());?></span>
                                    </div>
                                    
                                     <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Category");?></strong></label>
                                        <span class="tips data_value"><?php print($this->categoryInfo->getName());?></span>
                                    </div>
                                    
                                     <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Model");?></strong></label>
                                        <span class="tips data_value"><?php print($this->modelInfo->getName());?></span>
                                    </div>
                                    
                                    
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Country");?></strong></label>
                                        <span class="tips data_value"><?php print($this->countryInfo->getName());?></span>
                                    </div>
                                   
                                   <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Branch");?></strong></label>
                                        <span class="tips data_value"><?php print($this->branchInfo->getName());?></span>
                                    </div>
                                    
                                    
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Purchased-Date");?></strong></label>
                                        <span class="tips data_value"><?php print($this->dateString($this->assetInformation->getPurchasedDate()));?></span>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Cost");?></strong></label>
                                        <span class="tips data_value"><?php print($this->assetInformation->getCost());?></span>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Warranty-Valid-Until");?></strong></label>
                                        <span class="tips data_value"><?php print($this->dateString($this->assetInformation->getWarrantyValiedUntil()));?></span>
                                    </div>
                                    
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Previous-User");?></strong></label>
                                        <span class="tips data_value"><?php if($this->assetInformation->getPriviousUser()){ print($this->assetInformation->getPriviousUser()); } else {?> N/A <?php } ?></span>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Current-User");?></strong></label>
                                        <span class="tips data_value"><?php print($this->assetInformation->getCurrentUser());?></span>
                                    </div>
                                    
                                     <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Item-Picture");?></strong></label>
                                        <?php if($this->assetInformation->getItemPicture() != ""){?>
                                        <span class="tips">
                                            <a href="<?php print($this->baseUrl());?>/images/assets/item-pictures/<?php print($this->assetInformation->getItemPicture());?>" target="_blank">
                                            <?php echo $this->translate("View-Existing-Item-Picture");?>
                                            </a>
                                        </span>
                                        <?php } else {?>
                                        <span class="tips">N/A</span>
                                        <?php } ?>
                                    </div>
                                    
                                </div>
                                
                                
                                
                            </div>
                            <div class="col-md-6">
                                
                                
                               <div class="col-md-12 col-sm-12 col-xs-12 m-t-20">
                                    
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Tag-Number");?></strong></label>
                                        <span class="tips data_value"><?php print($this->assetInformation->getTagNumber());?></span>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Barcode");?></strong></label>
                                        <span class="tips data_value"><?php print($this->assetInformation->getBarcode());?></span>
                                    </div>
                                   
                                   
                                   <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Vendor");?></strong></label>
                                        <span class="tips data_value"><?php print($this->venderInfo->getName());?></span>
                                    </div>
                                   
                                   
                                   
                                   <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Date-Acquired");?></strong></label>
                                        <span class="tips data_value"><?php print($this->dateString($this->assetInformation->getDateAcquired()));?></span>
                                    </div>
                                   
                                   <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Date Disposed");?></strong></label>
                                        <span class="tips data_value"><?php if($this->assetInformation->getDateDisposed()){ print($this->dateString($this->assetInformation->getDateDisposed())); } else {?> N/A <?php } ?></span>
                                    </div>
                                   
                                   
                                   <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Region");?></strong></label>
                                        <span class="tips data_value"><?php print($this->regionInfo->getName());?></span>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Department");?></strong></label>
                                        <span class="tips data_value"><?php print($this->departmentInfo->getName());?></span>
                                    </div>
                                   
                                   <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Purchased-From");?></strong></label>
                                        <span class="tips data_value"><?php print($this->assetInformation->getPurchasedFrom());?></span>
                                    </div>
                                   
                                   
                                   <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Next-Maintenance-Date");?></strong></label>
                                        <span class="tips data_value"><?php print($this->dateString($this->assetInformation->getNextMaintenanceDate()));?></span>
                                    </div>
                                   
                                   
                                   <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Status");?></strong></label>
                                        <span class="tips data_value"> <?php if($this->assetInformation->getStatus() == 1){?> <?php echo $this->translate("In-Use"); ?> <?php } elseif($this->assetInformation->getStatus() == 2){?> <?php echo $this->translate("Ready-Use"); ?> <?php } elseif($this->assetInformation->getStatus() == 3){?> <?php echo $this->translate("Waiting-For-Service"); ?> <?php } elseif($this->assetInformation->getStatus() == 4){?> <?php echo $this->translate("Sent-Out-For-Service"); ?> <?php } elseif($this->assetInformation->getStatus() == 5){?> <?php echo $this->translate("Out-Of-Use"); ?> <?php } elseif($this->assetInformation->getStatus() == 6){?> <?php echo $this->translate("Sold"); ?> <?php } ?></span>
                                    </div>
                                   
                                   
                                   <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Attach-Invoice");?></strong></label>
                                        <?php if($this->assetInformation->getAttachedInvoice() != ""){?>
                                        <span class="tips">
                                            <a href="<?php print($this->baseUrl());?>/images/assets/invoices/<?php print($this->assetInformation->getAttachedInvoice());?>" target="_blank">
                                            <?php echo $this->translate("View-Existing-Attach-Invoice");?>
                                            </a>
                                        </span>
                                        <?php } else {?>
                                        <span class="tips">N/A</span>
                                        <?php } ?>
                                        
                                    </div>
                                    
                                    
                                </div>
                            
                            
                            
                            </div>
                            
                            
                            
                            <div class="col-md-12">
                                
                                
                               <div class="col-md-12 col-sm-12 col-xs-12 m-b-10">
                                   
                                   
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Description");?></strong>
                                        </label>
                                        <div class="controls">
                                            <span class="tips data_value"><?php print($this->assetInformation->getDescription());?></span>
                                        </div>
                                    </div>
                                  
                                   
                               </div>
                                
                            </div>
                            
                            
                       
                        </div>
                        
                        
                        
                      <?php echo $this->partial('common/_system_log.phtml', array('logInformation' => $this->logInformation)); ?> 
                 
                    </div>
                    
                    
                    
                    
                    
                </div>
            </form>


        </div>
    </div>




</div>
<script src="<?php print($this->baseUrl()); ?>/assets/validator/admin/asset.js"></script>