   <div id="main-content">
            
            <div class="row">
                <div class="col-md-12">
            
                    
                    
                    <div class="panel panel-default">
                   
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-5">
                                    <form id="form_toDoList" name="form_toDoList" role="form" method="post" class="form-horizontal">
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Title");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <input parsley-minlength="3" class="form-control" type="text" name="txtTitle" id="txtTitle" value="<?php print($this->toDoListInfo->getListTitle());?>"/>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Description");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <textarea parsley-minlength="3" class="form-control" type="text" name="txtDescription" id="txtDescription"><?php print($this->toDoListInfo->getListDescription());?></textarea>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Reminder-On");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <select name="cmbReminderOn" id="cmbReminderOn" class="form-control normal_input">
                                                    <option value=""></option>
                                                    <option value="Yes" <?php if($this->toDoListInfo->getReminderOn() == 'Yes'){?> selected="selected" <?php } ?>><?php echo $this->translate("Yes");?></option>
                                                    <option value="No" <?php if($this->toDoListInfo->getReminderOn() == 'No'){?> selected="selected" <?php } ?>><?php echo $this->translate("No");?></option>
                                                </select>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Reminder-Date-On");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <input parsley-minlength="3" class="form-control normal_input pickadate" type="text" name="txtReminderDateOn" id="txtReminderDateOn" value="<?php print($this->toDoListInfo->getReminderDate());?>"/>
                                            </div>
                                        </div>
                                        
                                   
                                        <div class="form-group text-left">
                                            <button class="btn btn-blue" type="submit" name="Submit" id="Submit"><?php echo $this->translate("Submit");?></button>
                                            <button type="reset" class="btn btn-default"><?php echo $this->translate("Cancel");?></button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    
                    
                </div>
            </div>
            
                        
            
                        
        </div>
<script src="<?php print($this->baseUrl());?>/assets/validator/staff/toDoList.js"></script>