<div id="main-content">

    <div class="row">
        <div class="col-md-12">


            <form id="form_asset" name="form_asset" role="form" method="post" class="form-horizontal" enctype="multipart/form-data">
                <div class="panel panel-default">
                    
                    <div class="panel-heading">
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
           
                </div>

                    <div class="panel-body">
                    <h5 class="panel-title"><strong><?php echo $this->translate("Basic-Information"); ?></strong></h5>
                    <div class="row border-top">
                            <div class="col-md-12">
                                <div class="col-md-12 col-sm-12 col-xs-12 m-t-20">
                                    <div class="view_information">
                                            <ul>
                                                <li>
                                                    <span><?php echo $this->translate("Employee"); ?></span>
                                                   : <?php if($this->getEmployee($this->leaveInformation->getEmployee())){?><?php print($this->getEmployee($this->leaveInformation->getEmployee())->getNameWithInitials());?> <?php } ?>
                                                    <div class="clear"></div>
                                                </li>

                                                <li>
                                                    <span><?php echo $this->translate("No-Of-Days-Leave"); ?></span>
                                                    : <?php print($this->leaveInformation->getNoOfDaysLeave());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Reason"); ?></span>
                                                    : <?php print($this->leaveInformation->getReason());?>
                                                    <div class="clear"></div>
                                                </li>
                                            </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                    <?php foreach($this->leaveInformation->getLeaveDays() As $lIndex=>$leaveDayInfo) { ?>
                        <h5 class="panel-title"><strong><?php echo $this->translate("Leave-Day"); ?> - <?php print($lIndex+1); ?></strong></h5>
                        
                        <div class="row border-top">
                            <div class="col-md-12">
                                <div class="col-md-12 col-sm-12 col-xs-12 m-t-20">
                                    <div class="view_information">
                                            <ul>
                                                <li>
                                                    <span><?php echo $this->translate("Date-On"); ?></span>
                                                   : <?php print($leaveDayInfo->getLeaveDate());?>
                                                    <div class="clear"></div>
                                                </li>

                                                <li>
                                                    <span><?php echo $this->translate("LeaveType"); ?></span>
                                                   : <?php echo $this->translate($leaveDayInfo->getLeaveType()); ?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("LeaveTime"); ?></span>
                                                    : <?php echo $this->translate("From"); ?> : <?php print($leaveDayInfo->getLeaveTimeFrom());?>  <?php echo $this->translate("To"); ?> : <?php print($leaveDayInfo->getLeaveTimeTo());?>
                                                    <div class="clear"></div>
                                                </li>
                                            </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                        
                         <?php } ?>
                        
                         <h5 class="panel-title"><strong><?php echo $this->translate("Acting-Staff-Information"); ?></strong></h5>
                         
                         
                        <div class="row border-top">
                            <div class="col-md-12">
                                <div class="col-md-12 col-sm-12 col-xs-12 m-t-20">
                                    <div class="view_information">
                                            <ul>
                                                <li>
                                                    <span><?php echo $this->translate("Acting-Staff-Id"); ?></span>
                                                     : <?php if($this->getEmployee($this->leaveInformation->getActingStaffId())){?> <?php print($this->getEmployee($this->leaveInformation->getActingStaffId())->getNameWithInitials());?> <?php } ?>
                                                    <div class="clear"></div>
                                                </li>

                                                <li>
                                                    <span><?php echo $this->translate("Work-Area-To-Be-Covered"); ?></span>
                                                   : <?php print($this->leaveInformation->getWorkAreaToBeCovered());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Status-Of-Acceptance"); ?>/<?php echo $this->translate("Rejected"); ?></span>
                                                   : <?php print($this->leaveInformation->getActingStaffSignature());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Acting-Staff-Remarks");?></span>
                                                   : <?php print($this->leaveInformation->getActingStaffRemarks());?>
                                                    <div class="clear"></div>
                                                </li>
                                               
                                            </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                         
                         
                          <h5 class="panel-title"><strong><?php echo $this->translate("Supervisor-Signature-Information"); ?></strong></h5>
                            <div class="row border-top">
                            <div class="col-md-12">
                                <div class="col-md-12 col-sm-12 col-xs-12 m-t-20">
                                    <div class="view_information">
                                            <ul>
                                                <li>
                                                    <span><?php echo $this->translate("Supervisor-EmployeeId");?></span>
                                                   : <?php if($this->getEmployee($this->leaveInformation->getSupervisorEmployeeId())){?> <?php print($this->getEmployee($this->leaveInformation->getSupervisorEmployeeId())->getNameWithInitials());?> <?php } ?>
                                                    <div class="clear"></div>
                                                </li>

                                                <li>
                                                    <span><?php echo $this->translate("Status-Of-Recommendation");?></span>
                                                   : <?php 
                                                   if($this->leaveInformation->getSupervisorSignature() != ''){
                                                   echo $this->translate($this->leaveInformation->getSupervisorSignature());
                                                   }
                                                   ?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Supervisor-Remarks");?></span>
                                                   : <?php print($this->leaveInformation->getSupervisorRemarks());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                
                                               
                                            </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                          
                          
                          <h5 class="panel-title"><strong><?php echo $this->translate("Manager-Signature-Information"); ?></strong></h5>
                            <div class="row border-top">
                            <div class="col-md-12">
                                <div class="col-md-12 col-sm-12 col-xs-12 m-t-20">
                                    <div class="view_information">
                                            <ul>
                                                <li>
                                                    <span><?php echo $this->translate("Manager-Employee-Id");?></span>
                                                   : <?php if($this->getEmployee($this->leaveInformation->getManagerEmployeeId())){?> <?php print($this->getEmployee($this->leaveInformation->getManagerEmployeeId())->getNameWithInitials());?> <?php } ?>
                                                    <div class="clear"></div>
                                                </li>

                                                <li>
                                                    <span><?php echo $this->translate("Final-Status");?></span>
                                                   : <?php 
                                                   if($this->leaveInformation->getManagerSignature() != ''){
                                                    echo $this->translate($this->leaveInformation->getManagerSignature()); 
                                                   }
                                                   ?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Manager-Remarks");?></span>
                                                   : <?php print($this->leaveInformation->getManagerRemarks());?>
                                                    <div class="clear"></div>
                                                </li>
                                               
                                            </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                          
                          
                          <h5 class="panel-title"><strong><?php echo $this->translate("Other-Details"); ?></strong></h5>
                            <div class="row border-top">
                            <div class="col-md-12">
                                <div class="col-md-12 col-sm-12 col-xs-12 m-t-20">
                                    <div class="view_information">
                                            <ul>
                                                <li>
                                                    <span><?php echo $this->translate("App-Status");?></span>
                                                   : <?php echo $this->translate($this->leaveInformation->getAppStatus()); ?>
                                                    <div class="clear"></div>
                                                </li>

                                                <li>
                                                    <span><?php echo $this->translate("Is-Approved-By-Admin");?></span>
                                                   : <?php 
                                                   if($this->leaveInformation->getIsApprovedByAdmin() != ''){
                                                   echo $this->translate($this->leaveInformation->getIsApprovedByAdmin());
                                                   }
                                                   ?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Admin-Remarks");?></span>
                                                   : <?php print($this->leaveInformation->getAdminRemarks());?>
                                                    <div class="clear"></div>
                                                </li>
                                               
                                            </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                          
                          
    
                    </div>
                    
                    
                    
                    
                    
                </div>
            </form>


        </div>
    </div>




</div>
<script src="<?php print($this->baseUrl()); ?>/assets/validator/admin/asset.js"></script>