<select class="form-control" name="model" id="model">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <?php foreach($this->models As $mIndex=>$model){?>
                                                     <option value="<?php print($model->getId());?>"><?php print($model->getName());?></option>
                                                    <?php } ?>
                                                </select>