<select class="form-control" name="region" id="region">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <?php foreach($this->regions As $cIndex=>$region){?>
                                                     <option value="<?php print($region->getId());?>"><?php print($region->getName());?></option>
                                                    <?php } ?>
                                                </select>