<div id="main-content">

    <div class="row">
        <div class="col-md-12">



            <div class="panel panel-default">

                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-5">
                            <form id="form_salary_extra_bonus" name="form_salary_extra_bonus" role="form" method="post" class="form-horizontal" action="<?php print($this->baseUrl());?>/admin/payroll/extra-bonus/">
                                
                                <div class="form-group">
                                    <label class="form-label"><strong><?php echo $this->translate("Employee"); ?></strong></label>
                                    <div class="input-icon right">
                                        <i class="fa"></i>
                                       <select parsley-minlength="3" class="form-control" name="employee" id="employee">
                                        <option value="">-- select employee --</option>
                                        <?php foreach ($this->employeeInfo As $empIndex => $employee) { ?>
                                            <option value="<?php print($employee->getId()); ?>"><?php print($employee->getNameWithInitials()); ?></option>
                                        <?php } ?>
                                    </select>
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Salary-Month");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                 <select parsley-minlength="3" class="form-control mid_with_form_control_x" name="month" id="month">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <option value="January"><?php echo $this->translate("January"); ?></option>
                                                    <option value="February"><?php echo $this->translate("February"); ?></option>
                                                    <option value="March"><?php echo $this->translate("March"); ?></option>
                                                    <option value="April"><?php echo $this->translate("April"); ?></option>
                                                    <option value="May"><?php echo $this->translate("May"); ?></option>
                                                    <option value="June"><?php echo $this->translate("June"); ?></option>
                                                    <option value="July"><?php echo $this->translate("July"); ?></option>
                                                    <option value="August"><?php echo $this->translate("August"); ?></option>
                                                    <option value="September"><?php echo $this->translate("September"); ?></option>
                                                    <option value="October"><?php echo $this->translate("October"); ?></option>
                                                    <option value="November"><?php echo $this->translate("November"); ?></option>
                                                     <option value="December"><?php echo $this->translate("December"); ?></option>
                                                </select>
                                                
                                                <select parsley-minlength="3" class="form-control mid_with_form_control_x" name="year" id="year">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <?php for($year=2013;$year<=date('Y');$year++){?>
                                                    <option value="<?php print($year);?>"><?php print($year);?></option>
                                                    <?php } ?>
                                                </select>
                                                
                                            </div>
                                        </div>
                               
                                
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Bonus-Amount");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <input type="text" class="form-control" name="txtExtraBonus" id="txtExtraBonus" />
                                            </div>
                                        </div>
                                
                                
                                <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Remarks");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <textarea class="form-control" name="txtRemarks" id="txtRemarks"></textarea>
                                            </div>
                                        </div>
                              
                                

                        
                                <div class="form-group text-left">
                                    <button class="btn btn-blue" type="submit" name="Submit" id="Submit"><?php echo $this->translate("Search"); ?></button>
                                    <button type="reset" class="btn btn-default"><?php echo $this->translate("Cancel"); ?></button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>



        </div>
    </div>




</div>