   <div id="main-content">
            
            <div class="row">
                <div class="col-md-12">
            
                    
                    
                    <div class="panel panel-default">
                        
                         <div class="panel-heading">
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
           
                </div>
                   
                        <div class="panel-body">
                            <div class="row">
                            <div class="col-md-12">
                                <div class="col-md-12 col-sm-12 col-xs-12 m-t-20">
                                    <div class="view_information">
                                            <ul>
                                                <li>
                                                    <span><?php echo $this->translate("Salary-Type");?></span>
                                                   : <?php print($this->salaryPaymentBreakdownInfo->getSalaryType());?>
                                                    <div class="clear"></div>
                                                </li>
                                                <li>
                                                    <span><?php echo $this->translate("Remarks");?></span>
                                                   : <?php print($this->salaryPaymentBreakdownInfo->getRemarks());?>
                                                    <div class="clear"></div>
                                                </li>

                                                <li>
                                                    <span><?php echo $this->translate("Amount");?></span>
                                                    : <?php print($this->salaryPaymentBreakdownInfo->getAmount());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Amount-Type");?></span>
                                                    : <?php print($this->salaryPaymentBreakdownInfo->getAmountType());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Generated-On");?></span>
                                                    : <?php print($this->salaryPaymentBreakdownInfo->getGeneratedOn());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                 <li>
                                                    <span><?php echo $this->translate("Added-On");?></span>
                                                    : <?php print($this->salaryPaymentBreakdownInfo->getAddedOn());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Added-By");?></span>
                                                    :  <?php print($this->salaryPaymentBreakdownInfo->getAddedBy());?>
                                                    <div class="clear"></div>
                                                </li>
                                              
                                                
                                            </ul>
                                    </div>
                                </div>
                            </div>
                                
                                
                               
        
                                
                                
                        </div>
                        </div>
                    </div>

                    
                    
                </div>
            </div>
            
                        
            
                        
        </div>