 <div id="main-content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
           
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 m-t-20 table-responsive">
                            <table class="table table-bordered table_obtor_data table-hover">
                                <thead class="no-bd">
                                    <tr>
                                        <th class="table_id table_head"><?php echo $this->translate("ID");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Attachment-Title");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Attachment");?></th>   
                                    </tr>
                                </thead>
                                <tbody class="no-bd-y">

                                    <?php if ($this->attachments) { ?>
                                        <?php foreach ($this->attachments As $rIndex => $attachment) { ?>
                                            <tr>
                                                <td>
                                                    <a title="<?php echo $this->translate("View");?>" href="<?php print($this->baseUrl()); ?>/my-profile/attachments-view/?id=<?php print($attachment->getId()); ?>">
                                                    <?php print($rIndex+1); ?>
                                                    </a>
                                                </td>
                                                <td><?php print($this->translate($attachment->getAttachmentTitle())); ?></td>
                                                <td>
                                                    <a title="<?php echo $this->translate("View");?>" target="_blank" href="<?php print($this->baseUrl()); ?>/uploads/attachments/Employee/<?php print($attachment->getDocPath()); ?>">
                                                    <?php print($this->translate('Download-Attachment')); ?>
                                                    </a>
                                                </td>

                                            </tr>
                                        <?php } ?>
                                    <?php } else {?>
                                            <tr>
                                                <td colspan="3" class="table_data_not_found"><?php echo $this->translate("Records-Not-Available");?></td>
                                            </tr>
                                    <?php } ?>

                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>