 <div id="main-content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                     <div class="panel-heading">
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
           
                </div>
                <div class="panel-body m-t-20">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 table-responsive">
                            <table class="table table-bordered table_obtor_data table-hover">
                                <thead class="no-bd">
                                    <tr>
                                        <th class="table_id table_head"><?php echo $this->translate("ID");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Level");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Institute");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("From-Date");?></th>
                                         <th class="table_data table_head"><?php echo $this->translate("To-Date");?></th>
                                    </tr>
                                </thead>
                                <tbody class="no-bd-y">

                                    <?php if ($this->education) { ?>
                                        <?php foreach ($this->education As $rIndex => $educationQual) { ?>
                                            <tr>
                                                <td>
                                                    <a title="<?php echo $this->translate("View");?>" href="<?php print($this->baseUrl()); ?>/my-profile/education-qualification-view/?id=<?php print($educationQual->getId()); ?>">
                                                    <?php print($rIndex+1); ?>
                                                    </a>
                                                </td>
                                                <td><?php print($educationQual->getLevel()); ?></td>
                                                <td><?php print($educationQual->getInstitute()); ?></td>
                                                <td><?php print($educationQual->getStartDate()); ?></td>
                                                <td><?php print($educationQual->getEndDate()); ?></td>

                                            </tr>
                                        <?php } ?>
                                    <?php } else {?>
                                            <tr>
                                                <td colspan="5" class="table_data_not_found"><?php echo $this->translate("Records-Not-Available");?></td>
                                            </tr>
                                    <?php } ?>

                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>