<div id="main-content">

    <div class="row">
        <div class="col-md-12">


            <form id="form_asset" name="form_asset" role="form" method="post" class="form-horizontal" enctype="multipart/form-data">
                <div class="panel panel-default">
                    
                    <div class="panel-heading">
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
           
                </div>

                    <div class="panel-body">


                        <div class="row">
                            <div class="col-md-12">
                                
                             
                                   <div class="col-md-12 col-sm-12 col-xs-12 m-t-20">
                                    
                                    
                                         <div class="view_information">
                                            <ul>
                                                <li>
                                                    <span><?php echo $this->translate("Announce-To");?></span>
                                                   : <?php print($this->announcementInfo->getAnnounceTo());?>
                                                    <div class="clear"></div>
                                                </li>
                                
                                                <li>
                                                    <span><?php echo $this->translate("Media");?></span>
                                                   : <?php print($this->announcementInfo->getAnnounceType());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Announcement-Subject");?></span>
                                                   : <?php print($this->announcementInfo->getSubject());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Message");?></span>
                                                   : <?php print($this->announcementInfo->getMessage());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Recipient-List");?></span>
                                                   : <?php foreach($this->announcementQueueList As $qlIndex=>$announcementQueue){?>
                                                   <?php print($this->getEmployee($announcementQueue->getStaffId())->getNameWithInitials()); ?>,
                                                   <?php } ?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                            </ul>
                                    </div>
                                    
                                </div>
                                
                                
                            </div>
                            
                            
                           
                            
                            
                       
                        </div>
                        
   
                 
                    </div>
                    
                    
                    
                    
                    
                </div>
            </form>


        </div>
    </div>




</div>