<div id="main-content">

    <div class="row">
        <div class="col-md-12">


            <form id="form_asset" name="form_asset" role="form" method="post" class="form-horizontal" enctype="multipart/form-data">
                <div class="panel panel-default">
                    
                    <div class="panel-heading">
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
           
                </div>

                    <div class="panel-body">


                        <div class="row">
                            <div class="col-md-12">
                                
                               <div class="col-md-12 col-sm-12 col-xs-12 m-b-10">
                                   
                                   <div class="view_information">
                                            <ul>
                                                <li>
                                                    <span><?php echo $this->translate("Task-Name");?></span>
                                                   : <?php print($this->taskInformation->getName());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Project-Name");?></span>
                                                   : <?php print($this->getProject($this->taskInformation->getProjectId())->getProjectName());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Assigned-To");?></span>
                                                   : <?php print($this->getEmployee($this->taskInformation->getAssignedTo())->getNameWithInitials()); ?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Current-Status");?></span>
                                                   : <?php print($this->taskInformation->getCurrentStatus());?>
                                                    <div class="clear"></div>
                                                </li>
                                    
                                              <li>
                                                    <span><?php echo $this->translate("Task-Type");?></span>
                                                   : <?php print($this->taskInformation->getTaskType());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Task-Priority");?></span>
                                                   : <?php print($this->taskInformation->getPriority());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Task-Progress");?></span>
                                                   : <?php print($this->taskInformation->getProgress());?>%
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                 <li>
                                                    <span><?php echo $this->translate("Allocated-Hours");?></span>
                                                   : <?php print($this->taskInformation->getAllocatedHours());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                 <li>
                                                    <span><?php echo $this->translate("Hours-Spent");?></span>
                                                   : <?php print($this->taskInformation->getHoursSpent());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Start-Date");?></span>
                                                   : <?php print($this->taskInformation->getStartDate());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("End-Date");?></span>
                                                   : <?php print($this->taskInformation->getEndDate());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Task-Description");?></span>
                                                   : <?php print($this->taskInformation->getDescription());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                            </ul>
                                    </div>
                                  
                               </div>
                            </div>
                       
                        </div>
                        
                    </div>
                    
                    
                    
                    
                    
                </div>
            </form>


        </div>
    </div>




</div>