<div id="main-content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 table-responsive m-t-20">
                            <table class="table table-bordered table_obtor_data table-hover">
                                <thead class="no-bd">
                                    <tr>
                                        <th class="table_id table_head"><?php echo $this->translate("Invoice");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Client-Name");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Invoice-Date");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Due-Date");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Total");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Payment-Method");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Status");?></th>
                                        <th class="text-center table_head data_table_action"><?php echo $this->translate("Actions");?></th>
                                    </tr>
                                </thead>
                                <tbody class="no-bd-y">

                                <?php if($this->invoices){?>
			    <?php foreach($this->invoices As $index=>$invoice){?>
                                            <tr>
                                                <td>
                                                  <?php print($invoice->getId());?>
                                                </td>
                                                <td><?php print($invoice->getClient()->getCompanyname());?></td>
                                <td><?php print($invoice->getDate());?></td>
                                <td><?php print($invoice->getDueDate());?></td>
                                <td><?php print($invoice->getTotal());?></td>
                                <td>
                                <?php 
                                if($invoice->getPaymentmethod()){
                                print($invoice->getPaymentmethod()->getName());
                                }
                                ?>
                                </td>
                                <td><?php print($invoice->getStatus());?></td>      
                                                
                                                <td class="text-center">
                                                   <a title="<?php echo $this->translate("Edit");?>" href="<?php print($this->baseUrl());?>/admin/invoice/view-invoice/id/<?php print($invoice->getId());?>"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_edit.png" /></a>
                                                    <a title="<?php echo $this->translate("Delete");?>" href="<?php print($this->baseUrl());?>/admin/invoice/delete-invoice/id/<?php print($invoice->getId());?>" class="form-data-delete"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_drop.png" /></a>
                                                </td>
                                            </tr>
                                            
                                        <?php } ?>
			   <?php } else {?>
                                            <tr>
                                                <td colspan="8" class="table_data_not_found"><?php echo $this->translate("Records-Not-Available");?></td>
                                            </tr>
                                    <?php } ?>
                                        

                                </tbody>
                            </table>

                        </div>
                    </div>
                    
                    <?php if(count($this->invoices)>0){?>
			<?php echo $this->partial('common/_pagination.phtml', array('paginationData' => $this->paggination)); ?>
                    <?php } ?>
                    <!-- The pagination comes here... -->
                    
                </div>
            </div>
        </div>
    </div>
</div>
