<div id="main-content">

    <div class="row">
        <div class="col-md-12">


            <form id="form_invoice" name="form_invoice" role="form" method="post" class="form-horizontal" enctype="multipart/form-data">
                <div class="panel panel-default">

                    <div class="panel-heading">
                        <div class="btn-group pull-right">
                            <a href="#" id="form-data-back" class="btn btn-blue">
                                <?php echo $this->translate("Go-back"); ?> <i class="fa fa-backward"></i>
                            </a>
                        </div>

                    </div>

                    <div class="panel-body">

                        <h5 class="panel-title"><strong>
                                <?php echo $this->translate("Invoice"); ?> #<?php print($this->invoiceInfo->getId());?>
                            </strong></h5>
                        <div class="row border-top">
                            <div class="col-md-6">

                                <div class="col-md-12 col-sm-12 col-xs-12 m-t-20">


                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Client-Name"); ?></strong></label>
                                        <span class="tips data_value"><?php print($this->invoiceInfo->getClient()->getFirstname());?> (<a href="#">View Invoices</a>)</span>
                                    </div>

                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Invoice-Date"); ?></strong></label>
                                        <span class="tips data_value"><?php print($this->invoiceInfo->getDate());?></span>
                                    </div>


                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Due-Date"); ?></strong></label>
                                        <span class="tips data_value"><?php print($this->invoiceInfo->getDueDate());?></span>
                                    </div>

                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Total-Due"); ?></strong></label>
                                        <span class="tips data_value">
                                            <?php print($this->customerCurrency->getCurrencySym());?> <?php print($this->invoiceInfo->getTotal());?> <?php print($this->customerCurrency->getName());?>
                                        </span>
                                    </div>


                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Balance"); ?></strong></label>
                                        <span class="tips data_value">
                                            <?php print($this->customerCurrency->getCurrencySym());?> 0.00 <?php print($this->customerCurrency->getName());?>
                                        </span>
                                    </div>

                                </div>



                            </div>
                            <div class="col-md-6">


                                <div class="col-md-12 col-sm-12 col-xs-12 m-t-20">

                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Paid"); ?></strong></label>
                                        <span class="tips data_value">18/11/2013 15:30</span>
                                    </div>

                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Payment-Method"); ?></strong></label>
                                        <span class="tips data_value">
} ?>                                        Direct Debit
                                        </span>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label">
                                            <select name="tplname" class="form-control">
    <option>Invoice Payment Confirmation</option>
    <option>Credit Card Payment Confirmation</option>
    <option>Invoice Created</option>
    <option>Credit Card Invoice Created</option>
    <option>Invoice Payment Reminder</option>
    <option>First Invoice Overdue Notice</option>
    <option>Second Invoice Overdue Notice</option>
    <option>Third Invoice Overdue Notice</option>
    <option>Credit Card Payment Due</option>
    <option>Credit Card Payment Failed</option>
    <option>Invoice Refund Confirmation</option>
</select>
                                        </label>
                                        <span class="tips data_value">
                                            <button class="btn">Send Email</button>
                                        </span>
                                    </div>

                                    <div class="form-group">
                                        
                                        <button class="btn">Attempt Capture</button>
                                      <button class="btn">Mark Cancelled</button>
                                      <button class="btn">Mark Unpaid</button>  
                                    </div>


                                    <div class="form-group">
                                         <button class="btn">Printable Version</button>
                                      <button class="btn">View PDF</button>
                                      <button class="btn">Download PDF</button>  
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    
      <div class="row">
        <div class="col-md-12">


            <form id="form_invoice" name="form_invoice" role="form" method="post" class="form-horizontal" enctype="multipart/form-data">
                <div class="panel panel-default">
			<div class="panel-body">

                        <h5 class="panel-title"><strong>
                                <?php echo $this->translate("Order-Items");?>
                            </strong></h5>
                        <div class="row border-top">
                            <div class="col-md-12">

                                <div class="col-md-12 col-sm-12 col-xs-12 m-t-20">

                                    
                            <table class="table table-bordered table_obtor_data table-hover">
                        <thead>
                            <tr>
                                <th class="span2 text-center">ID</th>
                                <th>Description</th>
                                <th class="span2 text-center">Amount</th>
                                <th class="span2 text-center">Taxed</th>
                                <th class="span2 text-center"></th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            
                          
                            
                            <?php if($this->invoiceItems){?>
                            <?php 
                                $row_num = 1;
                                $subtotal = 0;
                                foreach($this->invoiceItems As $iIndex=>$invoiceItem){?>
                            <tr>
                                
                                <td>
                                    <?php print($row_num);?>
                                    <input type="hidden" name="txtInvoiceItemId[]" value="<?php print($invoiceItem->getId());?>" />
                                </td>
                                <td><input type="text" name="txtInvoiceItems[]" value="<?php print($invoiceItem->getDescription());?>" style="width: 100%;" class="form-control"/></td>
                                <td class="span2 text-center"><input type="text" name="txtInvoiceAmount[]" value="<?php print($invoiceItem->getAmount());?>" style="width: 80%;" class="form-control text-right" /></td>
                                <td class="span2 text-center">
                                   <input type="checkbox" name="txtInvoicetax[]" value="1" style="width: 100%;" <?php if($invoiceItem->getTaxed() == 1){?> checked="checked" <?php } ?> />
                                </td>
                                <td class="span1 text-center">
                                    x 
                                </td>
                                
                            </tr>
                            <?php 
            $subtotal = $subtotal + $invoiceItem->getAmount(); 
            $row_num = $row_num + 1;
            } ?>
            <?php } ?>
                            <tr>
                <td><?php print($row_num);?></td>
                <td><input type="text" name="txtInvoiceItem" value="" style="width: 100%;" class="form-control" />  </td>
                <td class="text-right"><input type="text" name="txtInvoiceAmt" value="" style="width: 80%;" class="form-control text-right" /></td>
                <td class="text-center"><input type="checkbox" name="txtInvoicet" value="1" style="width: 100%;" class="form-control"/></td>
                <td class="text-center">x</td>
            </tr>
                            
                           <tr>
                <td class="span1 text-center">&nbsp;</td>
                <td class="text-right"><strong>Sub Total:</strong></td>
                <td class="span2 text-right"><?php print($this->customerCurrency->getCurrencySym());?> <?php print($subtotal);?> <?php print($this->customerCurrency->getName());?></td>
                <td class="span1 text-center">&nbsp;</td>
                <td class="span1 text-center"></td>
            </tr>
            <tr>
                <td class="span1 text-center">&nbsp;</td>
                <td class="text-right">VAT:</td>
                <td class="span2 text-right"><?php print($this->customerCurrency->getCurrencySym());?> 0.00 <?php print($this->customerCurrency->getName());?></td>
                <td class="span1 text-center">&nbsp;</td>
                <td class="span1 text-center"></td>
            </tr>
            
            <tr>
                <td class="span1 text-center">&nbsp;</td>
                <td class="text-right"><strong>Total Due:</strong></td>
                <td class="span2 text-right"><?php print($this->customerCurrency->getCurrencySym());?> <?php print($this->invoiceInfo->getTotal());?> <?php print($this->customerCurrency->getName());?></td>
                <td class="span1 text-center">&nbsp;</td>
                <td class="span1 text-center"></td>
            </tr>
                            
                           
                            
                        
                        </tbody>
                    </table>
                                    
                                    
                                    <div class="row m-l-10">
                                    
                                       
                                        
                                        <div class="form-group text-left">
                                            <input type="hidden" name="txtInvoiceId" value="<?php print($this->invoiceInfo->getId());?>" />
                    <button class="btn btn-success"><i class="icon-save"></i> Save Changes</button>
                                        </div>
                                    
                                </div>

 </div>
                                
                                
                                
                                
                                
 </div>
 </div>
                            
                            
                            
                            
 </div>
 </div>
                
                
                
                
</form>
 </div>
          
          
          
 </div>
    
    
    
    <div class="row">
        <div class="col-md-12">


            <form id="form_invoice" name="form_invoice" role="form" method="post" class="form-horizontal" enctype="multipart/form-data">
                <div class="panel panel-default">
			<div class="panel-body">

                        <h5 class="panel-title"><strong>
                                <?php echo $this->translate("Transactions");?>
                            </strong></h5>
                        <div class="row border-top">
                            <div class="col-md-12">

                                <div class="col-md-12 col-sm-12 col-xs-12 m-t-20">

                                    
                            <table class="table table-bordered table_obtor_data table-hover">
                        <thead>
                            <tr>
                               <th class="span1 text-center">ID</th>
                                <th class="span1 text-center">Date</th>
                                <th class="span2">Payment Method</th>
                                <th class="span1">Transaction ID</th>
                                <th class="span1 text-center">Amount In</th>
                                <th class="span1 text-center">Fees</th>
                                <th class="span1 text-center">Amount Out</th>
                                <th class="span1 text-center"><i class="icon-bolt"></i> Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            <?php if($this->transactions){?>
			    <?php foreach($this->transactions As $index=>$transaction){?>
                            <tr>
                                <td class="span1 text-center"><?php print($index+1);?></td>
                                <td><?php print($transaction->getDate());?></td>
                                <td><?php print($transaction->getGateway()->getName());?></td>
                                <td><?php print($transaction->getTransId());?></td>
                                <td><?php print($this->customerCurrency->getCurrencySym());?> <?php print($transaction->getAmountIn());?> <?php print($this->customerCurrency->getName());?></td>
                                <td><?php print($this->customerCurrency->getCurrencySym());?> <?php print($transaction->getFees());?> <?php print($this->customerCurrency->getName());?></td>
                                <td><?php print($this->customerCurrency->getCurrencySym());?> <?php print($transaction->getAmountOut());?> <?php print($this->customerCurrency->getName());?></td>
                              
                                <td class="text-center">
                                                    <a title="<?php echo $this->translate("Edit");?>" href="#"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_edit.png" /></a>
                                                    <a title="<?php echo $this->translate("Delete");?>" href="#" class="form-data-delete"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_drop.png" /></a>
                                                </td>
                                
                            </tr>
                            <?php } ?>
			    <?php } ?>
                        </tbody>
                    </table>
                                    
                                    
                                    

 </div>
                                
                                
                                
                                
                                
 </div>
 </div>
                            
                            
                            
                            
 </div>
 </div>
                
                
                
                
</form>
 </div>
          
          
          
 </div>
    
    
    
    
    
    
</div>
<script src="<?php print($this->baseUrl()); ?>/invoices/validator/admin/invoice.js"></script>