 <div id="main-content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="btn-group">
                        <a href="<?php print($this->baseUrl()); ?>/admin/salary-particulars/add/?rel-id=<?php print($this->relId);?>" id="table-edit_new" class="btn btn-danger">
                            <?php echo $this->translate("Add-New");?> <i class="fa fa-plus"></i>
                        </a>
                    </div>
                    
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 table-responsive">
                            <table class="table table-bordered table_obtor_data table-hover">
                                <thead class="no-bd">
                                    <tr>
                                        <th class="table_id table_head"><?php echo $this->translate("ID");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Salary-Type");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Salary-Amount");?></th>  
                                        <th class="table_data table_head"><?php echo $this->translate("Effective-From");?></th> 
                                         <th class="table_data table_head"><?php echo $this->translate("Update-On");?></th> 
                                          <th class="table_data table_head"><?php echo $this->translate("Updated-By");?></th> 
                                        <th class="table_head text-center data_table_action"><?php echo $this->translate("Actions");?></th>
                                    </tr>
                                </thead>
                                <tbody class="no-bd-y">

                                    <?php if ($this->salaryParticulars) { ?>
                                        <?php foreach ($this->salaryParticulars As $rIndex => $salaryParticular) { ?>
                                            <tr>
                                                <td>
                                                    <a title="<?php echo $this->translate("View");?>" href="<?php print($this->baseUrl()); ?>/admin/salary-particulars/view/?rel-id=<?php print($this->relId);?>&id=<?php print($salaryParticular->getId()); ?>">
                                                    <?php print($rIndex+1); ?>
                                                    </a>
                                                </td>
                                                <td><?php print($salaryParticular->getSalaryType()); ?></td>
                                                <td><?php print($salaryParticular->getSalaryAmount()); ?></td>
                                                <td><?php print($salaryParticular->getEffectiveFrom()); ?></td>
                                                <td><?php print($salaryParticular->getUpdatedOn()); ?></td>
                                                <td><?php print($salaryParticular->getUpdatedBy()); ?></td>

                                                <td class="text-center">
                                                    <a title="<?php echo $this->translate("Edit");?>" href="<?php print($this->baseUrl()); ?>/admin/salary-particulars/edit/?rel-id=<?php print($this->relId);?>&id=<?php print($salaryParticular->getId()); ?>"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_edit.png" /></a>
                                                    <a title="<?php echo $this->translate("Delete");?>" href="<?php print($this->baseUrl()); ?>/admin/salary-particulars/delete/?rel-id=<?php print($this->relId);?>&id=<?php print($salaryParticular->getId()); ?>" class="form-data-delete"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_drop.png" /></a>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                    <?php } else {?>
                                            <tr>
                                                <td colspan="7" class="table_data_not_found"><?php echo $this->translate("Records-Not-Available");?></td>
                                            </tr>
                                    <?php } ?>

                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
