<div id="main-content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    
                    
                    
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 table-responsive m-t-20">
                            <table class="table table-bordered table_obtor_data table-hover">
                                <thead class="no-bd">
                                    <tr>
                                        <th class="table_id table_head"><strong><?php echo $this->translate("ID");?></strong></th>
                                        <th class="table_data table_head"><strong><?php echo $this->translate("Title");?></strong></th>
                                        <th class="table_data table_head"><strong><?php echo $this->translate("Description");?></strong></th>
                                        <th class="table_data table_head"><strong><?php echo $this->translate("Permission");?></strong></th>
                                        <th class="table_data table_head"><strong><?php echo $this->translate("Added_By");?></strong></th>
                                        <th class="table_data table_head"><strong><?php echo $this->translate("Added_On");?></strong></th>
                                    </tr>
                                </thead>
                                <tbody class="no-bd-y">

                                    <?php if ($this->documentInformation) { ?>
                                        <?php foreach ($this->documentInformation As $dIndex => $document) { ?>
                                            <tr>
                                                <td>
                                                    <a title="<?php echo $this->translate("View");?>" href="<?php print($this->baseUrl()); ?>/document/view/id/<?php print($document->getId()); ?>">
                                                    <?php print($document->getId()); ?>
                                                    </a>
                                                </td>
                                                <td><?php print($document->getDocTitle()); ?></td>
                                                 <td><?php print($document->getDocDescription()); ?></td>
                                            
                                               
                                              <td><?php print($document->getDocPermission()); ?></td>
                                              <td><?php print($document->getDocAddedBy()); ?></td>
                                              <td><?php print($document->getDocAddedOn()); ?></td>
                                              
                                            </tr>
                                        <?php } ?>
                                    <?php } else {?>
                                            <tr>
                                                <td colspan="7" class="table_data_not_found"><?php echo $this->translate("Records-Not-Available");?></td>
                                            </tr>
                                    <?php } ?>

                                </tbody>
                            </table>

                        </div>
                    </div>
                    
                    
                    <?php if(count($this->documentInformation)>0){?>
			<?php echo $this->partial('common/_pagination.phtml', array('paginationData' => $this->paggination)); ?>
                    <?php } ?>
                    
                </div>
            </div>
        </div>
    </div>
</div>