<div id="main-content">

    <div class="row">
        <div class="col-md-12">


            <form id="form_asset" name="form_asset" role="form" method="post" class="form-horizontal" enctype="multipart/form-data">
                <div class="panel panel-default">
                    
                    <div class="panel-heading">
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
           
                </div>

                    <div class="panel-body">


                        <div class="row">
                            <div class="col-md-12">
                                
                             
                                   <div class="col-md-12 col-sm-12 col-xs-12 m-t-20">
                                    
                                    
                                         <div class="view_information">
                                            <ul>
                                                <li>
                                                    <span><?php echo $this->translate("Document-Title");?></span>
                                                   : <?php print($this->documentInfo->getDocTitle());?>
                                                    <div class="clear"></div>
                                                </li>
                                
                                                <li>
                                                    <span><?php echo $this->translate("Description");?></span>
                                                   : <?php print($this->documentInfo->getDocDescription());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Attachment-file");?></span>
                                                   :  <a href="<?php print($this->baseUrl());?>/uploads/documents/<?php print($this->documentInfo->getDocAttachment());?>" target="_blank">
                                            <?php echo $this->translate("Click-Here-To-Download");?>
                                            </a>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Permission"); ?></span>
                                                   : <?php print($this->documentInfo->getDocPermission());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Share-List");?></span>
                                                   : <?php
                                                   if($this->shareList){
                                                   foreach($this->shareList As $slIndex=>$share){?>
                                                   <?php print($this->getEmployee($share->getUserId())->getNameWithInitials()); ?>,
                                                   <?php }} ?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                            </ul>
                                    </div>
                                    
                                </div>
                                
                                
                            </div>
                            
                            
                           
                            
                            
                       
                        </div>
                        
   
                 
                    </div>
                    
                    
                    
                    
                    
                </div>
            </form>


        </div>
    </div>




</div>