 <div id="main-content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="btn-group">
                        <a href="<?php print($this->baseUrl()); ?>/admin/department/add" id="table-edit_new" class="btn btn-danger">
                            <?php echo $this->translate("Add-New");?> <i class="fa fa-plus"></i>
                        </a>
                    </div>
                    
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 table-responsive">
                          <table class="table table-bordered table_obtor_data table-hover">
                                <thead class="no-bd">
                                    <tr>
                                        <th class="table_head"><?php echo $this->translate("Country-Name");?></th>
                                        <th class="table_head"><?php echo $this->translate("Region-Name");?></th>
                                        <th class="table_head"><?php echo $this->translate("Branch-Name");?></th>
                                        <th class="table_head"><?php echo $this->translate("Department-Name");?></th>
                                        <th class="text-center table_head data_table_action"><?php echo $this->translate("Actions");?></th>
                                    </tr>
                                </thead>
                                <tbody class="no-bd-y">

                                    <?php if ($this->departments) { ?>
                                        <?php foreach ($this->departments As $rIndex => $department) { ?>
                                            <tr>
                                                <td><?php if($department->getBranch()->getRegion()){ if($department->getBranch()->getRegion()->getCountry()){print($department->getBranch()->getRegion()->getCountry()->getName());}}?></td>
                                                <td><?php if($department->getBranch()->getRegion()){print($department->getBranch()->getRegion()->getName());}?></td>
                                                <td><?php if($department->getBranch()->getRegion()){print($department->getBranch()->getName());}?></td>
                                                <td><?php print($department->getName()); ?></td>
                                                <td class="text-center">
                                                    <a title="<?php echo $this->translate("Edit");?>" href="<?php print($this->baseUrl()); ?>/admin/department/edit/id/<?php print($department->getId()); ?>"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_edit.png" /></a>
                                                    <a title="<?php echo $this->translate("Delete");?>" href="<?php print($this->baseUrl()); ?>/admin/department/delete/id/<?php print($department->getId()); ?>" class="form-data-delete"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_drop.png" /></a>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                    <?php } ?>

                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
