<div id="main-content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    
                     <div class="btn-group">
                        <a href="<?php print($this->baseUrl()); ?>/admin/contact/add/" id="table-edit_new" class="btn btn-danger">
                            <?php echo $this->translate("Add-New");?> <i class="fa fa-plus"></i>
                        </a>
                    </div>
                    
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 table-responsive m-t-20">
                            <table class="table table-bordered table_obtor_data table-hover">
                                <thead class="no-bd">
                                    <tr>
                                        <th class="table_id table_head"><?php echo $this->translate("ID");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("First_Name");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Contact_Numbers");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("E-mail-Address");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("User-Type");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Contact-Type");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Other-Email");?></th>
                                        <th class="text-center table_head data_table_action"><?php echo $this->translate("Actions");?></th>
                                    </tr>
                                </thead>
                                <tbody class="no-bd-y">

                                    <?php if ($this->contactInformation) { ?>
                                        <?php foreach ($this->contactInformation As $cIndex => $contactInfo) { ?>
                                            <tr>
                                                <td>
                                                    <a title="<?php echo $this->translate("View");?>" href="<?php print($this->baseUrl()); ?>/admin/lead/view/id/<?php print($contactInfo->getId()); ?>">
                                                    <?php print($contactInfo->getId()); ?>
                                                    </a>
                                                </td>
                                                <td><?php print($contactInfo->getFirstName()); ?></td>
                                                <td>
                                                    <div class="col-md-12 col-sm-12 col-xs-12" id="tooltips">
                                                        <a rel="tooltip" data-toggle="tooltip" data-placement="top" title="<?php print($contactInfo->getMobile()); ?>/<?php print($contactInfo->getPhone()); ?>">
                                                          <?php print($contactInfo->getMobile()); ?>
                                                        </a>
                                                    </div> 
                                                    
                                                </td>
                                                
                                                <td><?php print($contactInfo->getEmailAddress()); ?></td>
                                                <td><?php print($contactInfo->getUserType()); ?></td>
                                                <td><?php print($contactInfo->getContactType()); ?></td>
                                                <td><?php print($contactInfo->getOtherEmail()); ?></td>
                                                
                                                <td class="text-center">
                                                    <a title="<?php echo $this->translate("Edit");?>" href="<?php print($this->baseUrl()); ?>/admin/contact/edit/id/<?php print($contactInfo->getId()); ?>"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_edit.png" /></a>
                                                    <a title="<?php echo $this->translate("Delete");?>" href="<?php print($this->baseUrl()); ?>/admin/contact/delete/id/<?php print($contactInfo->getId()); ?>" class="form-data-delete"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_drop.png" /></a>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                   <?php } else {?>
                                            <tr>
                                                <td colspan="8" class="table_data_not_found"><?php echo $this->translate("Records-Not-Available");?></td>
                                            </tr>
                                    <?php } ?>

                                </tbody>
                            </table>

                        </div>
                    </div>
                    
                    
                    <?php if(count($this->contactInformation)>0){?>
			<?php echo $this->partial('common/_pagination.phtml', array('paginationData' => $this->paggination)); ?>
                    <?php } ?>
                    
                </div>
            </div>
        </div>
    </div>
</div>