<div id="main-content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">

                <div class="panel-heading">
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            Go back <i class="fa fa-backward"></i>
                        </a>
                    </div>

                </div>


                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form id="form_user_role" name="form_user_role" role="form" method="post" class="form-horizontal">


                                <div class="form-group">
                                   <label class="form-label"><strong>Role Name</strong></label> : <label class="control-label"><?php if ($this->userRoleInfo) { ?> <?php print($this->userRoleInfo->getName()); ?> <?php } ?></label>
                                </div>

                                <div class="form-group text-left">
                                    <button class="btn btn-blue" type="submit" name="Submit" id="Submit">Submit</button>
                                    <button type="reset" class="btn btn-default">Cancel</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>