<div id="main-content">

    <div class="row">
        <div class="col-md-12">


            <form id="form_asset" name="form_asset" role="form" method="post" class="form-horizontal" enctype="multipart/form-data">
                <div class="panel panel-default">
                    
                    <div class="panel-heading">
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
           
                </div>

                    <div class="panel-body">


                        <div class="row">
                            <div class="col-md-6">
                                
                                <div class="col-md-12 col-sm-12 col-xs-12 m-t-20">
                                    
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("some-texts");?></strong></label>
                                        <span class="tips data_value">some texts1</span>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("some-texts");?></strong></label>
                                        <span class="tips data_value">some texts1</span>
                                    </div>
                                    
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("some-texts");?></strong></label>
                                        <span class="tips data_value">some texts1</span>
                                    </div>
                                    
                                    
                                    
                                   
                                    
                                </div>
                                
                                
                                
                            </div>
                            <div class="col-md-6">
                                
                                
                               <div class="col-md-12 col-sm-12 col-xs-12 m-t-20">
                                    
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("some-texts");?></strong></label>
                                        <span class="tips data_value">some texts1</span>
                                    </div>
                                   <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("some-texts");?></strong></label>
                                        <span class="tips data_value">some texts1</span>
                                    </div>
                                   
                                   <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("some-texts");?></strong></label>
                                        <span class="tips data_value">some texts1</span>
                                    </div>
                                   
                                   
                                   
                                    
                                    
                                </div>
                            
                            
                            
                            </div>
                            
                            
                            
                            <div class="col-md-12">
                                
                                
                               <div class="col-md-12 col-sm-12 col-xs-12 m-b-10">
                                   
                                   
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("some-texts");?></strong>
                                        </label>
                                        <div class="controls">
                                            <span class="tips data_value">asdasdasdasd</span>
                                        </div>
                                    </div>
                                  
                                   
                               </div>
                                
                            </div>
                            
                            
                       
                        </div>
                        
                        
                        
                      <?php echo $this->partial('common/_system_log.phtml', array('logInformation' => $this->logInformation)); ?> 
                 
                    </div>
                    
                    
                    
                    
                    
                </div>
            </form>


        </div>
    </div>




</div>
<script src="<?php print($this->baseUrl()); ?>/assets/validator/admin/asset.js"></script>