   <div id="main-content">
            
            <div class="row">
                <div class="col-md-12">
            
                    
                    
                    <div class="panel panel-default">
                        
                        <div class="panel-heading">
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
           
                </div>
                   
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="view_information">
                                            <ul>
                                                <li>
                                                    <span><?php echo $this->translate("Level");?></span>
                                                   : <?php print($this->edualificationInfo->getLevel());?>
                                                    <div class="clear"></div>
                                                </li>
                                                <li>
                                                    <span><?php echo $this->translate("Institute");?></span>
                                                   : <?php print($this->edualificationInfo->getInstitute());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                 <li>
                                                    <span><?php echo $this->translate("Major-Specialization");?></span>
                                                   : <?php print($this->edualificationInfo->getMajorSpecialization());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Year");?></span>
                                                   : <?php print($this->edualificationInfo->getYear());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Gpa");?></span>
                                                   : <?php print($this->edualificationInfo->getGpa());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Start-Date");?></span>
                                                   : <?php print($this->edualificationInfo->getStartDate());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                 <li>
                                                    <span><?php echo $this->translate("End-Date");?></span>
                                                   : <?php print($this->edualificationInfo->getEndDate());?>
                                                    <div class="clear"></div>
                                                </li>

                                                
                                            </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    
                    
                </div>
            </div>
            
                        
            
                        
        </div>
