<!-- BEGIN MANDATORY SCRIPTS -->
    
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/jquery-migrate-1.2.1.js"></script>
        <script type="text/javascript"
            src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>
    <link rel="stylesheet" type="text/css"
          href="http://code.jquery.com/ui/1.11.0/themes/base/jquery-ui.css"/>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/bootstrap/bootstrap.min.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/bootstrap-dropdown/bootstrap-hover-dropdown.min.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/bootstrap-select/bootstrap-select.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/icheck/icheck.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/mcustom-scrollbar/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/mmenu/js/jquery.mmenu.min.all.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/nprogress/nprogress.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/charts-sparkline/sparkline.min.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/breakpoints/breakpoints.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/numerator/jquery-numerator.js"></script>
    <!-- END MANDATORY SCRIPTS -->
     <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/metrojs/metrojs.min.js"></script>


     <script type="text/javascript" src="<?php print($this->baseUrl());?>/assets/skin/plugins/jquery_tree/src/js/jquery.tree.js"></script>
     
    <script src="<?php print($this->baseUrl());?>/assets/skin/obtor/js/notifIt.js" type="text/javascript"></script>
   <link href="<?php print($this->baseUrl());?>/assets/skin/obtor/css/notifIt.css" type="text/css" rel="stylesheet"> 
   <script src="<?php print($this->baseUrl());?>/assets/skin/obtor/js/messages.js" type="text/javascript"></script>
   <script src="<?php print($this->baseUrl());?>/assets/skin/obtor/js/obtor.js" type="text/javascript"></script>
   

    
   <!-- the poupup boxes -->
   
   
    <script src="<?php print($this->baseUrl());?>/assets/skin/js/application.js"></script>

    