<!-- BEGIN MANDATORY STYLE -->   
<link href="<?php print($this->baseUrl());?>/assets/skin/css/icons/icons.min.css" rel="stylesheet">
    <link href="<?php print($this->baseUrl());?>/assets/skin/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php print($this->baseUrl());?>/assets/skin/css/plugins.min.css" rel="stylesheet">
    <link href="<?php print($this->baseUrl());?>/assets/skin/css/style.min.css" rel="stylesheet">
    <!-- END  MANDATORY STYLE -->
    <!-- BEGIN PAGE LEVEL STYLE -->
    <link href="<?php print($this->baseUrl());?>/assets/skin/plugins/fullcalendar/fullcalendar.css" rel="stylesheet">
    <link href="<?php print($this->baseUrl());?>/assets/skin/plugins/metrojs/metrojs.css" rel="stylesheet">
    <!-- END PAGE LEVEL STYLE -->
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/modernizr/modernizr-2.6.2-respond-1.1.0.min.js"></script>
      <link href="<?php print($this->baseUrl());?>/assets/skin/css/obtor.css" rel="stylesheet">

      
      <!-- java scrip -->
<script src="<?php print($this->baseUrl());?>/assets/skin/plugins/jquery-1.11.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/vendor/js/bootstrap.min.js"></script>
<!-- bootbox code -->
<script src="<?php print($this->baseUrl());?>/assets/skin/obtor/js/bootbox.js"></script>

