<div class="form_content_wrapper">
<form id="form1" name="form1" method="post" action="">
<fieldset><legend> Access Denied </legend>
<div class="single_col">
<ul class="form_items">



	<div class="content_wrapper"><!-- Shash board Items-->
	<ul class="dashboard_items">

		<h1 class="error">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Oops !, Sorry. You are
		not authorized to view this page</h1>


	</ul>
	<div class="clear"></div>
	</div>
</ul>
</div>
</fieldset>
</form>
</div>
