   <div id="main-content">
            
            <div class="row">
                <div class="col-md-12">
            
                    
                     <?php foreach($this->allPaymentMethods As $pIndex=>$paymentMethod){?>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h5 class="panel-title"><strong><?php echo $this->translate($paymentMethod->getName()); ?></strong></h5>
                            <div class="row border-top">
                                <div class="col-md-12 col-sm-12 col-xs-12 m-t-20">
                                    <form id="form_payment_gateways" name="form_payment_gateways" role="form" method="post" class="form-horizontal">
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Display-Name");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                 <input type="text" id="txtPaymentMethodName" name="txtPaymentMethodName" class="form-control" value="<?php print($paymentMethod->getName());?>">
                                                 <input type="hidden" id="txtNameKey" name="txtNameKey" class="form-control" value="<?php print($paymentMethod->getNameKey());?>">
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Status");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <input type="radio" class="rdStatus" name="rdStatus" value="Enabled"  <?php if($paymentMethod->getStatusIs() == 'Enabled'){?> checked="checked" <?php } ?> > <?php echo $this->translate("Enabled");?>
                                                 <input type="radio" class="rdStatus" name="rdStatus" value="Disabled" <?php if($paymentMethod->getStatusIs() != 'Enabled'){?> checked="checked" <?php } ?>> <?php echo $this->translate("Disabled");?>
                                            </div>
                                        </div>
                                        
                                         <?php foreach($paymentMethod->getSettings() As $sIndex=>$setting){?>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong>
                                                     <input type="hidden" name="txtFieldId[]" value="<?php print($setting->getId());?>" />
                                                <?php echo $this->translate($setting->getSettingFieldName());?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                 <?php if($setting->getInputType() == 'text_field'){?>
                                                <input type="text" id="txtFieldName<?php print($sIndex);?>" name="txtFieldName<?php print($sIndex);?>" class="form-control" value="<?php print($setting->getSettingValue());?>">
                                                <?php } elseif($setting->getInputType() == 'check'){?>
                                                <input type="checkbox" id="txtFieldName<?php print($sIndex);?>" name="txtFieldName<?php print($sIndex);?>" class="form-control" value="Yes" <?php if($setting->getSettingValue() == 'Yes'){?> checked="checked" <?php } ?> >
                                                <span><?php print($setting->getFieldDescription());?></span>
                                                <?php } elseif($setting->getInputType() == 'radio'){?>
                                                <input type="radio" id="txtFieldName<?php print($sIndex);?>" name="txtFieldName<?php print($sIndex);?>" class="form-control" value="Yes" <?php if($setting->getSettingValue() == 'Yes'){?> checked="checked" <?php } ?>>
                                                <span><?php print($setting->getFieldDescription());?></span>
                                                <?php } elseif($setting->getInputType() == 'text_area'){?>
                                                <textarea id="txtFieldName<?php print($sIndex);?>" name="txtFieldName<?php print($sIndex);?>" class="form-control" rows="7"><?php print($setting->getSettingValue());?></textarea>
                                                 <?php } ?>
                                            </div>
                                        </div>
                                        
                                        <?php } ?>
                                        
                                   
                                        <div class="form-group text-left">
                                             <input type="hidden" id="txtPaymentMethodId" name="txtPaymentMethodId" class="form-control" value="<?php print($paymentMethod->getId());?>">
                                            <button class="btn btn-blue" type="submit" name="Submit" id="Submit"><?php echo $this->translate("Submit");?></button>
                                            <button type="reset" class="btn btn-default"><?php echo $this->translate("Cancel");?></button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    <?php } ?>
                    
                    
                </div>
            </div>
            
                        
            
                        
        </div>
