   <div id="main-content">
            
            <div class="row">
                <div class="col-md-12">
            
                    
                    
                    <div class="panel panel-default">
                        
                         <div class="panel-heading">
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
           
                </div>
                   
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="view_information">
                                            <ul>
                                                <li>
                                                    <span><?php echo $this->translate("Language");?></span>
                                                   : <?php print($this->languagesInfo->getLanguage());?>
                                                    <div class="clear"></div>
                                                </li>
                                               
                                                <li>
                                                    <span><?php echo $this->translate("Fluency");?></span>
                                                   : <?php print($this->languagesInfo->getFluency());?>
                                                    <div class="clear"></div>
                                                </li>
                                               
                                                 <li>
                                                    <span><?php echo $this->translate("Competency");?></span>
                                                   : <?php print($this->languagesInfo->getCompetency());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Comments");?></span>
                                                   : <?php print($this->languagesInfo->getComments());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                            </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    
                    
                </div>
            </div>
            
                        
            
                        
        </div>
