<!-- BEGIN MANDATORY SCRIPTS -->
    

    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/bootstrap-dropdown/bootstrap-hover-dropdown.min.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/bootstrap-select/bootstrap-select.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/icheck/icheck.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/mcustom-scrollbar/jquery.mCustomScrollbar.concat.min.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/mmenu/js/jquery.mmenu.min.all.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/nprogress/nprogress.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/charts-sparkline/sparkline.min.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/breakpoints/breakpoints.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/numerator/jquery-numerator.js"></script>
    <!-- END MANDATORY SCRIPTS -->
     <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/metrojs/metrojs.min.js"></script>


     <script type="text/javascript" src="<?php print($this->baseUrl());?>/assets/skin/plugins/jquery_tree/src/js/jquery.tree.js"></script>
     
    <script src="<?php print($this->baseUrl());?>/assets/skin/obtor/js/notifIt.js" type="text/javascript"></script>
   <link href="<?php print($this->baseUrl());?>/assets/skin/obtor/css/notifIt.css" type="text/css" rel="stylesheet"> 
   <script src="<?php print($this->baseUrl());?>/assets/skin/obtor/js/messages.js" type="text/javascript"></script>
   <script src="<?php print($this->baseUrl());?>/assets/skin/obtor/js/obtor.js" type="text/javascript"></script>
   

    
   <!-- the poupup boxes -->
   
   <!-- BEGIN PAGE LEVEL SCRIPTS -->
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/modal/js/classie.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/modal/js/modalEffects.js"></script>
    <!-- END  PAGE LEVEL SCRIPTS -->
    
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/datetimepicker/jquery.datetimepicker.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/bootstrap-datepicker/bootstrap-datepicker.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/pickadate/picker.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/pickadate/picker.date.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/pickadate/picker.time.js"></script>
    
    <script src="<?php print($this->baseUrl());?>/assets/skin/js/application.js"></script>

    