<!-- BEGIN MANDATORY STYLE -->   
<link href="<?php print($this->baseUrl());?>/assets/skin/css/icons/icons.min.css" rel="stylesheet">
    <link href="<?php print($this->baseUrl());?>/assets/skin/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php print($this->baseUrl());?>/assets/skin/css/plugins.min.css" rel="stylesheet">
    <link href="<?php print($this->baseUrl());?>/assets/skin/css/style.min.css" rel="stylesheet">
    <!-- END  MANDATORY STYLE -->
    <!-- BEGIN PAGE LEVEL STYLE -->
    <link href="<?php print($this->baseUrl());?>/assets/skin/plugins/fullcalendar/fullcalendar.css" rel="stylesheet">
    <link href="<?php print($this->baseUrl());?>/assets/skin/plugins/metrojs/metrojs.css" rel="stylesheet">
    <!-- END PAGE LEVEL STYLE -->
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/modernizr/modernizr-2.6.2-respond-1.1.0.min.js"></script>
      <link href="<?php print($this->baseUrl());?>/assets/skin/css/obtor.css" rel="stylesheet">

      <link href="<?php print($this->baseUrl());?>/assets/skin/plugins/modal/css/component.css" rel="stylesheet">
      
      
    <!-- BEGIN PAGE LEVEL STYLE -->
    <link href="<?php print($this->baseUrl());?>/assets/skin/plugins/datetimepicker/jquery.datetimepicker.css" rel="stylesheet">
    <link href="<?php print($this->baseUrl());?>/assets/skin/plugins/pickadate/themes/default.css" rel="stylesheet">
    <link href="<?php print($this->baseUrl());?>/assets/skin/plugins/pickadate/themes/default.date.css" rel="stylesheet">
    <link href="<?php print($this->baseUrl());?>/assets/skin/plugins/pickadate/themes/default.time.css" rel="stylesheet">
    <!-- END PAGE LEVEL STYLE -->
      
      <!-- java scrip -->
<script src="<?php print($this->baseUrl());?>/assets/skin/plugins/jquery-1.11.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/jquery-migrate-1.2.1.js"></script>
    <script type="text/javascript"
            src="<?php print($this->baseUrl());?>/assets/vendor/js/jquery-ui-1.11.0/jquery-ui.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/jquery-mobile/jquery.mobile-1.4.2.js"></script>
    <script src="<?php print($this->baseUrl());?>/assets/skin/plugins/bootstrap/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css"
          href="<?php print($this->baseUrl());?>/assets/vendor/js/jquery-ui-1.11.0/jquery-ui.min.css"/>
<!-- bootbox code -->
<script src="<?php print($this->baseUrl());?>/assets/skin/obtor/js/bootbox.js"></script>