<div class="panel panel-signin">
                <div class="panel-body">
                    <div class="logo text-center">
                        <img src="<?php print($this->baseUrl());?>/assets/staff-login/images/logo-primary.png" alt="Chain Logo" >
                    </div>
                    <br />
                    <p class="text-center">Please enter your email address.</p>
                    
                    <div class="mb30"></div>
                    
<form name="login-form" id="login-form" method="post">
                        <div class="input-group mb15">
                            <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
                            <input type="text" class="form-control" placeholder="Email Address" name="txtEmailAddress" id="txtEmailAddress">
                        </div><!-- input-group -->
                        
                        
                        <div class="clearfix">
                           
                            <div class="pull-right">
                                <button type="submit" class="btn btn-dark">Reset Password <i class="fa fa-angle-right ml5"></i></button>
                            </div>
                        </div>                      
                    </form>
                    
                    
                </div><!-- panel-body -->
                <div class="panel-footer">
                    <a href="<?php print($this->baseUrl());?>/login/" class="btn btn-dark btn-block">Already have an account? Sign In</a>
                </div><!-- panel-footer -->
            </div><!-- panel -->