 <div id="main-content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="btn-group">
                        <a href="<?php print($this->baseUrl()); ?>/admin/region/add" id="table-edit_new" class="btn btn-danger">
                            <?php echo $this->translate("Add-New");?> <i class="fa fa-plus"></i>
                        </a>
                    </div>
                    
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 table-responsive">
                            <table class="table table-hover">
                                <thead class="no-bd">
                                    <tr>
                                        <th><strong><?php echo $this->translate("Country-Name");?></strong></th>
                                        <th><strong><?php echo $this->translate("Region-Name");?></strong></th>
                                        <th class="text-center data_table_action"><strong><?php echo $this->translate("Actions");?></strong></th>
                                    </tr>
                                </thead>
                                <tbody class="no-bd-y">

                                    <?php if ($this->regions) { ?>
                                        <?php foreach ($this->regions As $rIndex => $region) { ?>
                                            <tr>
                                                <td><?php if($region->getCountry()){print($region->getCountry()->getName());}?></td>
                                                 <td><?php print($region->getName()); ?></td>
                                                <td class="text-center">
                                                    <a title="<?php echo $this->translate("Edit");?>" href="<?php print($this->baseUrl()); ?>/admin/region/edit/id/<?php print($region->getId()); ?>"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_edit.png" /></a>
                                                    <a title="<?php echo $this->translate("Delete");?>" href="<?php print($this->baseUrl()); ?>/admin/region/delete/id/<?php print($region->getId()); ?>" class="form-data-delete"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_drop.png" /></a>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                    <?php } ?>

                                </tbody>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
