<div id="main-content">
    <form id="form_staff" name="form_staff" role="form" method="post" class="form-horizontal">
    <div class="row">
        
                <div class="col-md-6">
                    <div class="panel panel-default">

                        <div class="panel-body">
                            <h5 class="panel-title"><strong><?php echo $this->translate("Basic-Information"); ?></strong></h5>
                            <div class="row border-top">
                                <div class="col-md-12 col-sm-12 col-xs-12 m-t-20 m-b-20">
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Employee-Number");?></strong></label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmployeeNumber" name="txtEmployeeNumber" value="<?php print($this->employeeInformation->getEmployeeNumber());?>">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Full-Name");?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtFullName" name="txtFullName" value="<?php print($this->employeeInformation->getFullName());?>">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Name-with-initials");?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtNameWithInitials" name="txtNameWithInitials" value="<?php print($this->employeeInformation->getNameWithInitials());?>">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Gender");?></strong></label>
                                        <div class="controls">
                                            <select parsley-minlength="3" class="form-control normal_input" name="cmbGender" id="cmbGender">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <option value="male" <?php if($this->employeeInformation->getGender() == 'male'){?> selected="selected" <?php }?>><?php echo $this->translate("male"); ?></option>
                                                     <option value="female" <?php if($this->employeeInformation->getGender() == 'female'){?> selected="selected" <?php }?>><?php echo $this->translate("female"); ?></option>
                                                </select>
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Date-Of-Birth");?></strong></label>
                                        <div class="controls">
                                            <input class="pickadate form-control picker__input" type="text" id="txtDateOfBirth" name="txtDateOfBirth" value="<?php print($this->employeeInformation->getDateOfBirth());?>">
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("NIC-Number");?></strong></label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtNICNumber" name="txtNICNumber" value="<?php print($this->employeeInformation->getNationalIdentityCardNo());?>">
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Driving-License-No");?></strong></label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtDrivingLicenseNo" name="txtDrivingLicenseNo" value="<?php print($this->employeeInformation->getDrivingLicenseNo());?>">
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Telephone-number-residence");?></strong></label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmployeeTelephoneNumberResidence" name="txtEmployeeTelephoneNumberResidence" value="<?php print($this->employeeInformation->getTelephoneNumberResidence());?>">
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Contact-number-mobile");?></strong></label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmployeeContactNumber" name="txtEmployeeContactNumber" value="<?php print($this->employeeInformation->getEmergencyContactTelephoneNumberMobile());?>">
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("E-mail-Address-Personal");?></strong></label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmployeeEmailAddressPersonal" name="txtEmployeeEmailAddressPersonal" value="<?php print($this->employeeInformation->getEMailAddressPersonal());?>">
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("E-mail-Address-Office");?></strong></label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmailAddressOffice" name="txtEmailAddressOffice" value="<?php print($this->employeeInformation->getEMailAddressOffice());?>">
                                        </div>
                                    </div>
                                    
                                </div>
                            </div>
                            
                            
                            
                            <h5 class="panel-title"><strong><?php echo $this->translate("Work-Location"); ?></strong></h5>
                            <div class="row border-top">
                                <div class="col-md-12 col-sm-12 col-xs-12 m-t-20 m-b-20">
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Country");?></strong></label>
                                        <div class="controls">
                                                <select class="form-control normal_input" name="txtCountry" id="txtCountry">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <?php foreach($this->countries As $cIndex=>$country){?>
                                                     <option value="<?php print($country->getId());?>" <?php if($this->employeeInformation->getCountry() == $country->getId()){?> selected="selected" <?php } ?>><?php print($country->getName());?></option>
                                                    <?php } ?>
                                                </select>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Region");?></strong>
                                        </label>
                                        <div class="controls">
                                            <span id="region">
                                                <select class="form-control normal_input" name="txtRegion" id="txtRegion">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <?php foreach($this->regions As $cIndex=>$region){?>
                                                     <option value="<?php print($region->getId());?>" <?php if($this->employeeInformation->getRegion() == $region->getId()){?> selected="selected" <?php } ?>><?php print($region->getName());?></option>
                                                    <?php } ?>
                                                </select>
                                                </span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Branch");?></strong>
                                        </label>
                                        <div class="controls">
                                            <span id="branch">
                                                <select class="form-control normal_input" name="txtBranchName" id="txtBranchName">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <?php foreach($this->branches As $cIndex=>$branch){?>
                                                     <option value="<?php print($branch->getId());?>" <?php if($this->employeeInformation->getBranch() == $branch->getId()){?> selected="selected" <?php } ?>><?php print($branch->getName());?></option>
                                                    <?php } ?>
                                                </select>
                                                </span>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Department");?></strong></label>
                                        <div class="controls">
                                           <span id="department">
                                                <select class="form-control normal_input" name="txtDepartmentName" id="txtDepartmentName">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <?php foreach($this->departments As $dIndex=>$department){?>
                                                     <option value="<?php print($department->getId());?>" <?php if($this->employeeInformation->getDepartment() == $department->getId()){?> selected="selected" <?php } ?>><?php print($department->getName());?></option>
                                                    <?php } ?>
                                                </select>
                                                </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            
                                <h5 class="panel-title"><strong><?php echo $this->translate("Employment-Details"); ?></strong></h5>
                            <div class="row border-top">
                                <div class="col-md-12 col-sm-12 col-xs-12 m-t-20 m-b-20">
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Joined-Date");?></strong></label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmployeeJoinedDate" name="txtEmployeeJoinedDate" value="<?php print($this->employeeInformation->getJoinedDate());?>">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Designation");?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmployeeDesignation" name="txtEmployeeDesignation" value="<?php print($this->employeeInformation->getDesignation());?>">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Contract-Status");?></strong>
                                        </label>
                                        <div class="controls">
                                            <select class="form-control normal_input" name="cmbContractStatus" id="cmbContractStatus">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <option value="1" <?php if($this->employeeInformation->getContractStatus() == '1'){?> selected="selected" <?php } ?>><?php echo $this->translate("Probation"); ?></option>
                                                     <option value="2" <?php if($this->employeeInformation->getContractStatus() == '2'){?> selected="selected" <?php } ?>><?php echo $this->translate("Confirmed"); ?></option>
                                                </select>
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Employee-Type");?></strong></label>
                                        <div class="controls">
                                            <select class="form-control normal_input" name="cmbEmployeeType" id="cmbEmployeeType">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                     <option value="1" <?php if($this->employeeInformation->getEmployeeType() == '1'){?> selected="selected" <?php } ?>><?php echo $this->translate("Part-Time"); ?></option>
                                                     <option value="2" <?php if($this->employeeInformation->getEmployeeType() == '2'){?> selected="selected" <?php } ?>><?php echo $this->translate("Full-Time"); ?></option>
                                                </select>
                                        </div>
                                    </div>

				   <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Employee-Status");?></strong></label>
                                        <div class="controls">
                                            <select class="form-control normal_input" name="cmbEmployeeStatus" id="cmbEmployeeStatus">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                     <option value="1" <?php if($this->employeeInformation->getEmployeeStatus() == '1'){?> selected="selected" <?php } ?>><?php echo $this->translate("In-Service"); ?></option>
                                                     <option value="2" <?php if($this->employeeInformation->getEmployeeStatus() == '2'){?> selected="selected" <?php } ?>><?php echo $this->translate("Not-In-Service"); ?></option>
                                                </select>
                                        </div>
                                    </div>

 				<div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Staff-ID-Status");?></strong></label>
                                        <div class="controls">
                                            <select class="form-control normal_input" name="cmbStaffIDStatus" id="cmbStaffIDStatus">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                     <option value="1" <?php if($this->employeeInformation->getStaffIdStatus() == '1'){?> selected="selected" <?php } ?>><?php echo $this->translate("Issued"); ?></option>
                                                     <option value="2" <?php if($this->employeeInformation->getStaffIdStatus() == '2'){?> selected="selected" <?php } ?>><?php echo $this->translate("Not-Issued"); ?></option>
                                                </select>
                                        </div>
                                    </div>

 					<div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Staff-ID-Issued-Date");?></strong></label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtStaffIdIssuedDate" name="txtStaffIdIssuedDate" value="<?php print($this->employeeInformation->getStaffIdIssueDate());?>">
                                        </div>
                                    </div>

				<div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("EPF-ETF-Number");?></strong></label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEpfEtfNumber" name="txtEpfEtfNumber" value="<?php print($this->employeeInformation->getEpfEtfNumber());?>">
                                        </div>
                                    </div>

				<div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("EPF-ETF-JoinedDate");?></strong></label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEpfEtfJoinedDate" name="txtEpfEtfJoinedDate" value="<?php print($this->employeeInformation->getEpfEtfNumberJoinedDate());?>">
                                        </div>
                                    </div>

                                </div>
                            </div> 
                        </div>
                    </div>
                </div>
            
            
                <div class="col-md-6">
                    <div class="panel panel-default">
                         <div class="panel-body">
                            
                             
                       <h5 class="panel-title"><strong><?php echo $this->translate("Permanent-address"); ?></strong></h5>
                            <div class="row border-top">
                                <div class="col-md-12 col-sm-12 col-xs-12 m-t-20 m-b-20">
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Address"); ?></strong></label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmployeeAddress" name="txtEmployeeAddress" value="<?php print($this->employeeInformation->getPermanentAddressAddress());?>">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Street"); ?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmployeeAddressStreet" name="txtEmployeeAddressStreet" value="<?php print($this->employeeInformation->getPermanentAddressState());?>">
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("City"); ?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmployeeAddressCity" name="txtEmployeeAddressCity" value="<?php print($this->employeeInformation->getPermanentAddressCity());?>">
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("State"); ?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmployeeAddressState" name="txtEmployeeAddressState" value="<?php print($this->employeeInformation->getPermanentAddressState());?>">
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Zip-Postal-Code"); ?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmployeeAddressZip" name="txtEmployeeAddressZip" value="<?php print($this->employeeInformation->getPermanentAddressZip());?>">
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Country"); ?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmployeeAddressCountry" name="txtEmployeeAddressCountry" value="<?php print($this->employeeInformation->getPermanentAddressCountry());?>">
                                        </div>
                                    </div>
                                </div>
                            </div>
                       
                       
                       
                       <h5 class="panel-title"><strong><?php echo $this->translate("Residential-Address"); ?></strong></h5>
                            <div class="row border-top">
                                <div class="col-md-12 col-sm-12 col-xs-12 m-t-20 m-b-20">
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Address"); ?></strong></label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmployeeResidentialAddress" name="txtEmployeeResidentialAddress" value="<?php print($this->employeeInformation->getResidentialAddressAddress());?>">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Street"); ?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmployeeResidentialAddressStreet" name="txtEmployeeResidentialAddressStreet" value="<?php print($this->employeeInformation->getResidentialAddressStreet());?>">
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("City"); ?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmployeeResidentialAddressCity" name="txtEmployeeResidentialAddressCity" value="<?php print($this->employeeInformation->getResidentialAddressCity());?>">
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("State"); ?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmployeeResidentialAddressState" name="txtEmployeeResidentialAddressState" value="<?php print($this->employeeInformation->getResidentialAddressState());?>">
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Zip-Postal-Code"); ?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmployeeResidentialAddressZip" name="txtEmployeeResidentialAddressZip" value="<?php print($this->employeeInformation->getResidentialAddressZip());?>">
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Country"); ?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmployeeResidentialAddressCountry" name="txtEmployeeResidentialAddressCountry" value="<?php print($this->employeeInformation->getResidentialAddressCountry());?>">
                                        </div>
                                    </div>
                                </div>
                            </div>
                       
                       
                       <h5 class="panel-title"><strong><?php echo $this->translate("In-Case-of-Emergency"); ?></strong></h5>
                            <div class="row border-top">
                                <div class="col-md-12 col-sm-12 col-xs-12 m-t-20 m-b-20">
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Contact-Name"); ?></strong></label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmergencyContactName" name="txtEmergencyContactName" value="<?php print($this->employeeInformation->getEmergencyContactName());?>">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Relationship"); ?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmergencyContactRelationship" name="txtEmergencyContactRelationship" value="<?php print($this->employeeInformation->getEmergencyContactRelationship());?>">
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Email-address"); ?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmergencyContactEmailaddress" name="txtEmergencyContactEmailaddress" value="<?php print($this->employeeInformation->getEmergencyContactEmailAddress());?>">
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Telephone-number-residence"); ?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmergencyContactTelephoneNumberResidence" name="txtEmergencyContactTelephoneNumberResidence" value="<?php print($this->employeeInformation->getEmergencyContactTelephoneNumberResidence());?>">
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Contact-number-mobile"); ?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmergencyContactMobileNumber" name="txtEmergencyContactMobileNumber" value="<?php print($this->employeeInformation->getEmergencyContactTelephoneNumberMobile());?>">
                                        </div>
                                    </div>
                                    
                                     <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Address"); ?></strong></label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmergencyContactAddress" name="txtEmergencyContactAddress" value="<?php print($this->employeeInformation->getEmergencyContactAddress());?>">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Street"); ?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmergencyContactAddressStreet" name="txtEmergencyContactAddressStreet" value="<?php print($this->employeeInformation->getEmergencyContactAddressStreet());?>">
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("City"); ?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmergencyContactAddressCity" name="txtEmergencyContactAddressCity" value="<?php print($this->employeeInformation->getEmergencyContactAddressCity());?>">
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("State"); ?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmergencyContactAddressState" name="txtEmergencyContactAddressState" value="<?php print($this->employeeInformation->getEmergencyContactAddressState());?>">
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Zip-Postal-Code"); ?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control" type="text" id="txtEmergencyContactAddressZipPostalCode" name="txtEmergencyContactAddressZipPostalCode" value="<?php print($this->employeeInformation->getEmergencyContactAddressZip());?>">
                                        </div>
                                    </div>
                                    
                                    <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Country"); ?></strong>
                                        </label>
                                        <div class="controls">
                                           <input class="form-control" type="text" id="txtEmergencyContactAddressCountry" name="txtEmergencyContactAddressCountry" value="<?php print($this->employeeInformation->getEmergencyContactAddressCountry());?>">
                                        </div>
                                    </div>
                                   
                                    
                                </div>
                            </div>
                 
                             
                             
                        </div>
                        
                    </div>
                </div>
        
        
        
        <div class="col-md-12">
                    <div class="panel panel-default">
                         <div class="panel-body">
				
                             
                            <div class="row">
                                <div class="col-md-12 col-sm-12 col-xs-12">

                                    <div class="row">
                                        <div class="col-md-12">
                                                <div class="form-group text-left">
                                                            <button class="btn btn-blue" type="submit" name="Submit" id="Submit"><?php echo $this->translate("Submit");?></button>
                                                            <button type="reset" class="btn btn-default"><?php echo $this->translate("Cancel");?></button>
                                                </div>
                                        </div>
                                    </div>
                                    
                                </div>
                            </div>
                                
			 </div>
		   </div>
</div>
            
            </div>
        </form>
    
</div>
<script src="<?php print($this->baseUrl());?>/assets/validator/admin/staff.js"></script>