<div id="main-content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    
                     <div class="btn-group">
                        <a href="<?php print($this->baseUrl()); ?>/admin/staff/add/" id="table-edit_new" class="btn btn-danger">
                            <?php echo $this->translate("Add-New");?> <i class="fa fa-plus"></i>
                        </a>
                    </div>
                    
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 table-responsive m-t-20">
                            <table class="table table-hover table_obtor_data">
                                <thead class="no-bd">
                                    <tr>
                                        <th class="table_id"><strong><?php echo $this->translate("ID");?></strong></th>
                                        <th class="table_data"><strong><?php echo $this->translate("Name-with-initials-head");?></strong></th>
                                        <th class="table_data"><strong><?php echo $this->translate("Contact-Numbers");?></strong></th>
                                        <th class="table_data"><strong><?php echo $this->translate("E-mail-Address");?></strong></th>
                                        <th class="table_data"><strong><?php echo $this->translate("Designation");?></strong></th>
                                        <th class="table_data"><strong><?php echo $this->translate("Contract-Status");?></strong></th>
                                        <th class="table_data"><strong><?php echo $this->translate("Employee-Type");?></strong></th>
                                        <th class="table_data"><strong><?php echo $this->translate("Status");?></strong></th>
                                        <th class="text-center data_table_action"><strong><?php echo $this->translate("Actions");?></strong></th>
                                    </tr>
                                </thead>
                                <tbody class="no-bd-y">

                                    <?php if ($this->employeeInfo) { ?>
                                        <?php foreach ($this->employeeInfo As $eIndex => $employee) { ?>
                                            <tr>
                                                <td>
                                                    <a title="<?php echo $this->translate("View");?>" href="<?php print($this->baseUrl()); ?>/admin/staff/view/id/<?php print($employee->getId()); ?>">
                                                    <?php print($employee->getEmployeeNumber()); ?>
                                                    </a>
                                                </td>
                                                <td><?php print($employee->getNameWithInitials()); ?></td>
                                                <td>
                                                    <div class="col-md-12 col-sm-12 col-xs-12" id="tooltips">
                                                        <a rel="tooltip" data-toggle="tooltip" data-placement="top" title="<?php print($employee->getTelephoneNumberMobile()); ?>/<?php print($employee->getTelephoneNumberResidence()); ?>">
                                                          <?php print($employee->getTelephoneNumberMobile()); ?>
                                                        </a>
                                                    </div> 
                                                    
                                                </td>
                                                <td><?php print($employee->getEMailAddressOffice()); ?></td>
                                                <td><?php print($employee->getDesignation()); ?></td>
                                                <td>
                                                    <?php if($employee->getContractStatus() == 1){?>
                                                    <?php echo $this->translate("Probation"); ?>
                                                    <?php } else {?>
                                                    <?php echo $this->translate("Confirmed"); ?>
                                                    <?php } ?>
                                                </td>
                                                <td>
                                                    <?php if($employee->getEmployeeType() == 1) {?>
                                                    <?php echo $this->translate("Part-Time"); ?>
                                                    <?php } else {?>
                                                    <?php echo $this->translate("Full-Time"); ?>
                                                    <?php } ?>
                                                </td>
                                                <td>
                                                    <?php if($employee->getEmployeeStatus() == 1) {?>
                                                    <span class="label bg-green"><?php echo $this->translate("In-Service"); ?></span>
                                                    <?php } else {?>
                                                    <span class="label bg-red"><?php echo $this->translate("Not-In-Service"); ?></span>
                                                    <?php } ?>
                                                </td>
                                                
                                                <td class="text-center">
                                                    <a title="<?php echo $this->translate("Edit");?>" href="<?php print($this->baseUrl()); ?>/admin/staff/edit/id/<?php print($employee->getId()); ?>"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_edit.png" /></a>
                                                    <a title="<?php echo $this->translate("Delete");?>" href="<?php print($this->baseUrl()); ?>/admin/staff/delete/id/<?php print($employee->getId()); ?>" class="form-data-delete"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_drop.png" /></a>
                                                </td>
                                            </tr>
                                        <?php } ?>
                                    <?php } ?>

                                </tbody>
                            </table>

                        </div>
                    </div>
                    
                    
                    <?php if(count($this->systemLog)>0){?>
			<?php echo $this->partial('common/_pagination.phtml', array('paginationData' => $this->paggination)); ?>
                    <?php } ?>
                    
                </div>
            </div>
        </div>
    </div>
</div>
