<div id="main-content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    
                     <div class="btn-group">
                        <a href="#" id="table-edit_new" class="btn btn-danger">
                            <?php echo $this->translate("Add-New");?> <i class="fa fa-plus"></i>
                        </a>
                    </div>
                    
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 table-responsive m-t-20">
                            <table class="table table-hover table_obtor_data">
                                <thead class="no-bd">
                                    <tr>
                                        <th class="table_id"><strong><?php echo $this->translate("ID");?></strong></th>
                                        <th class="table_data"><strong><?php echo $this->translate("Title1");?></strong></th>
                                        <th class="table_data"><strong><?php echo $this->translate("Title2");?></strong></th>
                                        <th class="table_data"><strong><?php echo $this->translate("Title3");?></strong></th>
                                        <th class="table_data"><strong><?php echo $this->translate("Title4");?></strong></th>
                                        <th class="table_data"><strong><?php echo $this->translate("Title5");?></strong></th>
                                        <th class="table_data"><strong><?php echo $this->translate("Title6");?></strong></th>
                                        <th class="text-center data_table_action"><strong><?php echo $this->translate("Actions");?></strong></th>
                                    </tr>
                                </thead>
                                <tbody class="no-bd-y">

                               
                                            <tr>
                                                <td>
                                                    <a title="<?php echo $this->translate("View");?>" href="<?php print($this->baseUrl()); ?>/admin/test/view/id/1">
                                                    1
                                                    </a>
                                                </td>
                                                <td>some text</td>
                                                <td>some text</td>
                                                <td>some text</td>
                                                <td>some text</td>
                                                
                                               <td>some text</td>
                                                <td>some text</td>
                                                
                                                <td class="text-center">
                                                    <a title="<?php echo $this->translate("Edit");?>" href="#"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_edit.png" /></a>
                                                    <a title="<?php echo $this->translate("Delete");?>" href="#" class="form-data-delete"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_drop.png" /></a>
                                                </td>
                                            </tr>
                                            
                                            <tr>
                                                <td>
                                                    <a title="<?php echo $this->translate("View");?>" href="<?php print($this->baseUrl()); ?>/admin/test/view/id/1">
                                                    1
                                                    </a>
                                                </td>
                                                <td>some text</td>
                                                <td>some text</td>
                                                <td>some text</td>
                                                <td>some text</td>
                                                
                                               <td>some text</td>
                                                <td>some text</td>
                                                
                                                <td class="text-center">
                                                    <a title="<?php echo $this->translate("Edit");?>" href="#"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_edit.png" /></a>
                                                    <a title="<?php echo $this->translate("Delete");?>" href="#" class="form-data-delete"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_drop.png" /></a>
                                                </td>
                                            </tr>
                                            
                                            <tr>
                                                <td>
                                                    <a title="<?php echo $this->translate("View");?>" href="<?php print($this->baseUrl()); ?>/admin/test/view/id/1">
                                                    1
                                                    </a>
                                                </td>
                                                <td>some text</td>
                                                <td>some text</td>
                                                <td>some text</td>
                                                <td>some text</td>
                                                
                                               <td>some text</td>
                                                <td>some text</td>
                                                
                                                <td class="text-center">
                                                    <a title="<?php echo $this->translate("Edit");?>" href="#"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_edit.png" /></a>
                                                    <a title="<?php echo $this->translate("Delete");?>" href="#" class="form-data-delete"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_drop.png" /></a>
                                                </td>
                                            </tr>
                                            
                                            
                                            <tr>
                                                <td>
                                                    <a title="<?php echo $this->translate("View");?>" href="<?php print($this->baseUrl()); ?>/admin/test/view/id/1">
                                                    1
                                                    </a>
                                                </td>
                                                <td>some text</td>
                                                <td>some text</td>
                                                <td>some text</td>
                                                <td>some text</td>
                                                
                                               <td>some text</td>
                                                <td>some text</td>
                                                
                                                <td class="text-center">
                                                    <a title="<?php echo $this->translate("Edit");?>" href="#"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_edit.png" /></a>
                                                    <a title="<?php echo $this->translate("Delete");?>" href="#" class="form-data-delete"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_drop.png" /></a>
                                                </td>
                                            </tr>
                                            
                                            
                                            <tr>
                                                <td>
                                                    <a title="<?php echo $this->translate("View");?>" href="<?php print($this->baseUrl()); ?>/admin/test/view/id/1">
                                                    1
                                                    </a>
                                                </td>
                                                <td>some text</td>
                                                <td>some text</td>
                                                <td>some text</td>
                                                <td>some text</td>
                                                
                                               <td>some text</td>
                                                <td>some text</td>
                                                
                                                <td class="text-center">
                                                    <a title="<?php echo $this->translate("Edit");?>" href="#"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_edit.png" /></a>
                                                    <a title="<?php echo $this->translate("Delete");?>" href="#" class="form-data-delete"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_drop.png" /></a>
                                                </td>
                                            </tr>
                                        

                                </tbody>
                            </table>

                        </div>
                    </div>
                    
                    
                    <!-- The pagination comes here... -->
                    
                </div>
            </div>
        </div>
    </div>
</div>
