   <div id="main-content">
            
            <div class="row">
                <div class="col-md-12">
            
                    
                    
                    <div class="panel panel-default">
                        
                        <div class="panel-heading">
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
           
                </div>
                   
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <form id="form_professional_experience" name="form_professional_experience" role="form" method="post" class="form-horizontal">
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Company-Name");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <p><?php print($this->professionalExperienceInfo->getCompanyName());?></p>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Job-Title");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <p><?php print($this->professionalExperienceInfo->getJobTitle());?></p>
                                            
                                            </div>
                                        </div>
                                        
                                         <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("From-Date");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <p><?php print($this->professionalExperienceInfo->getFromDate());?></p>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("To-Date");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <p><?php print($this->professionalExperienceInfo->getToDate());?></p>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Comments");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <p><?php print($this->professionalExperienceInfo->getComments());?></p>
                                            </div>
                                        </div>
                                        
                                   
                                        
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    
                    
                </div>
            </div>
            
                        
            
                        
        </div>
<script src="<?php print($this->baseUrl());?>/assets/validator/admin/professional-experience.js"></script>