   <div id="main-content">
            
            <div class="row">
                <div class="col-md-12">
            
                    
                    
                    <div class="panel panel-default">
                   
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <form id="form_lead" name="form_lead" role="form" method="post" class="form-horizontal">
                                        
                                        <div class="form-group">
                                        <label class="form-label"><strong><?php echo $this->translate("Attachment-Csv-file");?></strong>
                                        </label>
                                        <div class="controls">
                                            <input class="form-control normal_input" type="file" id="txtAttachment" name="txtAttachment">
                                        </div>
                                    </div>
                                        
                                        
                                        
                                   
                                        <div class="form-group text-left">
                                            <button class="btn btn-blue" type="submit" name="Submit" id="Submit"><?php echo $this->translate("Submit");?></button>
                                            <button type="reset" class="btn btn-default"><?php echo $this->translate("Cancel");?></button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    
                    
                </div>
            </div>
            
                        
            
                        
        </div>
<script src="<?php print($this->baseUrl());?>/assets/validator/admin/lead.js"></script>