   <div id="main-content">
            
            <div class="row">
                <div class="col-md-12">
            
                    
                    
                    <div class="panel panel-default">
                        
                        <div class="panel-heading">
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
           
                </div>
                   
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-5">
                                    <form id="form_professional_experience" name="form_professional_experience" role="form" method="post" class="form-horizontal">
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Company-Name");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <input parsley-minlength="3" class="form-control" type="text" name="txtCompanyName" id="txtCompanyName" value="<?php print($this->professionalExperienceInfo->getCompanyName());?>"/>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Job-Title");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <input parsley-minlength="3" class="form-control" type="text" name="txtJobTitle" id="txtJobTitle" value="<?php print($this->professionalExperienceInfo->getJobTitle());?>"/>
                                            </div>
                                        </div>
                                        
                                         <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("From-Date");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <input parsley-minlength="3" class="form-control pickadate" type="text" name="txtFromDate" id="txtFromDate" value="<?php print($this->professionalExperienceInfo->getFromDate());?>"/>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("To-Date");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <input parsley-minlength="3" class="form-control pickadate" type="text" name="txtToDate" id="txtToDate" value="<?php print($this->professionalExperienceInfo->getToDate());?>"/>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Comments");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <textarea class="form-control" type="text" name="txtComments" id="txtComments"><?php print($this->professionalExperienceInfo->getComments());?></textarea>
                                            </div>
                                        </div>
                                        
                                   
                                        <div class="form-group text-left">
                                            <button class="btn btn-blue" type="submit" name="Submit" id="Submit"><?php echo $this->translate("Submit");?></button>
                                            <button type="reset" class="btn btn-default"><?php echo $this->translate("Cancel");?></button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    
                    
                </div>
            </div>
            
                        
            
                        
        </div>
<script src="<?php print($this->baseUrl());?>/assets/validator/admin/professional-experience.js"></script>