   <div id="main-content">
            
            <div class="row">
                <div class="col-md-12">
            
                    
                    
                    <div class="panel panel-default">
                        
                        <div class="panel-heading">
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
           
                </div>
                   
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="view_information">
                                            <ul>
                                                <li>
                                                    <span><?php echo $this->translate("Company-Name");?></span>
                                                   : <?php print($this->professionalExperienceInfo->getCompanyName());?>
                                                    <div class="clear"></div>
                                                </li>
                                                <li>
                                                    <span><?php echo $this->translate("Job-Title");?></span>
                                                   : <?php print($this->professionalExperienceInfo->getJobTitle());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                 <li>
                                                    <span><?php echo $this->translate("From-Date");?></span>
                                                   : <?php print($this->professionalExperienceInfo->getFromDate());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("To-Date");?></span>
                                                   : <?php print($this->professionalExperienceInfo->getToDate());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Comments");?></span>
                                                   : <?php print($this->professionalExperienceInfo->getComments());?>
                                                    <div class="clear"></div>
                                                </li>

                                                
                                            </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    
                    
                </div>
            </div>
            
                        
            
                        
        </div>
<script src="<?php print($this->baseUrl());?>/assets/validator/admin/professional-experience.js"></script>
