<div id="main-content">

    <div class="row">
        <div class="col-md-12">



            <div class="panel panel-default">

                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-5">
                            <form id="form_attendance" name="form_attendance" role="form" method="get" class="form-horizontal" action="<?php print($this->baseUrl());?>/admin/leave/index/">
                                
                                <div class="form-group">
                                    <label class="form-label"><strong><?php echo $this->translate("Employee"); ?></strong></label>
                                    <div class="input-icon right">
                                        <i class="fa"></i>
                                       <select parsley-minlength="3" class="form-control" name="employee" id="employee">
                                        <option value="">-- select employee --</option>
                                        <?php foreach ($this->employeeInfo As $empIndex => $employee) { ?>
                                            <option value="<?php print($employee->getId()); ?>"><?php print($employee->getNameWithInitials()); ?></option>
                                        <?php } ?>
                                    </select>
                                    </div>
                                </div>
                                
                                
                                <div class="form-group">
                                    <label class="form-label"><strong><?php echo $this->translate("From-Date"); ?></strong></label>
                                    <div class="input-icon right">
                                        <i class="fa"></i>
                                        <input parsley-minlength="3" class="form-control" type="text" name="leave-from" id="leave-from"/>
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="form-label"><strong><?php echo $this->translate("To-Date"); ?></strong></label>
                                    <div class="input-icon right">
                                        <i class="fa"></i>
                                        <input parsley-minlength="3" class="form-control" type="text" name="leave-to" id="leave-to"/>
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("App-Status");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                 <select parsley-minlength="3" class="form-control" name="status" id="status">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <option value="Approved"><?php echo $this->translate("Approved"); ?></option>
                                                    <option value="Rejected"><?php echo $this->translate("Rejected"); ?></option>
                                                    <option value="Canceled"><?php echo $this->translate("Canceled"); ?></option>
                                                    <option value="Pending"><?php echo $this->translate("Pending"); ?></option>
                                                </select>
                                            </div>
                                        </div>
                              
                                

                        
                                <div class="form-group text-left">
                                    <button class="btn btn-blue" type="submit" name="Submit" id="Submit"><?php echo $this->translate("Search"); ?></button>
                                    <button type="reset" class="btn btn-default"><?php echo $this->translate("Cancel"); ?></button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>



        </div>
    </div>




</div>