<div class="panel panel-signin">
                <div class="panel-body">

                 <h1>An error occurred</h1>
                    
                    <div class="mb30"></div>
                    
<form name="login-form" id="login-form" method="post">
                
                        
<h2><?php echo $this->message ?></h2>

<?php if ('development' == APPLICATION_ENV): ?>

<h3>Exception information:</h3>
<p><b>Message:</b> <?php echo $this->exception->getMessage() ?></p>

<h3>Stack trace:</h3>
<pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

<h3>Request Parameters:</h3>
<pre><?php echo var_export($this->request->getParams(), true) ?>
  </pre>
<?php endif ?>
                                            
                    </form>
                    
                    
                </div><!-- panel-body -->
               
            </div><!-- panel -->

