   <div id="main-content">
            
            <div class="row">
                <div class="col-md-12">
            
                    
                    
                    <div class="panel panel-default">
                        
                        <div class="panel-heading">
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
           
                </div>
                   
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-12">
                                    <form id="form_education_qualification" name="form_education_qualification" role="form" method="post" class="form-horizontal">
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Level");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <p><?php print($this->edualificationInfo->getLevel());?></p>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Institute");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <p><?php print($this->edualificationInfo->getInstitute());?></p>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Major-Specialization");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <p><?php print($this->edualificationInfo->getMajorSpecialization());?></p>
                                                
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Year");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <p><?php print($this->edualificationInfo->getYear());?></p>
                                            </div>
                                        </div>
                                        
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Gpa");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <p><?php print($this->edualificationInfo->getGpa());?></p>
                                            </div>
                                        </div>
                                        
                                        
                                        
                                         <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Start-Date");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <p><?php print($this->edualificationInfo->getStartDate());?></p>
                                            </div>
                                        </div>
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("End-Date");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <p><?php print($this->edualificationInfo->getEndDate());?></p>
                                            </div>
                                        </div>
                                        
                                      
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    
                    
                </div>
            </div>
            
                        
            
                        
        </div>