<div id="main-content">

    <div class="row">
        <div class="col-md-12">


           
                <div class="panel panel-default">
                    
                    <div class="panel-heading">
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
           
                </div>

                    <div class="panel-body">


                        <div class="row">
                            <div class="col-md-6">
                                
                               <div class="col-md-12 col-sm-12 col-xs-12 m-b-10">
                                   
                                   <div class="view_information">
                                     
                                       
                                              <ul>
                                                <li>
                                                    <span><?php echo $this->translate("Task-Name");?></span>
                                                   : <?php print($this->taskInformation->getName());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                 <li>
                                                    <span><?php echo $this->translate("Assigned-To");?></span>
                                                   : <?php print($this->getEmployee($this->taskInformation->getAssignedTo())->getNameWithInitials()); ?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Task-Type");?></span>
                                                   : <?php print($this->taskInformation->getTaskType());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                 <li>
                                                    <span><?php echo $this->translate("Task-Progress");?></span>
                                                   : <?php print($this->taskInformation->getProgress());?>%
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                 <li>
                                                    <span><?php echo $this->translate("Hours-Spent");?></span>
                                                   : <?php print($this->taskInformation->getHoursSpent());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                 <li>
                                                    <span><?php echo $this->translate("End-Date");?></span>
                                                   : <?php print($this->taskInformation->getEndDate());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                
                                              </ul>
                                       
                                       
                                    </div>
                                  
                               </div>
                            </div>
                            
                            
                            <div class="col-md-6">
                                
                               <div class="col-md-12 col-sm-12 col-xs-12 m-b-10">
                                   
                                   <div class="view_information">
                                     <ul>
                                                <li>
                                                    <span><?php echo $this->translate("Project-Name");?></span>
                                                   : <?php print($this->getProject($this->taskInformation->getProjectId())->getProjectName());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                
                                                 <li>
                                                    <span><?php echo $this->translate("Current-Status");?></span>
                                                   : <?php print($this->taskInformation->getCurrentStatus());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                 <li>
                                                    <span><?php echo $this->translate("Task-Priority");?></span>
                                                   : <?php print($this->taskInformation->getPriority());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                 <li>
                                                    <span><?php echo $this->translate("Allocated-Hours");?></span>
                                                   : <?php print($this->taskInformation->getAllocatedHours());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Start-Date");?></span>
                                                   : <?php print($this->taskInformation->getStartDate());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                   
                                                
                                              </ul>
                                    </div>
                                  
                               </div>
                            </div>
                            
                            <div class="col-md-12">
                                
                               <div class="col-md-12 col-sm-12 col-xs-12 m-b-10">
                                   
                                   <div class="view_information">
                                  
                                       <ul>
                                           <li>
                                                    <span><?php echo $this->translate("Task-Description");?></span>
                                                   : <?php print($this->taskInformation->getDescription());?>
                                                    <div class="clear"></div>
                                                </li>
                                       </ul>
                                       
                                   </div>
                               </div>
                            </div>
                            
                            
                            
                       
                        </div>
                        
                        
                        
                          <h5 class="panel-title"><strong><?php echo $this->translate("Update-Task-Information");?></strong></h5>
                                
                          <div class="col-md-12 col-sm-12 col-xs-12 m-b-20">
                          <div class="row border-top">
                                <div class="col-md-5 col-sm-12 col-xs-12 m-t-20">
                                    <form id="form_project" name="form_project" role="form" method="post" class="form-horizontal" action="">
                                        
                                        
                                        
                                        
                                       <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Assigned-To");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <select  class="form-control" name="txtAssignedTo" id="txtAssignedTo">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <?php foreach($this->employeeInfo As $eIndex=>$employee){?>
                                                    <option value="<?php print($employee->getId());?>" <?php if($this->taskInformation->getAssignedTo() == $employee->getId()){?> selected="selected" <?php } ?>><?php print($employee->getNameWithInitials());?> (#<?php print($employee->getEmployeeNumber());?>)</option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                        
                                        
                                        <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Current-Status");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <select  class="form-control" name="txtCurrentStatus" id="txtCurrentStatus">
                                                    <option value="">--<?php echo $this->translate("select"); ?>--</option>
                                                    <?php foreach($this->taskStatusList As $tIndex=>$taskStatus){?>
                                                    <option value="<?php print($taskStatus);?>" <?php if($this->taskInformation->getCurrentStatus() == $taskStatus){?> selected="selected" <?php }?>><?php print($this->translate($taskStatus));?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>
                                        
                                          <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Task-Progress");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <input parsley-minlength="3" class="form-control" type="text" name="txtProgress" id="txtProgress" value="<?php print($this->taskInformation->getProgress());?>"/>
                                            </div>
                                        </div>
                                       
                               
                                       
                                        
                                       
                                        
                                   
                                        <div class="form-group text-left">
                                            <button class="btn btn-blue" type="submit" name="Submit" id="Submit"><?php echo $this->translate("Submit");?></button>
                                            <button type="reset" class="btn btn-default"><?php echo $this->translate("Cancel");?></button>
                                        </div>
                                    </form>
                                </div>
                            </div>
                              </div>
                        
                    </div>
                    
                    
                    
                    
                    
                </div>
          

        </div>
    </div>




</div>