<div id="main-content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 table-responsive m-t-20">
                            <table class="table table-bordered table_obtor_data table-hover">
                                <thead class="no-bd">
                                    <tr>
                                        <th class="table_id table_head"><?php echo $this->translate("ID");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Client-Name");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Date");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Payment-Method");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Description");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Amount-In");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Fees");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Amount-Out");?></th>
                                        <th class="text-center table_head data_table_action"><?php echo $this->translate("Actions");?></th>
                                    </tr>
                                </thead>
                                <tbody class="no-bd-y">

                                <?php if($this->transactions){?>
			          <?php foreach($this->transactions As $index=>$transaction){?>
                                            <tr>
                                                <td>
                                                  <?php print($transaction->getId());?>
                                                </td>
                                                <td><?php print($transaction->getClient()->getCompanyname());?></td>
                                                <td><?php print($transaction->getDate());?></td>
                                                <td><?php print($transaction->getGateway()->getName());?></td>
                                                <td><?php print($transaction->getDescription());?></td>
                                               <td><?php print($transaction->getAmountIn());?></td>
                                               <td><?php print($transaction->getFees());?></td>
                                               <td><?php print($transaction->getAmountOut());?></td>
                                                
                                                <td class="text-center">
                                                   <a title="<?php echo $this->translate("Edit");?>" href="<?php print($this->baseUrl());?>/admin/billing/edit-transactions/id/<?php print($transaction->getId());?>"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_edit.png" /></a>
                                                    <a title="<?php echo $this->translate("Delete");?>" href="<?php print($this->baseUrl());?>/admin/billing/delete-transaction/id/<?php print($transaction->getId());?>" class="form-data-delete"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_drop.png" /></a>
                                                </td>
                                            </tr>
                                            
                                        <?php } ?>
			   <?php } else {?>
                                            <tr>
                                                <td colspan="9" class="table_data_not_found"><?php echo $this->translate("Records-Not-Available");?></td>
                                            </tr>
                                    <?php } ?>
                                        

                                </tbody>
                            </table>

                        </div>
                    </div>
                    
                    <?php if(count($this->transactions)>0){?>
			<?php echo $this->partial('common/_pagination.phtml', array('paginationData' => $this->paggination)); ?>
                    <?php } ?>
                    <!-- The pagination comes here... -->
                    
                </div>
            </div>
        </div>
    </div>
</div>
