                    <!-- Navigation info -->
                    <ul id="nav-info" class="clearfix">
                        <li><a href="index.html"><i class="icon-home"></i></a></li>
                        <li><a href="javascript:void(0)">Pages</a></li>
                        <li class="active"><a href="">Blank</a></li>
                    </ul>
                    <!-- END Navigation info -->

                    <!-- Your Content -->
                    
                    <h3 class="page-header page-header-top">Clients Profile</h3>
                      
                     <div class="row-fluid">
                     <form action="/admin_stfo/clientssummary.php" method="get">
<p>Active Client: <select name="userid" onchange="submit();"><option value="127">1st Call Phils Autos - Phil Walton</option>
<option value="197">5 Star Order - Jahangir Uddin</option>
<option value="117">A and M Group Services - Matthew Siron</option>
<option value="198">A1 Agency Limited - Liam Robinson</option>
<option value="218">All Weather Gardening Services - Andrew Waterworth</option>
<option value="228">andersklattrare - Erik Wilson</option>
<option value="99">Andrew James Kitchens &amp; Bedrooms Ltd - Andrew Lee</option>
<option value="215">Andrew Wilkinson Landscape Designs LTD - Andrew Wilkinson</option>
<option value="159">AR Smart Repairs - Adrian Roebuck</option>
<option value="231">Archdale Plumbing and Heating - Dean Archdale</option>
<option value="202">Arthur Shaw (Conisbrough) Ltd - Susan Shaw</option>
<option value="91">Ascot Energy Servics - Justyna Turzynska</option>
<option value="216">Athena Beauty - Lynnette Clarke</option>
<option value="242">Atkinson Heating &amp; Maintenance Ltd - Spencer Atkinson</option>
<option value="245">Autofix Garage Services  - Darren Ingham </option>
<option value="189">Barden &amp; Hall Limited - Andrew Barden</option>
<option value="241">bed factory outlet - Scott Kilner</option>
<option value="143">BeYourOwnLawyer - Robert Murdoch</option>
<option value="108">Big Now Ltd - Andrew Conlon</option>
<option value="193">Bizzy Bees  - Alex leigh</option>
<option value="178">Blue Moon Trading Company - John Moss</option>
<option value="235">Bradway Removals - mathew edis</option>
<option value="85">BuffersCleaning - Pauline Geldart</option>
<option value="179">Chemtrailworld - Jason Nota</option>
<option value="248">Christchurch Cabs - Stewart Walker</option>
<option value="160">Clifton McDonald S.L. - Clifton McDonald S.L. </option>
<option value="75">COR Asset Pool Ltd. - Laura Kowalewski </option>
<option value="150">Croftnook Cottage - Susan Edinboro</option>
<option value="183">Cuts and Co - Ann Marie Cutts</option>
<option value="243">David Adamson Accountants - David Adamson</option>
<option value="174">Delta Interiors - Christopher Johnstone</option>
<option value="230">desert off road  specialist 4x4 center - michael scarborough</option>
<option value="97">Didsbury Flooring Co - David Neil Price</option>
<option value="225">DJC Joinery - David Charlton</option>
<option value="180">DM Electrical - Daniel McHugh</option>
<option value="78">Dunbar House Ltd - Rajan Bhabra</option>
<option value="135">EGS Motors LTD - John Stones</option>
<option value="125">Emerald Hair and Beauty - Emily Tasker</option>
<option value="156">Exclusive Beds - Hassan Daji</option>
<option value="184">Expression Hair - Sue Rodgers</option>
<option value="220">Foxy Butlers LTD - Laura Dean</option>
<option value="190">Fred Moon Plumbing - Fred  Moon</option>
<option value="103">Go-Dollars Advisors, S.A. - Grace Loaiza</option>
<option value="233">green gas - simon hollingworth</option>
<option value="252">Green Tea (Chinease Take away) - Peng Lang</option>
<option value="255">Greenfield Interiors - Julie Greenfield</option>
<option value="168">Greengates Pet Store - Ben Salfarlie</option>
<option value="133">Hadfields  - James Crabtree</option>
<option value="123">Hair@Pro-Style - Lesley Lockwood</option>
<option value="105">Halifax Snooker Club LTD - Tony Ioannou</option>
<option value="217">Housemaid 911 Ltd - Nicola Kildunne</option>
<option value="173">Huddersfield MOT Centre - Linden Cahill</option>
<option value="93">Impact Signs - Richard Douthwaite</option>
<option value="138">Intafaze Entertainments - Andrew wilkinson</option>
<option value="94">J C Interiors ltd - Jacky Cornforth</option>
<option value="212">Jacqeline Guitart Interior Design - Jacqueline Guitart</option>
<option value="221">JC Dancewear - Claire Shaw</option>
<option value="244">JK Decoration - John  King</option>
<option value="256">John Lovett Upholstery - John Slaney</option>
<option value="152">Junction 26 Beds - Amy Pinfield</option>
<option value="157">Kestrel Property Services - Marc Gable</option>
<option value="224">Kirby's Removals - Sandra Maude</option>
<option value="96">Klip Designer Hair - Anne  Telford-Taylor</option>
<option value="247">KP Classic &amp; Modern LTD - Alex Barry</option>
<option value="6">Kriptik International - Tim Maynard</option>
<option value="151">La Bonne Cuisine - John Allen</option>
<option value="90">Leeds Auto Paint Supplies - Stephen Williamson</option>
<option value="101">LG Hairdressers - Anthony Huggins</option>
<option value="146">Linley AutoBody Specialists LTD - Dean Linley</option>
<option value="128">London Pullman Tours LTD - James Baxter</option>
<option value="136">los flamingos estates - Jacob Voch</option>
<option value="186">MC Carpets &amp; Furniture Stores Ltd - Martyn Thompson</option>
<option value="147">McCarthy - Martin MacCarthy</option>
<option value="106">Mick Hope Imprinted Concrete - Mick  Hope</option>
<option value="86">Millhouses Plans Ltd - Sue Humphrey</option>
<option value="107">Monara IT UK Ltd - Tim Maynard</option>
<option value="126">Monara IT UK Ltd - Peter Humphrey</option>
<option value="195">MRConstruction - Mark Cochrane</option>
<option value="232">MW Contracts and hire ltd - christopher Rudzki</option>
<option value="213">Netherton Community Centre - Stephen Knight</option>
<option value="98">New Look Interiors - David Donlon</option>
<option value="77">Nimon Trading - Nigel Woolf</option>
<option value="192">NJT Electrical Wholesalers LLP - Brian Beilby</option>
<option value="258" selected="selected">Nottingham Catering - Benjamin Collington</option>
<option value="176">Pappleyard Plastering - Patrick Appleyard</option>
<option value="122">Pay As You Go Pa - Nicola Hopkinson</option>
<option value="194">Penningtons Sporting Arms &amp; Ammunition - Tracy Brown</option>
<option value="246">Philip Gordon Photography - Philip  Gordon Pitts</option>
<option value="239">pm carpets - paul lobley</option>
<option value="214">Prestige Imports - Nigel Jones</option>
<option value="149">Providence Chartering Services LLP - Alex Booth</option>
<option value="144">Ravensthorpe home centre - Mohammed Nawaz</option>
<option value="187">Reshape Accident Repair Centre Limited - Ricky Kennedy</option>
<option value="121">Rolands Croft Guesthouse - Peter Sutton</option>
<option value="236">selston timber - alan spencer</option>
<option value="153">Shawcross Printers - Jerry Green</option>
<option value="175">Signs &amp; Print - Peter Szumowski</option>
<option value="234">Slips Deli - Lisa Brewer</option>
<option value="196">Solar Sun 4 Life UK - Solar Sun 4 Life UK</option>
<option value="130">Sparkilly Studios Ltd - Mark Pacey</option>
<option value="7">SS Building Company Ltd. - Steven Seng</option>
<option value="240">Staples Autos LTD - Frank Staples</option>
<option value="163">Stephen Hairdressing - Stephen Jones</option>
<option value="112">Suite Centre Leeds LTD - Howard Symonds</option>
<option value="227">Taylors Home Brew - Mark  Taylor</option>
<option value="142">test - Peter Humphrey</option>
<option value="92">The Clock Hotel - Adeel Amjad</option>
<option value="226">THE DEVIL MADE ME DO IT - ROBERT CLEMENTS</option>
<option value="219">The Dressing Room - Jane  Sanders</option>
<option value="88">The End Hairdressers - Alex  Thompson</option>
<option value="83">The Home Improvement Co - Paul Todd</option>
<option value="110">The Leeds Sofa Company - Steve Rowlands</option>
<option value="162">The Pest Professor Ltd - Richard Mcdonald</option>
<option value="204">The Scaffold Company Northern - Paul Harling</option>
<option value="158">The Wellness Clinic - Sian Buchanan</option>
<option value="172">Tigers Eye - Ian Shelmerdine</option>
<option value="223">Tiny Toes - Pete - Claire Zanetti</option>
<option value="199">Total Heat Systems Limited - Andrew Smith</option>
<option value="188">Total Image - Andrew Russell</option>
<option value="203">Triangle Menswear - Mark Barrowcliffe</option>
<option value="257">Trident security Solutions LTD - Roman Yurichuk</option>
<option value="161">uneek  impressions - John Campbell</option>
<option value="177">Union Plumbing and Heating - Oliver Scott</option>
<option value="200">Universal Appliances - Sam Moore</option>
<option value="169">UPVC Trade Centre Limited - Stephen Stanton</option>
<option value="165">Valkry Corporation - Michael Brown</option>
<option value="201">Vectra Man - Anthony Morgan</option>
<option value="170">Vision Hair and Beauty - hanna Amenyeanu</option>
<option value="114">Wakefield Restorations - Peter Wakefield</option>
<option value="8">Woolf Investments - Nigel Woolf</option>
<option value="167">Wrapture Vehicle Wraps - Philip Moran</option>
<option value="4">Zero Identity - Carl Asaba</option>
</select> <input value="Go" type="submit" class="btn btn-small"></p>
</form>
                     </div> 
                        
                            
                         <!-- Tabs -->
                    <div class="push">
                      
                        <ul class="nav nav-tabs">
                            <li class="active"><a href="javascript:void(0)">Summary</a></li>
                            <li><a href="javascript:void(0)">Profile</a></li>
                            <li><a href="javascript:void(0)">Contacts</a></li>
                            <li><a href="javascript:void(0)">Products/Services</a></li>
                            <li><a href="javascript:void(0)">Domains</a></li>
                            <li><a href="javascript:void(0)">Billable</a></li>
                            <li><a href="javascript:void(0)">Items</a></li>
                            <li><a href="javascript:void(0)">Invoices</a></li>
                            <li><a href="javascript:void(0)">Transactions</a></li>
                            <li><a href="javascript:void(0)">Emails</a></li>
                            <li><a href="javascript:void(0)">Notes(0)</a></li>
                            <li><a href="javascript:void(0)">Log</a></li>
                        </ul>
                    </div>
                    <!-- END Tabs -->
                    <div class="row-fluid tab_content">
                     	<div class="span4"><div style="font-size:18px;">#258 - Benjamin Collington</div></div> 
                     	<div class="span8">
                            <div class="clientsummaryactions">
Exempt from Tax: <span id="taxstatus" class="csajaxtoggle" style="text-decoration:underline;cursor:pointer"><strong class="textred">No</strong></span>
&nbsp;&nbsp;
Auto CC Processing: <span id="autocc" class="csajaxtoggle" style="text-decoration:underline;cursor:pointer"><strong class="textgreen">Yes</strong></span>
&nbsp;&nbsp;
Send Overdue Reminders: <span id="overduenotices" class="csajaxtoggle" style="text-decoration:underline;cursor:pointer"><strong class="textgreen">Yes</strong></span>
&nbsp;&nbsp;
Apply Late Fees: <span id="latefees" class="csajaxtoggle" style="text-decoration:underline;cursor:pointer"><strong class="textgreen">Yes</strong></span>
</div>
                        </div> 
                        
                        <div class="row-fluid" style="margin-top:2%;">
                        <!-- main 3 colum ariya -->
                        
                        		 <!--  colum1  -->
                            <div class="span4">
                            	<!--1-->
                            	<div class="clientssummarybox">
                                <div class="title">Clients Information</div>
                                <table class="clientssummarystats" cellpadding="2" cellspacing="0">
                                <tbody><tr><td width="110">First Name</td><td>Benjamin</td></tr>
                                <tr class="altrow"><td>Last Name</td><td>Collington</td></tr>
                                <tr><td>Company Name</td><td>Nottingham Catering</td></tr>
                                <tr class="altrow"><td>Email Address</td><td>chef-dsf@hotmail.com</td></tr>
                                <tr><td>Address 1</td><td>6 Gordon Rise</td></tr>
                                <tr class="altrow"><td>Address 2</td><td></td></tr>
                                <tr><td>City</td><td>Nottingham</td></tr>
                                <tr class="altrow"><td>State/Region</td><td>Nottinghamshire</td></tr>
                                <tr><td>Postcode</td><td>NG3 5GB</td></tr>
                                <tr class="altrow"><td>Country</td><td>GB - United Kingdom</td></tr>
                                <tr><td>Phone Number</td><td>07828988162</td></tr>
                                </tbody></table>
                                <ul>
                                <li><a href="#" class="box_link" ><img src="<?php print($this->baseUrl());?>/content/admin/img/resetpw.png" border="0" align="absmiddle"> Reset &amp; Send Password</a>
                                </li><li><a href="#" onclick="#" class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/offlinecc.png" border="0" align="absmiddle"> Credit Card Information</a>
                                </li><li><a href="#" class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/clientlogin.png" border="0" align="absmiddle"> Login as Client</a>
                                </li></ul>
                                </div>
                                
                                <!--2-->
                                <div class="clientssummarybox">
                                <div class="title">Contacts/Sub-Accounts</div>
                                <table class="clientssummarystats" cellpadding="2" cellspacing="0">
                                <tbody><tr><td align="center">No additional contacts setup</td></tr>
                                </tbody></table>
                                <ul>
                                <li><a href=""><img src="<?php print($this->baseUrl());?>/content/admin/img/clientsadd.png" border="0" align="absmiddle"> Add Contact</a>
                                </li></ul>
                                </div>
                                <!--3-->
                                <div class="clientssummarybox">
                                <div class="title">Other Information</div>
                                <table class="clientssummarystats" cellpadding="2" cellspacing="0">
                                <tbody><tr><td width="110">Status</td><td>Active</td></tr>
                                <tr class="altrow"><td>Client Group</td><td>None</td></tr>
                                <tr><td>Signup Date</td><td>23/09/2013</td></tr>
                                <tr class="altrow"><td>Client For</td><td>1 Months</td></tr>
                                <tr><td width="110">Last Login</td><td>No Login Logged</td></tr>
                                </tbody></table>
                                </div>
                                
                            
                            </div>
                         	<!--  colum1 END  -->
                            <!--  colum2  -->
                             <div class="span4">
                             	<!--1-->
                                <div class="clientssummarybox">
                                <div class="title">Invoices/Billing</div>
                                <table class="clientssummarystats" cellpadding="2" cellspacing="0">
                                <tbody><tr><td width="110">Paid</td><td>1 (£81.58    GBP)</td></tr>
                                <tr class="altrow"><td>Unpaid/Due</td><td>0 (£0.00    GBP)</td></tr>
                                <tr><td>Cancelled</td><td>0 (0)</td></tr>
                                <tr class="altrow"><td>Refunded</td><td>0 (0)</td></tr>
                                <tr><td>Collections</td><td>0 (0)</td></tr>
                                <tr class="altrow"><td><strong>Income</strong></td><td><strong>£80.76    GBP</strong></td></tr>
                                <tr><td>Credit Balance</td><td>£0.00    GBP</td></tr>
                                </tbody></table>
                                <ul>
                                <li><a href="" class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/invoicesedit.png" border="0" align="absmiddle"> Create Invoice</a>
                                </li><li><a href="#" onclick="" class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/addfunds.png" border="0" align="absmiddle"> Create Add Funds Invoice</a>
                                </li><li><a href="#" onclick="" class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/ticketspredefined.png" border="0" align="absmiddle"> Generate Due Invoices</a>
                                </li><li><a href="" class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/billableitems.png" border="0" align="absmiddle"> Add Billable Item</a>
                                </li><li><a href="#" onclick="" class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/income.png" border="0" align="absmiddle"> Manage Credits</a>
                                </li><li><a href="" class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/quotes.png" border="0" align="absmiddle"> Create New Quote</a>
                                </li></ul>
                                </div>
                             	<!--2-->
                                <div class="clientssummarybox">
                                <div class="title">Files</div>
                                <table class="clientssummarystats" cellpadding="2" cellspacing="0">
                                <tbody><tr><td align="center">No files uploaded</td></tr>
                                </tbody></table>
                                <ul>
                                <li><a href="#" id="addfile"><img src="<?php print($this->baseUrl());?>/content/admin/img/add.png" border="0" align="absmiddle"> Add File</a>
                                </li></ul>
                                <div id="addfileform" style="display:none;">
                                <img src="<?php print($this->baseUrl());?>/content/admin/img/spacer.gif" height="4" width="1"><br>
                                <form method="post" action="clientssummary.php?userid=258&amp;action=uploadfile" enctype="multipart/form-data">
                                <input name="token" value="93a1cef13ed544eb3ee2405d093d41ee6f9d9edf" type="hidden">
                                <table class="clientssummarystats" cellpadding="2" cellspacing="0">
                                <tbody><tr><td width="40">Title</td><td class="fieldarea"><input name="title" style="width:90%" type="text"></td></tr>
                                <tr><td>File</td><td class="fieldarea"><input name="uploadfile" style="width:90%" type="file"></td></tr>
                                <tr><td></td><td class="fieldarea"><input name="adminonly" value="1" type="checkbox"> Admin Only &nbsp;&nbsp;&nbsp;&nbsp; <input value="Submit" type="submit"></td></tr>
                                </tbody></table>
                                </form>
                                </div>
                                </div>
                                <!--3-->
                                <div class="clientssummarybox">
                                <div class="title">Recent Emails</div>
                                <table class="clientssummarystats" cellpadding="2" cellspacing="0">
                                <tbody><tr class=""><td align="center">23/09/2013 13:04 - <a href="#" onclick="" class="textblack">Invoice Payment Confirmation</a></td></tr>
                                <tr class="altrow"><td align="center">23/09/2013 13:04 - <a href="#" onclick="" class="textblack">Invoice Payment Confirmation</a></td></tr>
                                <tr class=""><td align="center">23/09/2013 13:03 - <a href="#" onclick="" class="textblack">Domain Registration Confirmation</a></td></tr>
                                <tr class="altrow"><td align="center">23/09/2013 13:02 - <a href="#" onclick="" class="textblack">Order Confirmation</a></td></tr>
                                <tr class=""><td align="center">23/09/2013 13:02 - <a href="#" onclick="" class="textblack">Customer Invoice</a></td></tr>
                                </tbody></table>
                                </div>
                                
                             
                             </div>
                            
                            <!--  colum2 END  -->
                        	 <!--  colum3  -->
                             <div class="span4">
                             	<!--1-->
                             	<div class="clientssummarybox">
                                <div class="title">Products/Services</div>
                                <table class="clientssummarystats" cellpadding="2" cellspacing="0">
                                <tbody><tr><td width="140">Shared Hosting</td><td>0 (0 Total)</td></tr>
                                <tr class="altrow"><td>Reseller Hosting</td><td>0 (0 Total)</td></tr>
                                <tr><td>VPS/Server</td><td>0 (0 Total)</td></tr>
                                <tr class="altrow"><td>Product/Service</td><td>1 (1 Total)</td></tr>
                                <tr><td>Domains</td><td>1 (1 Total)</td></tr>
                                <tr class="altrow"><td>Accepted Quotes</td><td>0 (0 Total)</td></tr>
                                <tr><td>Support Tickets</td><td>0 (0 Total)</td></tr>
                                <tr class="altrow"><td>Affiliate Signups</td><td>0</td></tr>
                                </tbody></table>
                                <ul>
                                <li><a href="" class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/orders.png" border="0" align="absmiddle"> View Orders</a>
                                </li><li><a href="" class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/ordersadd.png" border="0" align="absmiddle"> Add New Order</a>
                                </li></ul>
                                </div>
                             	<!--2-->
                                <div class="clientssummarybox">
                                    <div class="title">Send Email</div>
                                    <form action="clientsemails.php?userid=258&amp;action=send&amp;type=general" method="post">
                                    <input name="token" value="93a1cef13ed544eb3ee2405d093d41ee6f9d9edf" type="hidden">
                                    <input name="id" value="258" type="hidden">
                                    <div align="center"><select name="messagename"><option selected="selected" value="newmessage">New Message</option><option value="Automated Password Reset">Automated Password Reset</option><option value="Client Signup Email">Client Signup Email</option><option value="Credit Card Expiring Soon">Credit Card Expiring Soon</option><option value="Order Confirmation">Order Confirmation</option><option value="Password Reset Confirmation">Password Reset Confirmation</option><option value="Quote Accepted">Quote Accepted</option><option value="Quote Accepted Notification">Quote Accepted Notification</option><option value="Quote Delivery with PDF">Quote Delivery with PDF</option><option value="Thompsons" style="background-color:#efefef">Thompsons</option></select> <input value="Go" class="btn btn-small" type="submit"></div>
                                    </form>
                                    </div>
                                    <!--3-->
                                    <div class="clientssummarybox">
                                    <div class="title">Other Actions</div>
                                    <ul>
                                    <li><a href="" class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/reports.png" border="0" align="absmiddle"> View Account Statement</a>
                                    </li><li><a href=""  class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/ticketsopen.png" border="0" align="absmiddle"> Open New Support Ticket</a>
                                    </li><li><a href=""  class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/ticketsother.png" border="0" align="absmiddle"> View all Support Tickets</a>
                                    </li><li><a href=""  class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/affiliates.png" border="0" align="absmiddle"> Activate as Affiliate</a>
                                    </li><li><a href="#"  class="box_link" onclick=""><img src="<?php print($this->baseUrl());?>/content/admin/img/clients.png" border="0" align="absmiddle"> Merge Clients Accounts</a>
                                    </li><li><a href="#"  class="box_link" onclick="" style="color:#000000;"><img src="<?php print($this->baseUrl());?>/content/admin/img/delete.png" border="0" align="absmiddle"> Close Clients Account</a>
                                    </li><li><a href="#"  class="box_link" onclick="" style="color:#CC0000;"><img src="<?php print($this->baseUrl());?>/content/admin/img/delete.png" border="0" align="absmiddle"> Delete Clients Account</a>
                                    </li></ul>
                                    </div>
                                    
                                    <div class="clientssummarybox">
                                    <div class="title">Admin Notes</div>
                                    <form method="post" action="">
                                    <input name="token" value="" type="hidden">
                                    <div align="center">
                                    <textarea name="adminnotes" rows="6" style="width:90%;"></textarea><br>
                                    <input value="Submit" class="btn" type="submit">
                                    </div>
                                    </form>
                                    </div>
                                
                             
                             </div>

                              <!--  colum3 END  -->
                              
                              
                         <!-- main colum ariya -->
                         </div>
                        
                        <div class="row-fluid">
                      		<table class="table table-hover">
                        <thead>
                            <tr>
                                <th class="span1 text-center" data-toggle="tooltip" title="Toggle all!"><input type="checkbox" id="check3-all" name="check3-all"></th>
                                <th class="span1 text-center">#</th>
                                <th>Username</th>
                                <th class="hidden-phone"><i class="icon-envelope-alt"></i> Email</th>
                                <th class="hidden-phone">Firstname</th>
                                <th class="hidden-phone">Lastname</th>
                                <th class="span3 text-center"><i class="icon-bolt"></i> Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="span1 text-center"><input type="checkbox" id="check3-td1" name="check3-td1"></td>
                                <td class="span1 text-center">1</td>
                                <td><a href="javascript:void(0)">username1</a></td>
                                <td class="hidden-phone">user1@example.com</td>
                                <td class="hidden-phone">Name</td>
                                <td class="hidden-phone">Last</td>
                                <td class="span3 text-center">
                                    <div class="btn-group">
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Details" class="btn btn-mini btn-info"><i class="icon-info-sign"></i></a>
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Edit" class="btn btn-mini btn-success"><i class="icon-pencil"></i></a>
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Delete" class="btn btn-mini btn-danger"><i class="icon-remove"></i></a>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="span1 text-center"><input type="checkbox" id="check3-td2" name="check3-td2"></td>
                                <td class="span1 text-center">2</td>
                                <td><a href="javascript:void(0)">username2</a></td>
                                <td class="hidden-phone">user2@example.com</td>
                                <td class="hidden-phone">Name</td>
                                <td class="hidden-phone">Last</td>
                                <td class="span3 text-center">
                                    <div class="btn-group">
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Details" class="btn btn-mini btn-info"><i class="icon-info-sign"></i></a>
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Edit" class="btn btn-mini btn-success"><i class="icon-pencil"></i></a>
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Delete" class="btn btn-mini btn-danger"><i class="icon-remove"></i></a>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="span1 text-center"><input type="checkbox" id="check3-td3" name="check3-td3"></td>
                                <td class="span1 text-center">3</td>
                                <td><a href="javascript:void(0)">username3</a></td>
                                <td class="hidden-phone">user3@example.com</td>
                                <td class="hidden-phone">Name</td>
                                <td class="hidden-phone">Last</td>
                                <td class="span3 text-center">
                                    <div class="btn-group">
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Details" class="btn btn-mini btn-info"><i class="icon-info-sign"></i></a>
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Edit" class="btn btn-mini btn-success"><i class="icon-pencil"></i></a>
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Delete" class="btn btn-mini btn-danger"><i class="icon-remove"></i></a>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="span1 text-center"><input type="checkbox" id="check3-td4" name="check3-td4"></td>
                                <td class="span1 text-center">4</td>
                                <td><a href="javascript:void(0)">username4</a></td>
                                <td class="hidden-phone">user4@example.com</td>
                                <td class="hidden-phone">Name</td>
                                <td class="hidden-phone">Last</td>
                                <td class="span3 text-center">
                                    <div class="btn-group">
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Details" class="btn btn-mini btn-info"><i class="icon-info-sign"></i></a>
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Edit" class="btn btn-mini btn-success"><i class="icon-pencil"></i></a>
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Delete" class="btn btn-mini btn-danger"><i class="icon-remove"></i></a>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                        </div>
                        
                        
                        
                        
                     </div>  
                   
                    <!-- End Your Content -->
               