<div id="main-content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    
                     <div class="btn-group">
                        <a href="<?php print($this->baseUrl());?>/admin/product/add/" id="table-edit_new" class="btn btn-danger">
                            <?php echo $this->translate("Add-New");?> <i class="fa fa-plus"></i>
                        </a>
                    </div>
                    
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 table-responsive m-t-20">
                           <table class="table table-bordered table_obtor_data table-hover">
                                <thead class="no-bd">
                                    <tr>
                                        <th class="table_id table_head"><?php echo $this->translate("ID");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Product-Name");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Type");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Sort-Order");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Pay-Type");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Stock");?></th>
                                        <th class="text-center table_head data_table_action"><?php echo $this->translate("Actions");?></th>
                                    </tr>
                                </thead>
                                <tbody class="no-bd-y">

                               <?php if($this->productAndServices){?>
			    <?php foreach($this->productAndServices As $index=>$productAndService){?>
                                    
                                    
                                    
                                    <?php if($productAndService->getProducts()){?>
                                            <tr>
                                                <td colspan="7">
                                                   <strong>Group Name: </strong>  <?php print($productAndService->getName());?>
                                                </td>
                                            </tr>
                                    
                                    
                                    <?php foreach($productAndService->getProducts() As $pIndex=>$products){?>
                                            <tr>
                                                <td>
                                                    <a title="<?php echo $this->translate("View");?>" href="#">
                                                    <?php print($products->getId());?>
                                                    </a>
                                                </td>
                                                <td><?php print($products->getProductName());?></td>
                                                <td><?php print($products->getProductType()->getName());?></td>
                                                <td><?php print($products->getSortOrder());?></td>
                                                <td><?php print(ucfirst($products->getPaytype()));?></td>
                                                
                                               <td>
                                                    <?php 
                                                    if($products->getStockcontrol() == 1){
                                                        print($products->getProductQty());
                                                    } else {
                                                        print("-");
                                                    }
                                                    ?>
                                               </td>
                                                
                                                <td class="text-center">
                                                    <a title="<?php echo $this->translate("Edit");?>" href="<?php print($this->baseUrl());?>/admin/product/edit/id/<?php print($products->getId());?>"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_edit.png" /></a>
                                                    <a title="<?php echo $this->translate("Delete");?>" href="<?php print($this->baseUrl());?>/admin/product/delete/id/<?php print($products->getId());?>" class="form-data-delete"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_drop.png" /></a>
                                                </td>
                                            </tr>
                                            <?php } ?>
                                             <?php } ?>
                                            
                                            
                                            
                                            
                                        <?php } ?>
			   <?php } else {?>
                                            <tr>
                                                <td colspan="7" class="table_data_not_found"><?php echo $this->translate("Records-Not-Available");?></td>
                                            </tr>
                                    <?php } ?>
                                            

                                </tbody>
                            </table>

                        </div>
                    </div>
                    
                    
                    <!-- The pagination comes here... -->
                    
                </div>
            </div>
        </div>
    </div>
</div>
