<div id="main-content">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    
                     <div class="btn-group">
                        <a href="<?php print($this->baseUrl()); ?>/admin/customer/add/" id="table-edit_new" class="btn btn-danger">
                            <?php echo $this->translate("Add-New");?> <i class="fa fa-plus"></i>
                        </a>
                    </div>
                    
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12 col-sm-12 col-xs-12 table-responsive m-t-20">
                            <table class="table table-bordered table_obtor_data table-hover">
                                <thead>
                                    <tr>
                                        <th class="table_id table_head"><?php echo $this->translate("ID");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("First-Name");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Last-Name");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Company-Name");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("E-Mail-Address");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Created");?></th>
                                        <th class="table_data table_head"><?php echo $this->translate("Status");?></th>
                                        <th class="text-center table_head data_table_action"><?php echo $this->translate("Actions");?></th>
                                    </tr>
                                </thead>
                                <tbody class="no-bd-y">

                                    <?php if($this->clients){?>
			    <?php foreach($this->clients As $index=>$client){?>
                            <tr>
                                <td class="span1 text-center"><?php print($client->getId());?></td>
                                <td><?php print($client->getFirstname());?></td>
                                <td><?php print($client->getLastname());?></td>
                                <td><?php print($client->getCompanyname());?></td>
                                <td class="hidden-phone"><?php print($client->getEmail());?></td>
                                <td><?php print($client->getDatecreated());?></td>
                                
                                <td>
                                    <?php if($client->getStatus() == 'Active') {?>
                                    <span class="label bg-green">Active</span>
                                    <?php }elseif($client->getStatus() == 'Inactive') {?>
                                    <span class="label bg-danger">Inactive</span>
                                    <?php } else {?>
                                    <span class="label bg-red">Closed</span>
                                    <?php } ?>
                                   
                                   
                                </td>
                                <td class="text-center">
                                                    <a title="<?php echo $this->translate("Edit");?>" href="<?php print($this->baseUrl()); ?>/admin/customer/edit/id/<?php print($client->getId()); ?>"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_edit.png" /></a>
                                                    <a title="<?php echo $this->translate("Delete");?>" href="<?php print($this->baseUrl()); ?>/admin/customer/delete/id/<?php print($client->getId()); ?>" class="form-data-delete"><img src="<?php print($this->baseUrl()); ?>/assets/skin/images/b_drop.png" /></a>
                                                </td>
                            </tr>
                            <?php } ?>
			   <?php } else {?>
                                            <tr>
                                                <td colspan="8" class="table_data_not_found"><?php echo $this->translate("Records-Not-Available");?></td>
                                            </tr>
                                    <?php } ?>

                                </tbody>
                            </table>

                        </div>
                    </div>
                    
                    
                    <?php if(count($this->clients)>0){?>
			<?php echo $this->partial('common/_pagination.phtml', array('paginationData' => $this->paggination)); ?>
                    <?php } ?>
                    
                </div>
            </div>
        </div>
    </div>
</div>
