                    <!-- Navigation info -->
                    <ul id="nav-info" class="clearfix">
                        <li><a href="index.html"><i class="icon-home"></i></a></li>
                        <li><a href="javascript:void(0)">Pages</a></li>
                        <li class="active"><a href="">Blank</a></li>
                    </ul>
                    <!-- END Navigation info -->

                    <!-- Your Content -->
                    
                    <h3 class="page-header page-header-top">Clients Profile</h3>
                      
                    
                        
                            
                         <!-- Tabs -->
                         <?php echo $this->partial('common/_client_links.phtml', array('clientId' => $this->clientInfo->getId(),'currentLink' => $this->actionName)); ?>
                         
                       
                   
                     	
                         
                        <table class="table table-hover">
                        <thead>
                            <tr>
                                <th class="span1 text-center">ID</th>
                                <th class="span3 text-center">Created</th>
                                <th>Note</th>
                                <th class="span1 text-center">Admin</th>
                                <th class="span2 text-center">Last Update</th>
                                <th class="span2 text-center"><i class="icon-bolt"></i> Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            
                            
                            
                        
                        </tbody>
                    </table>
                    <!-- END Default style -->

                    
                   
                    
                    
                    
                    
                   
                    <!-- End Your Content -->
                    <script>
$(document).on("change", "#cmbClientId", function(e) {
   var location = $(this).val();
   document.location.href = location;
   
});
</script>
                    
               