                    <!-- Navigation info -->
                    <ul id="nav-info" class="clearfix">
                        <li><a href="index.html"><i class="icon-home"></i></a></li>
                        <li><a href="javascript:void(0)">Pages</a></li>
                        <li class="active"><a href="">Blank</a></li>
                    </ul>
                    <!-- END Navigation info -->

                    <!-- Your Content -->
                    
                    <h3 class="page-header page-header-top">Clients Profile</h3>
                      
                     <div class="row-fluid">
                    
<p>Active Client: 
    
     <select id="cmbClientId"  name="cmbClientId" class="input-xlarge">
                                        <option value=""></option>
                                        <?php foreach($this->clientDetails As $cIndex=>$client){?>
                                        <option value="<?php print($this->baseUrl());?>/admin/client/view/id/<?php print($client->getId());?>"  <?php if($this->clientInfo->getId() == $client->getId()){?> selected="selected" <?php } ?> ><?php print($client->getCompanyname());?> - <?php print($client->getFirstname());?> <?php print($client->getLastname());?></option>
                                         <?php } ?>
                                        
                                    </select>
    
                     </div> 
                        
                            
                         <!-- Tabs -->
                         <?php echo $this->partial('common/_client_links.phtml', array('clientId' => $this->clientInfo->getId(),'currentLink' => $this->actionName)); ?>
                         
                         
                    <!-- END Tabs -->
                    <div class="row-fluid tab_content">
                     	<div class="span4"><div style="font-size:18px;">#<?php print($this->clientInfo->getId());?> - <?php print($this->clientInfo->getFirstname());?> <?php print($this->clientInfo->getLastname());?></div></div> 
                     	<div class="span8">
                            
                            <div class="clientsummaryactions">
                                Exempt from Tax: 
                                <span id="taxstatus" class="csajaxtoggle" style="text-decoration:underline;cursor:pointer">
                                    <?php if($this->clientInfo->getTaxexempt() == 'on'){?>
                                    <strong class="textgreen">Yes</strong>
                                    <?php } else {?>
                                     <strong class="textred">No</strong>
                                    <?php } ?>
                                </span>
                                &nbsp;&nbsp;
                                Auto CC Processing: <span id="autocc" class="csajaxtoggle" style="text-decoration:underline;cursor:pointer">
                                    
                                    <?php if($this->clientInfo->getDisableautocc() == 'on'){?>
                                    <strong class="textgreen">Yes</strong>
                                    <?php } else {?>
                                     <strong class="textred">No</strong>
                                    <?php } ?>
                                    
                                </span>
                                &nbsp;&nbsp;
                                Send Overdue Reminders: <span id="overduenotices" class="csajaxtoggle" style="text-decoration:underline;cursor:pointer">
                                    <?php if($this->clientInfo->getOverideduenotices() == 'on'){?>
                                    <strong class="textgreen">Yes</strong>
                                    <?php } else {?>
                                     <strong class="textred">No</strong>
                                    <?php } ?>
                                </span>
                                &nbsp;&nbsp;    
                                Apply Late Fees: <span id="latefees" class="csajaxtoggle" style="text-decoration:underline;cursor:pointer">
                                    <?php if($this->clientInfo->getLatefeeoveride() == 'on'){?>
                                    <strong class="textgreen">Yes</strong>
                                    <?php } else {?>
                                     <strong class="textred">No</strong>
                                    <?php } ?>
                                </span>
                            </div>
                        </div> 
                        
                        <div class="row-fluid" style="margin-top:2%;">
                        <!-- main 3 colum ariya -->
                        
                        		 <!--  colum1  -->
                            <div class="span4">
                            	<!--1-->
                            	<div class="clientssummarybox">
                                <div class="title">Clients Information</div>
                                <table class="clientssummarystats" cellpadding="2" cellspacing="0">
                                <tbody><tr><td width="110">First Name</td><td><?php print($this->clientInfo->getFirstname());?></td></tr>
                                <tr class="altrow"><td>Last Name</td><td><?php print($this->clientInfo->getLastname());?></td></tr>
                                <tr><td>Company Name</td><td><?php print($this->clientInfo->getCompanyname());?></td></tr>
                                <tr class="altrow"><td>Email Address</td><td><?php print($this->clientInfo->getEmail());?></td></tr>
                                <tr><td>Address 1</td><td><?php print($this->clientInfo->getAddress1());?></td></tr>
                                <tr class="altrow"><td><?php print($this->clientInfo->getAddress2());?></td><td></td></tr>
                                <tr><td>City</td><td><?php print($this->clientInfo->getCity());?></td></tr>
                                <tr class="altrow"><td>State/Region</td><td><?php print($this->clientInfo->getState());?></td></tr>
                                <tr><td>Postcode</td><td><?php print($this->clientInfo->getPostcode());?></td></tr>
                                <tr class="altrow"><td>Country</td><td>GB - <?php print($this->clientInfo->getCountry()->getName());?></td></tr>
                                <tr><td>Phone Number</td><td><?php print($this->clientInfo->getPhonenumber());?></td></tr>
                                </tbody></table>
                                <ul style="display: none;">
                                <li><a href="#" class="box_link" >
                                        <img src="<?php print($this->baseUrl());?>/content/admin/img/resetpw.png" border="0" align="absmiddle"> Reset &amp; Send Password
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="box_link">
                                        <img src="<?php print($this->baseUrl());?>/content/admin/img/offlinecc.png" border="0" align="absmiddle"> Credit Card Information
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="box_link">
                                        <img src="<?php print($this->baseUrl());?>/content/admin/img/clientlogin.png" border="0" align="absmiddle"> 
                                        Login as Client
                                    </a>
                                </li></ul>
                                </div>
                                
                                <!--2-->
                                <div class="clientssummarybox" style="display: none;">
                                <div class="title">Contacts/Sub-Accounts</div>
                                <table class="clientssummarystats" cellpadding="2" cellspacing="0">
                                <tbody><tr><td align="center">No additional contacts setup</td></tr>
                                </tbody></table>
                                <ul>
                                <li><a href=""><img src="<?php print($this->baseUrl());?>/content/admin/img/clientsadd.png" border="0" align="absmiddle"> Add Contact</a>
                                </li></ul>
                                </div>
                                <!--3-->
                                <div class="clientssummarybox">
                                <div class="title">Other Information</div>
                                <table class="clientssummarystats" cellpadding="2" cellspacing="0">
                                <tbody><tr><td width="110">Status</td><td><?php print($this->clientInfo->getStatus());?></td></tr>
                                <tr><td>Signup Date</td><td><?php print($this->clientInfo->getDatecreated());?></td></tr>
                                <tr class="altrow"><td>Client For</td><td><?php print($this->clintDuration);?></td></tr>
                                <tr><td width="110">Last Login</td><td><?php print($this->clientInfo->getLastlogin());?></td></tr>
                                </tbody></table>
                                </div>
                                
                            
                            </div>
                         	<!--  colum1 END  -->
                            <!--  colum2  -->
                             <div class="span4">
                             	<!--1-->
                                <div class="clientssummarybox">
                                <div class="title">Invoices/Billing</div>
                                <table class="clientssummarystats" cellpadding="2" cellspacing="0">
                                <tbody><tr><td width="110">Paid</td><td><?php print($this->totalPaidInvoice);?> (<?php print($this->clientCurrency->getCurrencySym());?><?php print($this->totalPaidAmount);?>  <?php print($this->clientCurrency->getName());?>)</td></tr>
                                <tr class="altrow"><td>Unpaid/Due</td><td><?php print($this->totalUnpaidDueCount);?> (<?php print($this->clientCurrency->getCurrencySym());?><?php print($this->totalUnpaidDueAmount);?>    <?php print($this->clientCurrency->getName());?>)</td></tr>
                                <tr><td>Cancelled</td><td><?php print($this->countCancelledInvoice);?> (<?php print($this->clientCurrency->getCurrencySym());?><?php print($this->totalCancelledAmount);?>    <?php print($this->clientCurrency->getName());?>)</td></tr>
                                <tr class="altrow"><td>Refunded</td><td><?php print($this->countRefundedInvoice);?> (<?php print($this->clientCurrency->getCurrencySym());?><?php print($this->totalRefundedAmount);?>    <?php print($this->clientCurrency->getName());?>)</td></tr>
                            
                                <tr class="altrow"><td><strong>Income</strong></td><td><strong><?php print($this->clientCurrency->getCurrencySym());?><?php print($this->totalPaidAmount);?>  <?php print($this->clientCurrency->getName());?></strong></td></tr>
                                
                                </tbody></table>
                                <ul style="display: none;">
                                <li><a href="" class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/invoicesedit.png" border="0" align="absmiddle"> Create Invoice</a>
                                </li><li><a href="#" onclick="" class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/addfunds.png" border="0" align="absmiddle"> Create Add Funds Invoice</a>
                                </li><li><a href="#" onclick="" class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/ticketspredefined.png" border="0" align="absmiddle"> Generate Due Invoices</a>
                                </li><li><a href="" class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/billableitems.png" border="0" align="absmiddle"> Add Billable Item</a>
                                </li><li><a href="#" onclick="" class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/income.png" border="0" align="absmiddle"> Manage Credits</a>
                                </li><li><a href="" class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/quotes.png" border="0" align="absmiddle"> Create New Quote</a>
                                </li></ul>
                                </div>
                             	<!--2-->
                                <div class="clientssummarybox" style="display: none;">
                                <div class="title">Files</div>
                                <table class="clientssummarystats" cellpadding="2" cellspacing="0">
                                <tbody><tr><td align="center">No files uploaded</td></tr>
                                </tbody></table>
                                <ul>
                                <li><a href="#" id="addfile"><img src="<?php print($this->baseUrl());?>/content/admin/img/add.png" border="0" align="absmiddle"> Add File</a>
                                </li></ul>
                                <div id="addfileform" style="display:none;">
                                <img src="<?php print($this->baseUrl());?>/content/admin/img/spacer.gif" height="4" width="1"><br>
                                <form method="post" action="clientssummary.php?userid=258&amp;action=uploadfile" enctype="multipart/form-data">
                                <input name="token" value="93a1cef13ed544eb3ee2405d093d41ee6f9d9edf" type="hidden">
                                <table class="clientssummarystats" cellpadding="2" cellspacing="0">
                                <tbody><tr><td width="40">Title</td><td class="fieldarea"><input name="title" style="width:90%" type="text"></td></tr>
                                <tr><td>File</td><td class="fieldarea"><input name="uploadfile" style="width:90%" type="file"></td></tr>
                                <tr><td></td><td class="fieldarea"><input name="adminonly" value="1" type="checkbox"> Admin Only &nbsp;&nbsp;&nbsp;&nbsp; <input value="Submit" type="submit"></td></tr>
                                </tbody></table>
                                </form>
                                </div>
                                </div>
                                <!--3-->
                                <div class="clientssummarybox">
                                <div class="title">Recent Emails</div>
                                <table class="clientssummarystats" cellpadding="2" cellspacing="0">
                                <tbody>
                                    <?php foreach($this->maillogs As $mIndex=>$mailLog){?>
                                    <tr class="">
                                        <td align="center">
                                            <?php print($mailLog->getDate());?> - 
                                            <a href="#" onclick="" class="textblack">
                                                <?php print($mailLog->getSubject());?>
                                            </a>
                                        </td>
                                    </tr>
                                    <?php } ?>
                                    
                                </tbody></table>
                                </div>
                                
                             
                             </div>
                            
                            <!--  colum2 END  -->
                        	 <!--  colum3  -->
                             <div class="span4">
                             	<!--1-->
                             	<div class="clientssummarybox">
                                <div class="title">Products/Services</div>
                                <table class="clientssummarystats" cellpadding="2" cellspacing="0">
                                <tbody>
                                    <?php foreach($this->productGroups As $pgIndex=>$productGroup){?>
                                    <tr><td width="140"><?php print($productGroup->name);?></td><td><?php print($productGroup->numberOfOrder);?> (<?php print($productGroup->numberOfOrder);?> Total)</td></tr>
                                    <?php } ?>
                                    
                                <tr class="altrow"><td>Domains</td><td><?php print($this->totalNumberOfDomains);?> (<?php print($this->totalNumberOfDomains);?> Total)</td></tr>
                                <tr><td>Support Tickets</td><td><?php print($this->totalNumberOfTickets);?> (<?php print($this->totalNumberOfTickets);?> Total)</td></tr>
                                <tr class="altrow"><td>Affiliate Signups</td><td>0</td></tr>
                                </tbody></table>
                                <ul>
                                <li>
                                    <a href="<?php print($this->baseUrl());?>/admin/order/index/client/<?php print($this->clientInfo->getId());?>" class="box_link">
                                        <img src="<?php print($this->baseUrl());?>/content/admin/img/orders.png" border="0" align="absmiddle"> View Orders
                                    </a>
                                </li><li>
                                    <a href="<?php print($this->baseUrl());?>/admin/order/add/client/<?php print($this->clientInfo->getId());?>" class="box_link">
                                        <img src="<?php print($this->baseUrl());?>/content/admin/img/ordersadd.png" border="0" align="absmiddle"> Add New Order</a>
                                </li></ul>
                                </div>
                             	<!--2-->
                                <div class="clientssummarybox" style="display: none;">
                                    <div class="title">Send Email</div>
                                    <form action="clientsemails.php?userid=258&amp;action=send&amp;type=general" method="post">
                                    <input name="token" value="93a1cef13ed544eb3ee2405d093d41ee6f9d9edf" type="hidden">
                                    <input name="id" value="258" type="hidden">
                                    <div align="center"><select name="messagename"><option selected="selected" value="newmessage">New Message</option><option value="Automated Password Reset">Automated Password Reset</option><option value="Client Signup Email">Client Signup Email</option><option value="Credit Card Expiring Soon">Credit Card Expiring Soon</option><option value="Order Confirmation">Order Confirmation</option><option value="Password Reset Confirmation">Password Reset Confirmation</option><option value="Quote Accepted">Quote Accepted</option><option value="Quote Accepted Notification">Quote Accepted Notification</option><option value="Quote Delivery with PDF">Quote Delivery with PDF</option><option value="Thompsons" style="background-color:#efefef">Thompsons</option></select> <input value="Go" class="btn btn-small" type="submit"></div>
                                    </form>
                                    </div>
                                    <!--3-->
                                    <div class="clientssummarybox" style="display: none;">
                                    <div class="title">Other Actions</div>
                                    <ul>
                                    <li><a href="" class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/reports.png" border="0" align="absmiddle"> View Account Statement</a>
                                    </li><li><a href=""  class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/ticketsopen.png" border="0" align="absmiddle"> Open New Support Ticket</a>
                                    </li><li><a href=""  class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/ticketsother.png" border="0" align="absmiddle"> View all Support Tickets</a>
                                    </li><li><a href=""  class="box_link"><img src="<?php print($this->baseUrl());?>/content/admin/img/affiliates.png" border="0" align="absmiddle"> Activate as Affiliate</a>
                                    </li><li><a href="#"  class="box_link" onclick=""><img src="<?php print($this->baseUrl());?>/content/admin/img/clients.png" border="0" align="absmiddle"> Merge Clients Accounts</a>
                                    </li><li><a href="#"  class="box_link" onclick="" style="color:#000000;"><img src="<?php print($this->baseUrl());?>/content/admin/img/delete.png" border="0" align="absmiddle"> Close Clients Account</a>
                                    </li><li><a href="#"  class="box_link" onclick="" style="color:#CC0000;"><img src="<?php print($this->baseUrl());?>/content/admin/img/delete.png" border="0" align="absmiddle"> Delete Clients Account</a>
                                    </li></ul>
                                    </div>
                                    
                                    <div class="clientssummarybox" style="display: none;">
                                    <div class="title">Admin Notes</div>
                                    <form method="post" action="">
                                    <input name="token" value="" type="hidden">
                                    <div align="center">
                                    <textarea name="adminnotes" rows="6" style="width:90%;"></textarea><br>
                                    <input value="Submit" class="btn" type="submit">
                                    </div>
                                    </form>
                                    </div>
                                
                             
                             </div>

                              <!--  colum3 END  -->
                              
                              
                         <!-- main colum ariya -->
                         </div>
                        
                        <div class="row-fluid" style="display: none;">
                      		<table class="table table-hover">
                        <thead>
                            <tr>
                                <th class="span1 text-center" data-toggle="tooltip" title="Toggle all!"><input type="checkbox" id="check3-all" name="check3-all"></th>
                                <th class="span1 text-center">#</th>
                                <th>Username</th>
                                <th class="hidden-phone"><i class="icon-envelope-alt"></i> Email</th>
                                <th class="hidden-phone">Firstname</th>
                                <th class="hidden-phone">Lastname</th>
                                <th class="span3 text-center"><i class="icon-bolt"></i> Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td class="span1 text-center"><input type="checkbox" id="check3-td1" name="check3-td1"></td>
                                <td class="span1 text-center">1</td>
                                <td><a href="javascript:void(0)">username1</a></td>
                                <td class="hidden-phone">user1@example.com</td>
                                <td class="hidden-phone">Name</td>
                                <td class="hidden-phone">Last</td>
                                <td class="span3 text-center">
                                    <div class="btn-group">
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Details" class="btn btn-mini btn-info"><i class="icon-info-sign"></i></a>
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Edit" class="btn btn-mini btn-success"><i class="icon-pencil"></i></a>
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Delete" class="btn btn-mini btn-danger"><i class="icon-remove"></i></a>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="span1 text-center"><input type="checkbox" id="check3-td2" name="check3-td2"></td>
                                <td class="span1 text-center">2</td>
                                <td><a href="javascript:void(0)">username2</a></td>
                                <td class="hidden-phone">user2@example.com</td>
                                <td class="hidden-phone">Name</td>
                                <td class="hidden-phone">Last</td>
                                <td class="span3 text-center">
                                    <div class="btn-group">
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Details" class="btn btn-mini btn-info"><i class="icon-info-sign"></i></a>
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Edit" class="btn btn-mini btn-success"><i class="icon-pencil"></i></a>
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Delete" class="btn btn-mini btn-danger"><i class="icon-remove"></i></a>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="span1 text-center"><input type="checkbox" id="check3-td3" name="check3-td3"></td>
                                <td class="span1 text-center">3</td>
                                <td><a href="javascript:void(0)">username3</a></td>
                                <td class="hidden-phone">user3@example.com</td>
                                <td class="hidden-phone">Name</td>
                                <td class="hidden-phone">Last</td>
                                <td class="span3 text-center">
                                    <div class="btn-group">
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Details" class="btn btn-mini btn-info"><i class="icon-info-sign"></i></a>
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Edit" class="btn btn-mini btn-success"><i class="icon-pencil"></i></a>
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Delete" class="btn btn-mini btn-danger"><i class="icon-remove"></i></a>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td class="span1 text-center"><input type="checkbox" id="check3-td4" name="check3-td4"></td>
                                <td class="span1 text-center">4</td>
                                <td><a href="javascript:void(0)">username4</a></td>
                                <td class="hidden-phone">user4@example.com</td>
                                <td class="hidden-phone">Name</td>
                                <td class="hidden-phone">Last</td>
                                <td class="span3 text-center">
                                    <div class="btn-group">
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Details" class="btn btn-mini btn-info"><i class="icon-info-sign"></i></a>
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Edit" class="btn btn-mini btn-success"><i class="icon-pencil"></i></a>
                                        <a href="javascript:void(0)" data-toggle="tooltip" title="Delete" class="btn btn-mini btn-danger"><i class="icon-remove"></i></a>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                        </div>
                        
                        
                        
                        
                     </div>  
                   
                    <!-- End Your Content -->
                    <script>
$(document).on("change", "#cmbClientId", function(e) {
   var location = $(this).val();
   document.location.href = location;
   
});
</script>
                    
               