                    <!-- Navigation info -->
                    <ul id="nav-info" class="clearfix">
                        <li><a href="index.html"><i class="icon-home"></i></a></li>
                        <li><a href="javascript:void(0)">Pages</a></li>
                        <li class="active"><a href="">Blank</a></li>
                    </ul>
                    <!-- END Navigation info -->

                    <!-- Your Content -->
                    
                    <h3 class="page-header page-header-top">Clients Profile</h3>
                      
                    
                        
                            
                         <!-- Tabs -->
                         <?php echo $this->partial('common/_client_links.phtml', array('clientId' => $this->clientInfo->getId(),'currentLink' => $this->actionName)); ?>
                         
                       
                   
                         
                        
                        <table class="table table-hover">
                        <thead>
                            <tr>
                                <th class="span1 text-center">ID</th>
                                <th>Client Name</th>
                                <th class="span1 text-center">Date</th>
                                <th>Payment Method</th>
                                <th class="span3">Description</th>
                                <th class="span1 text-center">Amount In</th>
                                <th class="span1 text-center">Fees</th>
                                <th class="span1 text-center">Amount Out</th>
                                <th class="span2 text-center"><i class="icon-bolt"></i> Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            
                            
                            <?php if($this->transactions){?>
			    <?php foreach($this->transactions As $index=>$transaction){?>
                            <tr>
                                <td class="span1 text-center"><?php print($index+1);?></td>
                                <td><?php print($transaction->getClient()->getCompanyname());?></td>
                                <td><?php print($transaction->getDate());?></td>
                                <td><?php print($transaction->getGateway()->getName());?></td>
                                <td><?php print($transaction->getDescription());?></td>
                                <td><?php print($transaction->getAmountIn());?></td>
                                <td><?php print($transaction->getFees());?></td>
                                <td><?php print($transaction->getAmountOut());?></td>
                              
                                
                                <td class="span1 text-center">
                                    
                                    <div class="btn-group">
                                        <a href="<?php print($this->baseUrl());?>/admin/billing/edit-transactions/id/<?php print($transaction->getId());?>" data-toggle="tooltip" title="Edit" class="btn btn-mini btn-success"><i class="icon-pencil"></i></a>
                                        <a href="<?php print($this->baseUrl());?>/admin/billing/delete-transaction/id/<?php print($transaction->getId());?>" data-toggle="tooltip" title="Delete" class="btn btn-mini btn-danger"><i class="icon-remove"></i></a>
                                    </div>
                                </td>
                            </tr>
                            <?php } ?>
			    <?php } ?>
                            
                        
                        </tbody>
                    </table>
                    <!-- END Default style -->
                    <!-- END Default style --> 
                        
             
                    
                    
                    
                    
                   
                    <!-- End Your Content -->
                    <script>
$(document).on("change", "#cmbClientId", function(e) {
   var location = $(this).val();
   document.location.href = location;
   
});
</script>
                    
               