<div id="main-content">

    <div class="row">
        <div class="col-md-12">



            <div class="panel panel-default">

                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-5">
                            <form id="form_attendance" name="form_attendance" role="form" method="get" class="form-horizontal" action="<?php print($this->baseUrl());?>/admin/attendance/">
                                <div class="form-group">
                                    <label class="form-label"><strong><?php echo $this->translate("Date-On"); ?></strong></label>
                                    <div class="input-icon right">
                                        <i class="fa"></i>
                                        <input parsley-minlength="3" class="form-control pickadate" type="text" name="report_date" id="report_date"/>
                                    </div>
                                </div>

                        
                                <div class="form-group text-left">
                                    <button class="btn btn-blue" type="submit" name="Submit" id="Submit"><?php echo $this->translate("Search"); ?></button>
                                    <button type="reset" class="btn btn-default"><?php echo $this->translate("Cancel"); ?></button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>



        </div>
    </div>




</div>