<div id="main-content">

    <div class="row">
        <div class="col-md-12">


          
                <div class="panel panel-default">
                    
                    <div class="panel-heading">
                        
                        <div class="btn-group">
                        <a href="<?php print($this->baseUrl()); ?>/admin/attendance/edit/id/<?php print($this->attendanceInformation->getId());?>" id="table-edit_new" class="btn btn-warning">
                            <?php echo $this->translate("Edit-Record");?> <i class="fa fa-edit"></i>
                        </a>
                    </div>
                        
                    <div class="btn-group pull-right">
                        <a href="#" id="form-data-back" class="btn btn-blue">
                            <?php echo $this->translate("Go-back");?> <i class="fa fa-backward"></i>
                        </a>
                    </div>
           
                </div>

                    <div class="panel-body">


                        <div class="row">
                            <div class="col-md-12">
                                
                               <div class="col-md-12 col-sm-12 col-xs-12 m-b-10">
                                   
                                   <div class="view_information">
                                            <ul>
                                                <li>
                                                    <span><?php echo $this->translate("Date-On"); ?></span>
                                                   : <?php print($this->attendanceInformation->getDateOn());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                            <li>
                                                    <span><?php echo $this->translate("Is-Working-Day"); ?></span>
                                                   : <?php print($this->attendanceInformation->getIsWorkingDay());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Scheduled-On-Time"); ?></span>
                                                   : <?php print($this->attendanceInformation->getScheduledOnTime());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Scheduled-Off-Time"); ?></span>
                                                   : <?php print($this->attendanceInformation->getScheduledOffTime());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                 <li>
                                                    <span><?php echo $this->translate("Attendance-In-Time"); ?></span>
                                                   : <?php print($this->attendanceInformation->getAttendanceInTime());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Attendance-Out-Time"); ?></span>
                                                   : <?php print($this->attendanceInformation->getAttendanceOutTime());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Is-Late"); ?></span>
                                                   : <?php print($this->attendanceInformation->getIsLate());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Is-Early-Off"); ?></span>
                                                   : <?php print($this->attendanceInformation->getIsEarlyOff());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Other-In-Out"); ?></span>
                                                   : <?php print($this->attendanceInformation->getOtherInOut());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Remarks"); ?></span>
                                                   : <?php print($this->attendanceInformation->getRemarks());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("In-Time-Fp-Serial"); ?></span>
                                                   : <?php print($this->attendanceInformation->getInTimeFpSerial());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Out-Time-Fp-Serial"); ?></span>
                                                   : <?php print($this->attendanceInformation->getOutTimeFpSerial());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("In-Time-Status-Exempted"); ?></span>
                                                   : <?php print($this->attendanceInformation->getInTimeStatusExempted());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Out-Time-Status-Exempted"); ?></span>
                                                   : <?php print($this->attendanceInformation->getOutTimeStatusExempted());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                 <li>
                                                    <span><?php echo $this->translate("In-Time-Execused"); ?></span>
                                                   : <?php print($this->attendanceInformation->getInTimeExecused());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                 <li>
                                                    <span><?php echo $this->translate("Out-Time-Execused"); ?></span>
                                                   : <?php print($this->attendanceInformation->getOutTimeExecused());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("In-Time-Different-Min"); ?></span>
                                                   : <?php print($this->attendanceInformation->getInTimeDifferentMin());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Out-Time-Different-Min"); ?></span>
                                                   : <?php print($this->attendanceInformation->getOutTimeDifferentMin());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                 <li>
                                                    <span><?php echo $this->translate("In-Time-Different-Min-Type"); ?></span>
                                                   : <?php print($this->attendanceInformation->getInTimeDifferentMinType());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Out-Time-Different-Min-Type"); ?></span>
                                                   : <?php print($this->attendanceInformation->getOutTimeDifferentMinType());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Is-On-Leave"); ?></span>
                                                   : <?php print($this->attendanceInformation->getIsOnLeave());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Counted-Working-Day"); ?></span>
                                                   : <?php print($this->attendanceInformation->getCountedWorkingDay());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                 <li>
                                                    <span><?php echo $this->translate("Extra-Working-Hrs"); ?></span>
                                                   : <?php print($this->attendanceInformation->getExtraWorkingHrs());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("ExtraWorkingHrsApproved"); ?></span>
                                                   : <?php print($this->attendanceInformation->getExtraWorkingHrsApproved());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Approved-Extra-Working-Hrs"); ?></span>
                                                   : <?php print($this->attendanceInformation->getApprovedExtraWorkingHrs());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Is-Paid-For-Extra-Hrs"); ?></span>
                                                   : <?php print($this->attendanceInformation->getIsPaidForExtraHrs());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                <li>
                                                    <span><?php echo $this->translate("Manually-Added-Or-Edited"); ?></span>
                                                   : <?php print($this->attendanceInformation->getManuallyAddedOrEdited());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                                 <li>
                                                    <span><?php echo $this->translate("Employee-ID"); ?></span>
                                                   : <?php print($this->attendanceInformation->getEmployee());?>
                                                    <div class="clear"></div>
                                                </li>
                                                
                                               
                                                
                                            </ul>
                                    </div>
                                  
                               </div>
                            </div>
                       
                        </div>
                        
                    </div>

                </div>
        </div>
    </div>




</div>