                  <!-- Navigation info -->
                    <ul id="nav-info" class="clearfix">
                        <li><a href="<?php print($this->baseUrl());?>/admin/"><i class="icon-home"></i></a></li>
                        <li><a href="<?php print($this->baseUrl());?>/admin/client/">View/Search Clients</a></li>
                        <li class="active"><a href="#">Edit Client</a></li>
                    </ul>
                    <!-- END Navigation info -->

                    <!-- Text Inputs -->
                    <form class="form-horizontal form-box remove-margin" method="post" action="" id="form-validation" novalidate="novalidate">
                        <h4 class="form-box-header">Edit Client</h4>
                        

                        <div class="form-box-content">
                            
                            
                            
                            <table class="table">

<tbody>
<tr>
<td>
   First Name
</td>
<td>
    <input type="text" id="first_name" name="first_name" class="input-xlarge" value="<?php print($this->clientInfo->getFirstname());?>" >
</td>
<td>
   Address 1
</td>
<td>
    <input type="text" id="address1" name="address1" class="input-xlarge" value="<?php print($this->clientInfo->getAddress1());?>">
</td>
</tr>

<tr>
<td>
   Last Name
</td>
<td>
    <input type="text" id="last_name" name="last_name" class="input-xlarge" value="<?php print($this->clientInfo->getLastname());?>">
</td>
<td>
   Address 2
</td>
<td>
    <input type="text" id="address2" name="address2" class="input-xlarge" value="<?php print($this->clientInfo->getAddress2());?>">
</td>
</tr>

<tr>
<td>
   Company Name
</td>
<td>
    <input type="text" id="company_name" name="company_name" class="input-xlarge" value="<?php print($this->clientInfo->getCompanyname());?>">
</td>
<td>
   City
</td>
<td>
    <input type="text" id="city_name" name="city_name" class="input-xlarge" value="<?php print($this->clientInfo->getCity());?>">
</td>
</tr>


<tr>
<td>
   Email Address
</td>
<td>
    <input type="text" id="email_address" name="email_address" class="input-xlarge" value="<?php print($this->clientInfo->getEmail());?>">
</td>
<td>
   State/Region
</td>
<td>
    <input type="text" id="state_region" name="state_region" class="input-xlarge" value="<?php print($this->clientInfo->getState());?>">
</td>
</tr>


<tr>
<td>
   Password
</td>
<td>
    <input type="text" id="client_password" name="client_password" class="input-xlarge">
</td>
<td>
  Postcode
</td>
<td>
    <input type="text" id="post_code" name="post_code" class="input-xlarge" value="<?php print($this->clientInfo->getPostcode());?>">
</td>
</tr>

<tr>
<td>
   Security Question
</td>
<td>
    <select name="security_question" id="security_question" class="input-xlarge">
        <option value="">Please select</option>
    </select>
    
</td>
<td>
 Country
</td>
<td>
    <select name="country_name" id="country_name" class="input-xlarge">
        <option value="">Please select</option>
    </select>
</td>
</tr>


<tr>
<td>
   Security Answer
</td>
<td>
    <input type="text" id="security_answer" name="security_answer" class="input-xlarge" value="<?php print($this->clientInfo->getSecurityqans());?>">
</td>
<td>
 Phone Number
</td>
<td>
    <input type="text" id="phone_number" name="phone_number" class="input-xlarge" value="<?php print($this->clientInfo->getPhonenumber());?>">
</td>
</tr>


<tr>

<td colspan="4">
    &nbsp;
</td>


</tr>

<tr>
<td>
   Late Fees
</td>
<td>
    <label for="late_fees" class="checkbox">
        <input type="checkbox" value="1" name="late_fees" id="late_fees" <?php if($this->clientInfo->getLatefeeoveride() == 1){?> checked="checked" <?php } ?>> Don't Apply Late Fees
    </label>
</td>
<td>
 Payment Method
</td>
<td>
   <select name="payment_method" id="payment_method" class="input-xlarge">
        <option value="">Please select</option>
    </select>
</td>
</tr>


<tr>
<td>
   Overdue Notices
</td>
<td>
    <label for="overdue_notices" class="checkbox">
        <input type="checkbox" value="1" name="overdue_notices" id="overdue_notices" <?php if($this->clientInfo->getOverideduenotices() == 1){?> checked="checked" <?php } ?>> Don't Send Overdue Emails
    </label>
</td>
<td>
 Billing Contact
</td>
<td>
    <select name="billing_contact" id="billing_contact" class="input-xlarge">
        <option value="">Please select</option>
    </select>
</td>
</tr>

<tr>
<td>
   Tax Exempt
</td>
<td>
    <label for="tax_exempt" class="checkbox">
        <input type="checkbox" value="1" name="tax_exempt" id="tax_exempt" <?php if($this->clientInfo->getTaxexempt() == 1){?> checked="checked" <?php } ?>> Don't Apply Tax to Invoices
    </label>
</td>
<td>
 Language
</td>
<td>
    <select name="language" id="language" class="input-xlarge">
        <option value="">Please select</option>
    </select>
</td>
</tr>


<tr>
<td>
   Separate Invoices
</td>
<td>
    <label for="tax_exempt" class="checkbox">
        <input type="checkbox" value="1" name="separate_invoices" id="separate_invoices" <?php if($this->clientInfo->getSeparateinvoices() == 1){?> checked="checked" <?php } ?>> Separate Invoices for Services
    </label>
</td>
<td>
 Status
</td>
<td>
    <select name="status" id="status" class="input-xlarge">
        <option value="">Please select</option>
    </select>
</td>
</tr>


<tr>
<td>
   Disable CC Processing
</td>
<td>
    <label for="disable_cc_processing" class="checkbox">
        <input type="checkbox" value="1" name="disable_cc_processing" id="disable_cc_processing" <?php if($this->clientInfo->getDisableautocc() == 1){?> checked="checked" <?php } ?>> Disable Automatic CC Processing
    </label>
</td>
<td>
Currency
</td>
<td>
    <select name="currency" id="currency" class="input-xlarge">
        <option value="">Please select</option>
    </select>
</td>
</tr>


<tr>
<td>
   Admin Notes
</td>
<td colspan="3">
    <textarea rows="3" class="textarea-large" id="admin_notes" name="admin_notes"><?php print($this->clientInfo->getNotes());?></textarea>
</td>


</tr>







</tbody>
</table>
                            
                            
                            


                            <div class="form-actions">
                                <button class="btn btn-success"><i class="icon-save"></i> Save</button>
                                <button class="btn btn-danger"><i class="icon-remove"></i> Delete</button>
                                <input type="hidden" name="txtId" value="<?php print($this->clientInfo->getId());?>" />
                            </div>
                        </div>
                    </form>
                    <!-- END Text Inputs -->
