<div id="main-content">

    <div class="row">
        <div class="col-md-12">



            <div class="panel panel-default">

                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-12">
                            <form id="form_attendance" name="form_attendance" role="form" method="get" class="form-horizontal" action="<?php print($this->baseUrl());?>/admin/order/index/">
                                <div class="form-group">
                                    <label class="form-label"><strong><?php echo $this->translate("Date-From"); ?></strong></label>
                                    <div class="input-icon right">
                                        <i class="fa"></i>
                                        <input parsley-minlength="3" class="form-control normal_input" type="text" name="date-from" id="date-from"/>
                                    </div>
                                </div>
                                
                                <div class="form-group">
                                    <label class="form-label"><strong><?php echo $this->translate("Date-To"); ?></strong></label>
                                    <div class="input-icon right">
                                        <i class="fa"></i>
                                        <input parsley-minlength="3" class="form-control normal_input" type="text" name="date-to" id="date-to"/>
                                    </div>
                                </div>
                                
                                
                                <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Order-Status");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                                <select id="order-status"  name="order-status" class="form-control normal_input">
                                                    <option value=""></option>
                                                     <option value="Pending">Pending</option>
                                                     <option value="Active">Active</option>
                                                     <option value="Fraud">Fraud</option>
                                                     <option value="Cancelled">Cancelled</option>
                                                </select>
                                            </div>
                                        </div>
                                
                                <div class="form-group">
                                            <label class="form-label"><strong><?php echo $this->translate("Client");?></strong></label>
                                            <div class="input-icon right">
                                                <i class="fa"></i>
                                               <select id="client"  name="client" class="form-control normal_input">
                                                    <option value=""></option>
                                                    <?php foreach($this->clientDetails As $cIndex=>$client){?>
                                                    <option value="<?php print($client->getId());?>"  <?php if($this->clientId == $client->getId()){?> selected="selected" <?php } ?> ><?php print($client->getCompanyname());?> - <?php print($client->getFirstname());?> <?php print($client->getLastname());?></option>
                                                    <?php } ?>
                                                </select>
                                            </div>
                                        </div>

                        
                                <div class="form-group text-left">
                                    <button class="btn btn-blue" type="submit" name="Submit" id="Submit"><?php echo $this->translate("Search"); ?></button>
                                    <button type="reset" class="btn btn-default"><?php echo $this->translate("Cancel"); ?></button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>



        </div>
    </div>




</div>