<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Chain Responsive Bootstrap3 Admin</title>

        <link href="<?php print($this->baseUrl());?>/assets/admin-login/css/style.default.css" rel="stylesheet">

        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="<?php print($this->baseUrl());?>/assets/admin-login/js/html5shiv.js"></script>
        <script src="<?php print($this->baseUrl());?>/assets/admin-login/js/respond.min.js"></script>
        <![endif]-->
    </head>

    <body class="signin">
        
        
        <section>
            
            <div class="panel panel-signin">
                <div class="panel-body">
                    <div class="logo text-center">
                        <img src="<?php print($this->baseUrl());?>/assets/admin-login/images/logo-primary.png" alt="Chain Logo" >
                    </div>
                    <br />
                    <p class="text-center">Sign in to your account</p>
                    
                    <div class="mb30"></div>
                    
                    <?php echo $this->layout()->content ?>
                    
                </div><!-- panel-body -->
                <div class="panel-footer">
                    <a href="signup.html" class="btn btn-primary btn-block">Not yet a Member? Create Account Now</a>
                </div><!-- panel-footer -->
            </div><!-- panel -->
            
        </section>


        <script src="<?php print($this->baseUrl());?>/assets/admin-login/js/jquery-1.11.1.min.js"></script>
        <script src="<?php print($this->baseUrl());?>/assets/admin-login/js/jquery-migrate-1.2.1.min.js"></script>
        <script src="<?php print($this->baseUrl());?>/assets/admin-login/js/bootstrap.min.js"></script>
        <script src="<?php print($this->baseUrl());?>/assets/admin-login/js/modernizr.min.js"></script>
        <script src="<?php print($this->baseUrl());?>/assets/admin-login/js/pace.min.js"></script>
        <script src="<?php print($this->baseUrl());?>/assets/admin-login/js/retina.min.js"></script>
        <script src="<?php print($this->baseUrl());?>/assets/admin-login/js/jquery.cookies.js"></script>

        <script src="<?php print($this->baseUrl());?>/assets/admin-login/js/custom.js"></script>

    </body>
</html>